/* DictionaryBase.c generated by valac 0.26.2, the Vala compiler
 * generated from DictionaryBase.vala, do not modify */

/* Copyright (c) Microsoft. All rights reserved.*/
/* Licensed under the MIT license. See LICENSE file in the project root for full license information.*/
/*============================================================
**
** Class:  DictionaryBase
**
** Purpose: Provides the abstract base class for a
**          strongly typed collection of key/value pairs.
**
===========================================================*/

#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define SYSTEM_COLLECTIONS_TYPE_IENUMERABLE (system_collections_ienumerable_get_type ())
#define SYSTEM_COLLECTIONS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, SystemCollectionsIEnumerable))
#define SYSTEM_COLLECTIONS_IS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE))
#define SYSTEM_COLLECTIONS_IENUMERABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, SystemCollectionsIEnumerableIface))

typedef struct _SystemCollectionsIEnumerable SystemCollectionsIEnumerable;
typedef struct _SystemCollectionsIEnumerableIface SystemCollectionsIEnumerableIface;

#define SYSTEM_COLLECTIONS_TYPE_IENUMERATOR (system_collections_ienumerator_get_type ())
#define SYSTEM_COLLECTIONS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, SystemCollectionsIEnumerator))
#define SYSTEM_COLLECTIONS_IS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR))
#define SYSTEM_COLLECTIONS_IENUMERATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, SystemCollectionsIEnumeratorIface))

typedef struct _SystemCollectionsIEnumerator SystemCollectionsIEnumerator;
typedef struct _SystemCollectionsIEnumeratorIface SystemCollectionsIEnumeratorIface;

#define SYSTEM_COLLECTIONS_TYPE_ICOLLECTION (system_collections_icollection_get_type ())
#define SYSTEM_COLLECTIONS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, SystemCollectionsICollection))
#define SYSTEM_COLLECTIONS_IS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION))
#define SYSTEM_COLLECTIONS_ICOLLECTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, SystemCollectionsICollectionIface))

typedef struct _SystemCollectionsICollection SystemCollectionsICollection;
typedef struct _SystemCollectionsICollectionIface SystemCollectionsICollectionIface;

#define SYSTEM_COLLECTIONS_TYPE_IDICTIONARY (system_collections_idictionary_get_type ())
#define SYSTEM_COLLECTIONS_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, SystemCollectionsIDictionary))
#define SYSTEM_COLLECTIONS_IS_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY))
#define SYSTEM_COLLECTIONS_IDICTIONARY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, SystemCollectionsIDictionaryIface))

typedef struct _SystemCollectionsIDictionary SystemCollectionsIDictionary;
typedef struct _SystemCollectionsIDictionaryIface SystemCollectionsIDictionaryIface;

#define SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR (system_collections_idictionary_enumerator_get_type ())
#define SYSTEM_COLLECTIONS_IDICTIONARY_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR, SystemCollectionsIDictionaryEnumerator))
#define SYSTEM_COLLECTIONS_IS_IDICTIONARY_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR))
#define SYSTEM_COLLECTIONS_IDICTIONARY_ENUMERATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR, SystemCollectionsIDictionaryEnumeratorIface))

typedef struct _SystemCollectionsIDictionaryEnumerator SystemCollectionsIDictionaryEnumerator;
typedef struct _SystemCollectionsIDictionaryEnumeratorIface SystemCollectionsIDictionaryEnumeratorIface;

#define SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY (system_collections_dictionary_entry_get_type ())
#define SYSTEM_COLLECTIONS_DICTIONARY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, SystemCollectionsDictionaryEntry))
#define SYSTEM_COLLECTIONS_DICTIONARY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, SystemCollectionsDictionaryEntryClass))
#define SYSTEM_COLLECTIONS_IS_DICTIONARY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY))
#define SYSTEM_COLLECTIONS_IS_DICTIONARY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY))
#define SYSTEM_COLLECTIONS_DICTIONARY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, SystemCollectionsDictionaryEntryClass))

typedef struct _SystemCollectionsDictionaryEntry SystemCollectionsDictionaryEntry;
typedef struct _SystemCollectionsDictionaryEntryClass SystemCollectionsDictionaryEntryClass;

#define SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE (system_collections_dictionary_base_get_type ())
#define SYSTEM_COLLECTIONS_DICTIONARY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE, SystemCollectionsDictionaryBase))
#define SYSTEM_COLLECTIONS_DICTIONARY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE, SystemCollectionsDictionaryBaseClass))
#define SYSTEM_COLLECTIONS_IS_DICTIONARY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE))
#define SYSTEM_COLLECTIONS_IS_DICTIONARY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE))
#define SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE, SystemCollectionsDictionaryBaseClass))

typedef struct _SystemCollectionsDictionaryBase SystemCollectionsDictionaryBase;
typedef struct _SystemCollectionsDictionaryBaseClass SystemCollectionsDictionaryBaseClass;
typedef struct _SystemCollectionsDictionaryBasePrivate SystemCollectionsDictionaryBasePrivate;

#define SYSTEM_COLLECTIONS_TYPE_HASHTABLE (system_collections_hashtable_get_type ())
#define SYSTEM_COLLECTIONS_HASHTABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtable))
#define SYSTEM_COLLECTIONS_HASHTABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtableClass))
#define SYSTEM_COLLECTIONS_IS_HASHTABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_HASHTABLE))
#define SYSTEM_COLLECTIONS_IS_HASHTABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_TYPE_HASHTABLE))
#define SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtableClass))

typedef struct _SystemCollectionsHashtable SystemCollectionsHashtable;
typedef struct _SystemCollectionsHashtableClass SystemCollectionsHashtableClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER (system_collections_iequality_comparer_get_type ())
#define SYSTEM_COLLECTIONS_IEQUALITY_COMPARER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER, SystemCollectionsIEqualityComparer))
#define SYSTEM_COLLECTIONS_IS_IEQUALITY_COMPARER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER))
#define SYSTEM_COLLECTIONS_IEQUALITY_COMPARER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER, SystemCollectionsIEqualityComparerIface))

typedef struct _SystemCollectionsIEqualityComparer SystemCollectionsIEqualityComparer;
typedef struct _SystemCollectionsIEqualityComparerIface SystemCollectionsIEqualityComparerIface;

struct _SystemCollectionsIEnumeratorIface {
	GTypeInterface parent_iface;
	gboolean (*MoveNext) (SystemCollectionsIEnumerator* self);
	gboolean (*next) (SystemCollectionsIEnumerator* self);
	GObject* (*get) (SystemCollectionsIEnumerator* self);
	void (*Reset) (SystemCollectionsIEnumerator* self);
	GObject* (*get__currentElement) (SystemCollectionsIEnumerator* self);
	void (*set__currentElement) (SystemCollectionsIEnumerator* self, GObject* value);
	GeeIterator* (*get__iterator) (SystemCollectionsIEnumerator* self);
	void (*set__iterator) (SystemCollectionsIEnumerator* self, GeeIterator* value);
	GObject* (*get_Current) (SystemCollectionsIEnumerator* self);
};

struct _SystemCollectionsIEnumerableIface {
	GTypeInterface parent_iface;
	SystemCollectionsIEnumerator* (*GetEnumerator) (SystemCollectionsIEnumerable* self);
};

struct _SystemCollectionsICollectionIface {
	GTypeInterface parent_iface;
	void (*CopyTo) (SystemCollectionsICollection* self, GArray* array, gint arrayIndex);
	SystemCollectionsIEnumerator* (*iterator) (SystemCollectionsICollection* self);
	gint (*get_Count) (SystemCollectionsICollection* self);
	GObject* (*get_SyncRoot) (SystemCollectionsICollection* self);
	gboolean (*get_IsSynchronized) (SystemCollectionsICollection* self);
};

struct _SystemCollectionsIDictionaryEnumeratorIface {
	GTypeInterface parent_iface;
	GeeMapIterator* (*get__iterator) (SystemCollectionsIDictionaryEnumerator* self);
	void (*set__iterator) (SystemCollectionsIDictionaryEnumerator* self, GeeMapIterator* value);
	GObject* (*get_Key) (SystemCollectionsIDictionaryEnumerator* self);
	GObject* (*get_Value) (SystemCollectionsIDictionaryEnumerator* self);
	SystemCollectionsDictionaryEntry* (*get_Entry) (SystemCollectionsIDictionaryEnumerator* self);
};

struct _SystemCollectionsIDictionaryIface {
	GTypeInterface parent_iface;
	gboolean (*Contains) (SystemCollectionsIDictionary* self, GObject* key);
	void (*Add) (SystemCollectionsIDictionary* self, GObject* key, GObject* value);
	void (*Clear) (SystemCollectionsIDictionary* self);
	SystemCollectionsIDictionaryEnumerator* (*GetEnumerator) (SystemCollectionsIDictionary* self);
	void (*Remove) (SystemCollectionsIDictionary* self, GObject* key);
	SystemCollectionsICollection* (*get_Keys) (SystemCollectionsIDictionary* self);
	SystemCollectionsICollection* (*get_Values) (SystemCollectionsIDictionary* self);
	gboolean (*get_IsReadOnly) (SystemCollectionsIDictionary* self);
	gboolean (*get_IsFixedSize) (SystemCollectionsIDictionary* self);
};

struct _SystemCollectionsDictionaryBase {
	GeeAbstractMap parent_instance;
	SystemCollectionsDictionaryBasePrivate * priv;
};

struct _SystemCollectionsDictionaryBaseClass {
	GeeAbstractMapClass parent_class;
	GObject* (*get) (SystemCollectionsDictionaryBase* self, GObject* key);
	void (*set) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
	GObject* (*OnGet) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* currentValue);
	void (*OnSet) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue);
	void (*OnInsert) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
	void (*OnClear) (SystemCollectionsDictionaryBase* self);
	void (*OnRemove) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
	void (*OnValidate) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
	void (*OnSetComplete) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue);
	void (*OnInsertComplete) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
	void (*OnClearComplete) (SystemCollectionsDictionaryBase* self);
	void (*OnRemoveComplete) (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
};

struct _SystemCollectionsDictionaryBasePrivate {
	SystemCollectionsHashtable* _hashtable;
};

struct _SystemCollectionsIEqualityComparerIface {
	GTypeInterface parent_iface;
	gboolean (*Equals) (SystemCollectionsIEqualityComparer* self, GObject* x, GObject* y);
	gint (*GetHashCode) (SystemCollectionsIEqualityComparer* self, GObject* obj);
};


static gpointer system_collections_dictionary_base_parent_class = NULL;
static SystemCollectionsIDictionaryIface* system_collections_dictionary_base_system_collections_idictionary_parent_iface = NULL;
static SystemCollectionsIEnumerableIface* system_collections_dictionary_base_system_collections_ienumerable_parent_iface = NULL;
static SystemCollectionsICollectionIface* system_collections_dictionary_base_system_collections_icollection_parent_iface = NULL;

GType system_collections_ienumerator_get_type (void) G_GNUC_CONST;
GType system_collections_ienumerable_get_type (void) G_GNUC_CONST;
GType system_collections_icollection_get_type (void) G_GNUC_CONST;
gpointer system_collections_dictionary_entry_ref (gpointer instance);
void system_collections_dictionary_entry_unref (gpointer instance);
GParamSpec* system_collections_param_spec_dictionary_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_collections_value_set_dictionary_entry (GValue* value, gpointer v_object);
void system_collections_value_take_dictionary_entry (GValue* value, gpointer v_object);
gpointer system_collections_value_get_dictionary_entry (const GValue* value);
GType system_collections_dictionary_entry_get_type (void) G_GNUC_CONST;
GType system_collections_idictionary_enumerator_get_type (void) G_GNUC_CONST;
GType system_collections_idictionary_get_type (void) G_GNUC_CONST;
GType system_collections_dictionary_base_get_type (void) G_GNUC_CONST;
GType system_collections_hashtable_get_type (void) G_GNUC_CONST;
#define SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE, SystemCollectionsDictionaryBasePrivate))
enum  {
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_DUMMY_PROPERTY,
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_INNER_HASHTABLE,
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_DICTIONARY,
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_COUNT
};
static void system_collections_dictionary_base_real_CopyTo (SystemCollectionsICollection* base, GArray* array, gint index);
SystemCollectionsHashtable* system_collections_dictionary_base_get_InnerHashtable (SystemCollectionsDictionaryBase* self);
void system_collections_icollection_CopyTo (SystemCollectionsICollection* self, GArray* array, gint arrayIndex);
GObject* system_collections_dictionary_base_get (SystemCollectionsDictionaryBase* self, GObject* key);
static GObject* system_collections_dictionary_base_real_get (SystemCollectionsDictionaryBase* self, GObject* key);
GObject* system_collections_dictionary_base_OnGet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* currentValue);
void system_collections_dictionary_base_set (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static void system_collections_dictionary_base_real_set (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
void system_collections_dictionary_base_OnValidate (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
gboolean system_collections_idictionary_Contains (SystemCollectionsIDictionary* self, GObject* key);
void system_collections_dictionary_base_OnSet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue);
void system_collections_dictionary_base_OnSetComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue);
void system_collections_idictionary_Remove (SystemCollectionsIDictionary* self, GObject* key);
static gboolean system_collections_dictionary_base_real_Contains (SystemCollectionsIDictionary* base, GObject* key);
static void system_collections_dictionary_base_real_Add (SystemCollectionsIDictionary* base, GObject* key, GObject* value);
void system_collections_dictionary_base_OnInsert (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
void system_collections_idictionary_Add (SystemCollectionsIDictionary* self, GObject* key, GObject* value);
void system_collections_dictionary_base_OnInsertComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static void system_collections_dictionary_base_real_Clear (SystemCollectionsIDictionary* base);
void system_collections_dictionary_base_OnClear (SystemCollectionsDictionaryBase* self);
void system_collections_idictionary_Clear (SystemCollectionsIDictionary* self);
void system_collections_dictionary_base_OnClearComplete (SystemCollectionsDictionaryBase* self);
static void system_collections_dictionary_base_real_Remove (SystemCollectionsIDictionary* base, GObject* key);
void system_collections_dictionary_base_OnRemove (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
void system_collections_dictionary_base_OnRemoveComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static SystemCollectionsIDictionaryEnumerator* system_collections_dictionary_base_real_GetEnumerator (SystemCollectionsIDictionary* base);
SystemCollectionsIDictionaryEnumerator* system_collections_idictionary_GetEnumerator (SystemCollectionsIDictionary* self);
static GObject* system_collections_dictionary_base_real_OnGet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* currentValue);
static void system_collections_dictionary_base_real_OnSet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue);
static void system_collections_dictionary_base_real_OnInsert (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static void system_collections_dictionary_base_real_OnClear (SystemCollectionsDictionaryBase* self);
static void system_collections_dictionary_base_real_OnRemove (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static void system_collections_dictionary_base_real_OnValidate (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static void system_collections_dictionary_base_real_OnSetComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue);
static void system_collections_dictionary_base_real_OnInsertComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
static void system_collections_dictionary_base_real_OnClearComplete (SystemCollectionsDictionaryBase* self);
static void system_collections_dictionary_base_real_OnRemoveComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value);
SystemCollectionsDictionaryBase* system_collections_dictionary_base_construct (GType object_type);
GType system_collections_iequality_comparer_get_type (void) G_GNUC_CONST;
SystemCollectionsHashtable* system_collections_hashtable_new (SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsHashtable* system_collections_hashtable_construct (GType object_type, SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsIDictionary* system_collections_dictionary_base_get_Dictionary (SystemCollectionsDictionaryBase* self);
gint system_collections_hashtable_get_Count (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_get_IsReadOnly (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_get_IsFixedSize (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_get_IsSynchronized (SystemCollectionsHashtable* self);
SystemCollectionsICollection* system_collections_hashtable_get_Keys (SystemCollectionsHashtable* self);
GObject* system_collections_hashtable_get_SyncRoot (SystemCollectionsHashtable* self);
SystemCollectionsICollection* system_collections_hashtable_get_Values (SystemCollectionsHashtable* self);
static void system_collections_dictionary_base_finalize (GObject* obj);
gint system_collections_icollection_get_Count (SystemCollectionsICollection* self);
static void _vala_system_collections_dictionary_base_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


static void system_collections_dictionary_base_real_CopyTo (SystemCollectionsICollection* base, GArray* array, gint index) {
	SystemCollectionsDictionaryBase * self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	GArray* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	self = (SystemCollectionsDictionaryBase*) base;
	g_return_if_fail (array != NULL);
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = array;
	_tmp3_ = index;
	system_collections_icollection_CopyTo ((SystemCollectionsICollection*) _tmp1_, _tmp2_, _tmp3_);
}


static GObject* system_collections_dictionary_base_real_get (SystemCollectionsDictionaryBase* self, GObject* key) {
	GObject* result = NULL;
	GObject* currentValue = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	GObject* _tmp4_ = NULL;
	GObject* _tmp5_ = NULL;
	GObject* _tmp6_ = NULL;
	g_return_val_if_fail (key != NULL, NULL);
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = key;
	_tmp3_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp1_, _tmp2_);
	currentValue = (GObject*) _tmp3_;
	_tmp4_ = key;
	_tmp5_ = system_collections_dictionary_base_OnGet (self, _tmp4_, currentValue);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp6_);
	result = currentValue;
	return result;
}


GObject* system_collections_dictionary_base_get (SystemCollectionsDictionaryBase* self, GObject* key) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->get (self, key);
}


static void system_collections_dictionary_base_real_set (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	gboolean keyExists = FALSE;
	GObject* temp = NULL;
	SystemCollectionsHashtable* _tmp2_ = NULL;
	SystemCollectionsHashtable* _tmp3_ = NULL;
	GObject* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	GObject* _tmp6_ = NULL;
	GObject* _tmp11_ = NULL;
	GObject* _tmp12_ = NULL;
	GObject* _tmp13_ = NULL;
	SystemCollectionsHashtable* _tmp14_ = NULL;
	SystemCollectionsHashtable* _tmp15_ = NULL;
	GObject* _tmp16_ = NULL;
	GObject* _tmp17_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
	_tmp0_ = key;
	_tmp1_ = value;
	system_collections_dictionary_base_OnValidate (self, _tmp0_, _tmp1_);
	keyExists = TRUE;
	_tmp2_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = key;
	_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, _tmp4_);
	temp = (GObject*) _tmp5_;
	_tmp6_ = temp;
	if (_tmp6_ == NULL) {
		SystemCollectionsHashtable* _tmp7_ = NULL;
		SystemCollectionsHashtable* _tmp8_ = NULL;
		GObject* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		_tmp7_ = system_collections_dictionary_base_get_InnerHashtable (self);
		_tmp8_ = _tmp7_;
		_tmp9_ = key;
		_tmp10_ = system_collections_idictionary_Contains ((SystemCollectionsIDictionary*) _tmp8_, _tmp9_);
		keyExists = _tmp10_;
	}
	_tmp11_ = key;
	_tmp12_ = temp;
	_tmp13_ = value;
	system_collections_dictionary_base_OnSet (self, _tmp11_, _tmp12_, _tmp13_);
	_tmp14_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp15_ = _tmp14_;
	_tmp16_ = key;
	_tmp17_ = value;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp15_, _tmp16_, _tmp17_);
	{
		GObject* _tmp18_ = NULL;
		GObject* _tmp19_ = NULL;
		GObject* _tmp20_ = NULL;
		_tmp18_ = key;
		_tmp19_ = temp;
		_tmp20_ = value;
		system_collections_dictionary_base_OnSetComplete (self, _tmp18_, _tmp19_, _tmp20_);
	}
	goto __finally47;
	__catch47_g_error:
	{
		gboolean _tmp21_ = FALSE;
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		_tmp21_ = keyExists;
		if (_tmp21_) {
			SystemCollectionsHashtable* _tmp22_ = NULL;
			SystemCollectionsHashtable* _tmp23_ = NULL;
			GObject* _tmp24_ = NULL;
			GObject* _tmp25_ = NULL;
			_tmp22_ = system_collections_dictionary_base_get_InnerHashtable (self);
			_tmp23_ = _tmp22_;
			_tmp24_ = key;
			_tmp25_ = temp;
			gee_abstract_map_set ((GeeAbstractMap*) _tmp23_, _tmp24_, _tmp25_);
		} else {
			SystemCollectionsHashtable* _tmp26_ = NULL;
			SystemCollectionsHashtable* _tmp27_ = NULL;
			GObject* _tmp28_ = NULL;
			_tmp26_ = system_collections_dictionary_base_get_InnerHashtable (self);
			_tmp27_ = _tmp26_;
			_tmp28_ = key;
			system_collections_idictionary_Remove ((SystemCollectionsIDictionary*) _tmp27_, _tmp28_);
		}
	}
	__finally47:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (temp);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (temp);
}


void system_collections_dictionary_base_set (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->set (self, key, value);
}


static gboolean system_collections_dictionary_base_real_Contains (SystemCollectionsIDictionary* base, GObject* key) {
	SystemCollectionsDictionaryBase * self;
	gboolean result = FALSE;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	self = (SystemCollectionsDictionaryBase*) base;
	g_return_val_if_fail (key != NULL, FALSE);
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = key;
	_tmp3_ = system_collections_idictionary_Contains ((SystemCollectionsIDictionary*) _tmp1_, _tmp2_);
	result = _tmp3_;
	return result;
}


static void system_collections_dictionary_base_real_Add (SystemCollectionsIDictionary* base, GObject* key, GObject* value) {
	SystemCollectionsDictionaryBase * self;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GObject* _tmp3_ = NULL;
	SystemCollectionsHashtable* _tmp4_ = NULL;
	SystemCollectionsHashtable* _tmp5_ = NULL;
	GObject* _tmp6_ = NULL;
	GObject* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
	_tmp0_ = key;
	_tmp1_ = value;
	system_collections_dictionary_base_OnValidate (self, _tmp0_, _tmp1_);
	_tmp2_ = key;
	_tmp3_ = value;
	system_collections_dictionary_base_OnInsert (self, _tmp2_, _tmp3_);
	_tmp4_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp5_ = _tmp4_;
	_tmp6_ = key;
	_tmp7_ = value;
	system_collections_idictionary_Add ((SystemCollectionsIDictionary*) _tmp5_, _tmp6_, _tmp7_);
	{
		GObject* _tmp8_ = NULL;
		GObject* _tmp9_ = NULL;
		_tmp8_ = key;
		_tmp9_ = value;
		system_collections_dictionary_base_OnInsertComplete (self, _tmp8_, _tmp9_);
	}
	goto __finally48;
	__catch48_g_error:
	{
		SystemCollectionsHashtable* _tmp10_ = NULL;
		SystemCollectionsHashtable* _tmp11_ = NULL;
		GObject* _tmp12_ = NULL;
		g_clear_error (&_inner_error_);
		_inner_error_ = NULL;
		_tmp10_ = system_collections_dictionary_base_get_InnerHashtable (self);
		_tmp11_ = _tmp10_;
		_tmp12_ = key;
		system_collections_idictionary_Remove ((SystemCollectionsIDictionary*) _tmp11_, _tmp12_);
	}
	__finally48:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void system_collections_dictionary_base_real_Clear (SystemCollectionsIDictionary* base) {
	SystemCollectionsDictionaryBase * self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	system_collections_dictionary_base_OnClear (self);
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	system_collections_idictionary_Clear ((SystemCollectionsIDictionary*) _tmp1_);
	system_collections_dictionary_base_OnClearComplete (self);
}


static void system_collections_dictionary_base_real_Remove (SystemCollectionsIDictionary* base, GObject* key) {
	SystemCollectionsDictionaryBase * self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GError * _inner_error_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	g_return_if_fail (key != NULL);
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = key;
	_tmp3_ = system_collections_idictionary_Contains ((SystemCollectionsIDictionary*) _tmp1_, _tmp2_);
	if (_tmp3_) {
		GObject* temp = NULL;
		SystemCollectionsHashtable* _tmp4_ = NULL;
		SystemCollectionsHashtable* _tmp5_ = NULL;
		GObject* _tmp6_ = NULL;
		gpointer _tmp7_ = NULL;
		GObject* _tmp8_ = NULL;
		GObject* _tmp9_ = NULL;
		GObject* _tmp10_ = NULL;
		GObject* _tmp11_ = NULL;
		SystemCollectionsHashtable* _tmp12_ = NULL;
		SystemCollectionsHashtable* _tmp13_ = NULL;
		GObject* _tmp14_ = NULL;
		_tmp4_ = system_collections_dictionary_base_get_InnerHashtable (self);
		_tmp5_ = _tmp4_;
		_tmp6_ = key;
		_tmp7_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp5_, _tmp6_);
		temp = (GObject*) _tmp7_;
		_tmp8_ = key;
		_tmp9_ = temp;
		system_collections_dictionary_base_OnValidate (self, _tmp8_, _tmp9_);
		_tmp10_ = key;
		_tmp11_ = temp;
		system_collections_dictionary_base_OnRemove (self, _tmp10_, _tmp11_);
		_tmp12_ = system_collections_dictionary_base_get_InnerHashtable (self);
		_tmp13_ = _tmp12_;
		_tmp14_ = key;
		system_collections_idictionary_Remove ((SystemCollectionsIDictionary*) _tmp13_, _tmp14_);
		{
			GObject* _tmp15_ = NULL;
			GObject* _tmp16_ = NULL;
			_tmp15_ = key;
			_tmp16_ = temp;
			system_collections_dictionary_base_OnRemoveComplete (self, _tmp15_, _tmp16_);
		}
		goto __finally49;
		__catch49_g_error:
		{
			SystemCollectionsHashtable* _tmp17_ = NULL;
			SystemCollectionsHashtable* _tmp18_ = NULL;
			GObject* _tmp19_ = NULL;
			GObject* _tmp20_ = NULL;
			g_clear_error (&_inner_error_);
			_inner_error_ = NULL;
			_tmp17_ = system_collections_dictionary_base_get_InnerHashtable (self);
			_tmp18_ = _tmp17_;
			_tmp19_ = key;
			_tmp20_ = temp;
			system_collections_idictionary_Add ((SystemCollectionsIDictionary*) _tmp18_, _tmp19_, _tmp20_);
		}
		__finally49:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (temp);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_g_object_unref0 (temp);
	}
}


static SystemCollectionsIDictionaryEnumerator* system_collections_dictionary_base_real_GetEnumerator (SystemCollectionsIDictionary* base) {
	SystemCollectionsDictionaryBase * self;
	SystemCollectionsIDictionaryEnumerator* result = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	SystemCollectionsIDictionaryEnumerator* _tmp2_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_idictionary_GetEnumerator ((SystemCollectionsIDictionary*) _tmp1_);
	result = _tmp2_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static GObject* system_collections_dictionary_base_real_OnGet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* currentValue) {
	GObject* result = NULL;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	g_return_val_if_fail (key != NULL, NULL);
	g_return_val_if_fail (currentValue != NULL, NULL);
	_tmp0_ = currentValue;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


GObject* system_collections_dictionary_base_OnGet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* currentValue) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnGet (self, key, currentValue);
}


static void system_collections_dictionary_base_real_OnSet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (oldValue != NULL);
	g_return_if_fail (newValue != NULL);
}


void system_collections_dictionary_base_OnSet (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnSet (self, key, oldValue, newValue);
}


static void system_collections_dictionary_base_real_OnInsert (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
}


void system_collections_dictionary_base_OnInsert (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnInsert (self, key, value);
}


static void system_collections_dictionary_base_real_OnClear (SystemCollectionsDictionaryBase* self) {
}


void system_collections_dictionary_base_OnClear (SystemCollectionsDictionaryBase* self) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnClear (self);
}


static void system_collections_dictionary_base_real_OnRemove (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
}


void system_collections_dictionary_base_OnRemove (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnRemove (self, key, value);
}


static void system_collections_dictionary_base_real_OnValidate (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
}


void system_collections_dictionary_base_OnValidate (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnValidate (self, key, value);
}


static void system_collections_dictionary_base_real_OnSetComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (oldValue != NULL);
	g_return_if_fail (newValue != NULL);
}


void system_collections_dictionary_base_OnSetComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* oldValue, GObject* newValue) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnSetComplete (self, key, oldValue, newValue);
}


static void system_collections_dictionary_base_real_OnInsertComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
}


void system_collections_dictionary_base_OnInsertComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnInsertComplete (self, key, value);
}


static void system_collections_dictionary_base_real_OnClearComplete (SystemCollectionsDictionaryBase* self) {
}


void system_collections_dictionary_base_OnClearComplete (SystemCollectionsDictionaryBase* self) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnClearComplete (self);
}


static void system_collections_dictionary_base_real_OnRemoveComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (key != NULL);
	g_return_if_fail (value != NULL);
}


void system_collections_dictionary_base_OnRemoveComplete (SystemCollectionsDictionaryBase* self, GObject* key, GObject* value) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_CLASS (self)->OnRemoveComplete (self, key, value);
}


SystemCollectionsDictionaryBase* system_collections_dictionary_base_construct (GType object_type) {
	SystemCollectionsDictionaryBase * self = NULL;
	self = (SystemCollectionsDictionaryBase*) gee_abstract_map_construct (object_type, G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref);
	return self;
}


SystemCollectionsHashtable* system_collections_dictionary_base_get_InnerHashtable (SystemCollectionsDictionaryBase* self) {
	SystemCollectionsHashtable* result;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_hashtable;
	if (_tmp0_ == NULL) {
		SystemCollectionsHashtable* _tmp1_ = NULL;
		_tmp1_ = system_collections_hashtable_new (NULL);
		_g_object_unref0 (self->priv->_hashtable);
		self->priv->_hashtable = _tmp1_;
	}
	_tmp2_ = self->priv->_hashtable;
	result = _tmp2_;
	return result;
}


SystemCollectionsIDictionary* system_collections_dictionary_base_get_Dictionary (SystemCollectionsDictionaryBase* self) {
	SystemCollectionsIDictionary* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = G_TYPE_CHECK_INSTANCE_CAST (self, SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, SystemCollectionsIDictionary);
	return result;
}


static gint system_collections_dictionary_base_real_get_Count (SystemCollectionsICollection* base) {
	gint result;
	SystemCollectionsDictionaryBase* self;
	gint _tmp0_ = 0;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp1_ = self->priv->_hashtable;
	if (_tmp1_ == NULL) {
		_tmp0_ = 0;
	} else {
		SystemCollectionsHashtable* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		_tmp2_ = self->priv->_hashtable;
		_tmp3_ = system_collections_hashtable_get_Count (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp0_ = _tmp4_;
	}
	result = _tmp0_;
	return result;
}


static gboolean system_collections_dictionary_base_real_get_IsReadOnly (SystemCollectionsIDictionary* base) {
	gboolean result;
	SystemCollectionsDictionaryBase* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_hashtable_get_IsReadOnly (_tmp1_);
	_tmp3_ = _tmp2_;
	result = _tmp3_;
	return result;
}


static gboolean system_collections_dictionary_base_real_get_IsFixedSize (SystemCollectionsIDictionary* base) {
	gboolean result;
	SystemCollectionsDictionaryBase* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_hashtable_get_IsFixedSize (_tmp1_);
	_tmp3_ = _tmp2_;
	result = _tmp3_;
	return result;
}


static gboolean system_collections_dictionary_base_real_get_IsSynchronized (SystemCollectionsICollection* base) {
	gboolean result;
	SystemCollectionsDictionaryBase* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_hashtable_get_IsSynchronized (_tmp1_);
	_tmp3_ = _tmp2_;
	result = _tmp3_;
	return result;
}


static SystemCollectionsICollection* system_collections_dictionary_base_real_get_Keys (SystemCollectionsIDictionary* base) {
	SystemCollectionsICollection* result;
	SystemCollectionsDictionaryBase* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	SystemCollectionsICollection* _tmp2_ = NULL;
	SystemCollectionsICollection* _tmp3_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_hashtable_get_Keys (_tmp1_);
	_tmp3_ = _tmp2_;
	result = _tmp3_;
	return result;
}


static GObject* system_collections_dictionary_base_real_get_SyncRoot (SystemCollectionsICollection* base) {
	GObject* result;
	SystemCollectionsDictionaryBase* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GObject* _tmp3_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_hashtable_get_SyncRoot (_tmp1_);
	_tmp3_ = _tmp2_;
	result = _tmp3_;
	return result;
}


static SystemCollectionsICollection* system_collections_dictionary_base_real_get_Values (SystemCollectionsIDictionary* base) {
	SystemCollectionsICollection* result;
	SystemCollectionsDictionaryBase* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	SystemCollectionsICollection* _tmp2_ = NULL;
	SystemCollectionsICollection* _tmp3_ = NULL;
	self = (SystemCollectionsDictionaryBase*) base;
	_tmp0_ = system_collections_dictionary_base_get_InnerHashtable (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = system_collections_hashtable_get_Values (_tmp1_);
	_tmp3_ = _tmp2_;
	result = _tmp3_;
	return result;
}


static void system_collections_dictionary_base_class_init (SystemCollectionsDictionaryBaseClass * klass) {
	system_collections_dictionary_base_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemCollectionsDictionaryBasePrivate));
	((SystemCollectionsDictionaryBaseClass *) klass)->get = system_collections_dictionary_base_real_get;
	((SystemCollectionsDictionaryBaseClass *) klass)->set = system_collections_dictionary_base_real_set;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnGet = system_collections_dictionary_base_real_OnGet;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnSet = system_collections_dictionary_base_real_OnSet;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnInsert = system_collections_dictionary_base_real_OnInsert;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnClear = system_collections_dictionary_base_real_OnClear;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnRemove = system_collections_dictionary_base_real_OnRemove;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnValidate = system_collections_dictionary_base_real_OnValidate;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnSetComplete = system_collections_dictionary_base_real_OnSetComplete;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnInsertComplete = system_collections_dictionary_base_real_OnInsertComplete;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnClearComplete = system_collections_dictionary_base_real_OnClearComplete;
	((SystemCollectionsDictionaryBaseClass *) klass)->OnRemoveComplete = system_collections_dictionary_base_real_OnRemoveComplete;
	G_OBJECT_CLASS (klass)->get_property = _vala_system_collections_dictionary_base_get_property;
	G_OBJECT_CLASS (klass)->finalize = system_collections_dictionary_base_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_DICTIONARY_BASE_INNER_HASHTABLE, g_param_spec_object ("InnerHashtable", "InnerHashtable", "InnerHashtable", SYSTEM_COLLECTIONS_TYPE_HASHTABLE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_DICTIONARY_BASE_DICTIONARY, g_param_spec_object ("Dictionary", "Dictionary", "Dictionary", SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_DICTIONARY_BASE_COUNT, g_param_spec_int ("Count", "Count", "Count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void system_collections_dictionary_base_system_collections_idictionary_interface_init (SystemCollectionsIDictionaryIface * iface) {
	system_collections_dictionary_base_system_collections_idictionary_parent_iface = g_type_interface_peek_parent (iface);
	iface->Contains = (gboolean (*)(SystemCollectionsIDictionary*, GObject*)) system_collections_dictionary_base_real_Contains;
	iface->Add = (void (*)(SystemCollectionsIDictionary*, GObject*, GObject*)) system_collections_dictionary_base_real_Add;
	iface->Clear = (void (*)(SystemCollectionsIDictionary*)) system_collections_dictionary_base_real_Clear;
	iface->Remove = (void (*)(SystemCollectionsIDictionary*, GObject*)) system_collections_dictionary_base_real_Remove;
	iface->GetEnumerator = (SystemCollectionsIDictionaryEnumerator* (*)(SystemCollectionsIDictionary*)) system_collections_dictionary_base_real_GetEnumerator;
	iface->get_IsReadOnly = system_collections_dictionary_base_real_get_IsReadOnly;
	iface->get_IsFixedSize = system_collections_dictionary_base_real_get_IsFixedSize;
	iface->get_Keys = system_collections_dictionary_base_real_get_Keys;
	iface->get_Values = system_collections_dictionary_base_real_get_Values;
}


static void system_collections_dictionary_base_system_collections_ienumerable_interface_init (SystemCollectionsIEnumerableIface * iface) {
	system_collections_dictionary_base_system_collections_ienumerable_parent_iface = g_type_interface_peek_parent (iface);
}


static void system_collections_dictionary_base_system_collections_icollection_interface_init (SystemCollectionsICollectionIface * iface) {
	system_collections_dictionary_base_system_collections_icollection_parent_iface = g_type_interface_peek_parent (iface);
	iface->CopyTo = (void (*)(SystemCollectionsICollection*, GArray*, gint)) system_collections_dictionary_base_real_CopyTo;
	iface->get_Count = system_collections_dictionary_base_real_get_Count;
	iface->get_IsSynchronized = system_collections_dictionary_base_real_get_IsSynchronized;
	iface->get_SyncRoot = system_collections_dictionary_base_real_get_SyncRoot;
}


static void system_collections_dictionary_base_instance_init (SystemCollectionsDictionaryBase * self) {
	self->priv = SYSTEM_COLLECTIONS_DICTIONARY_BASE_GET_PRIVATE (self);
}


static void system_collections_dictionary_base_finalize (GObject* obj) {
	SystemCollectionsDictionaryBase * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE, SystemCollectionsDictionaryBase);
	_g_object_unref0 (self->priv->_hashtable);
	G_OBJECT_CLASS (system_collections_dictionary_base_parent_class)->finalize (obj);
}


GType system_collections_dictionary_base_get_type (void) {
	static volatile gsize system_collections_dictionary_base_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_dictionary_base_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsDictionaryBaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_collections_dictionary_base_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemCollectionsDictionaryBase), 0, (GInstanceInitFunc) system_collections_dictionary_base_instance_init, NULL };
		static const GInterfaceInfo system_collections_idictionary_info = { (GInterfaceInitFunc) system_collections_dictionary_base_system_collections_idictionary_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_ienumerable_info = { (GInterfaceInitFunc) system_collections_dictionary_base_system_collections_ienumerable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_icollection_info = { (GInterfaceInitFunc) system_collections_dictionary_base_system_collections_icollection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_collections_dictionary_base_type_id;
		system_collections_dictionary_base_type_id = g_type_register_static (GEE_TYPE_ABSTRACT_MAP, "SystemCollectionsDictionaryBase", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_type_add_interface_static (system_collections_dictionary_base_type_id, SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, &system_collections_idictionary_info);
		g_type_add_interface_static (system_collections_dictionary_base_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, &system_collections_ienumerable_info);
		g_type_add_interface_static (system_collections_dictionary_base_type_id, SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, &system_collections_icollection_info);
		g_once_init_leave (&system_collections_dictionary_base_type_id__volatile, system_collections_dictionary_base_type_id);
	}
	return system_collections_dictionary_base_type_id__volatile;
}


static void _vala_system_collections_dictionary_base_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemCollectionsDictionaryBase * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_TYPE_DICTIONARY_BASE, SystemCollectionsDictionaryBase);
	switch (property_id) {
		case SYSTEM_COLLECTIONS_DICTIONARY_BASE_INNER_HASHTABLE:
		g_value_set_object (value, system_collections_dictionary_base_get_InnerHashtable (self));
		break;
		case SYSTEM_COLLECTIONS_DICTIONARY_BASE_DICTIONARY:
		g_value_set_object (value, system_collections_dictionary_base_get_Dictionary (self));
		break;
		case SYSTEM_COLLECTIONS_DICTIONARY_BASE_COUNT:
		g_value_set_int (value, system_collections_icollection_get_Count ((SystemCollectionsICollection*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



