/* Hashtable.c generated by valac 0.26.2, the Vala compiler
 * generated from Hashtable.vala, do not modify */

/* Copyright (c) Microsoft. All rights reserved.*/
/* Licensed under the MIT license. See LICENSE file in the project root for full license information.*/
/*============================================================
**
** Class:  Hashtable
**
** Purpose: Represents a collection of key/value pairs
**          that are organized based on the hash code
**          of the key.
**
===========================================================*/

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <float.h>
#include <math.h>


#define SYSTEM_COLLECTIONS_TYPE_IENUMERABLE (system_collections_ienumerable_get_type ())
#define SYSTEM_COLLECTIONS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, SystemCollectionsIEnumerable))
#define SYSTEM_COLLECTIONS_IS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE))
#define SYSTEM_COLLECTIONS_IENUMERABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, SystemCollectionsIEnumerableIface))

typedef struct _SystemCollectionsIEnumerable SystemCollectionsIEnumerable;
typedef struct _SystemCollectionsIEnumerableIface SystemCollectionsIEnumerableIface;

#define SYSTEM_COLLECTIONS_TYPE_IENUMERATOR (system_collections_ienumerator_get_type ())
#define SYSTEM_COLLECTIONS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, SystemCollectionsIEnumerator))
#define SYSTEM_COLLECTIONS_IS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR))
#define SYSTEM_COLLECTIONS_IENUMERATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, SystemCollectionsIEnumeratorIface))

typedef struct _SystemCollectionsIEnumerator SystemCollectionsIEnumerator;
typedef struct _SystemCollectionsIEnumeratorIface SystemCollectionsIEnumeratorIface;

#define SYSTEM_COLLECTIONS_TYPE_ICOLLECTION (system_collections_icollection_get_type ())
#define SYSTEM_COLLECTIONS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, SystemCollectionsICollection))
#define SYSTEM_COLLECTIONS_IS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION))
#define SYSTEM_COLLECTIONS_ICOLLECTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, SystemCollectionsICollectionIface))

typedef struct _SystemCollectionsICollection SystemCollectionsICollection;
typedef struct _SystemCollectionsICollectionIface SystemCollectionsICollectionIface;

#define SYSTEM_COLLECTIONS_TYPE_IDICTIONARY (system_collections_idictionary_get_type ())
#define SYSTEM_COLLECTIONS_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, SystemCollectionsIDictionary))
#define SYSTEM_COLLECTIONS_IS_IDICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY))
#define SYSTEM_COLLECTIONS_IDICTIONARY_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, SystemCollectionsIDictionaryIface))

typedef struct _SystemCollectionsIDictionary SystemCollectionsIDictionary;
typedef struct _SystemCollectionsIDictionaryIface SystemCollectionsIDictionaryIface;

#define SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR (system_collections_idictionary_enumerator_get_type ())
#define SYSTEM_COLLECTIONS_IDICTIONARY_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR, SystemCollectionsIDictionaryEnumerator))
#define SYSTEM_COLLECTIONS_IS_IDICTIONARY_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR))
#define SYSTEM_COLLECTIONS_IDICTIONARY_ENUMERATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR, SystemCollectionsIDictionaryEnumeratorIface))

typedef struct _SystemCollectionsIDictionaryEnumerator SystemCollectionsIDictionaryEnumerator;
typedef struct _SystemCollectionsIDictionaryEnumeratorIface SystemCollectionsIDictionaryEnumeratorIface;

#define SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY (system_collections_dictionary_entry_get_type ())
#define SYSTEM_COLLECTIONS_DICTIONARY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, SystemCollectionsDictionaryEntry))
#define SYSTEM_COLLECTIONS_DICTIONARY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, SystemCollectionsDictionaryEntryClass))
#define SYSTEM_COLLECTIONS_IS_DICTIONARY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY))
#define SYSTEM_COLLECTIONS_IS_DICTIONARY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY))
#define SYSTEM_COLLECTIONS_DICTIONARY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, SystemCollectionsDictionaryEntryClass))

typedef struct _SystemCollectionsDictionaryEntry SystemCollectionsDictionaryEntry;
typedef struct _SystemCollectionsDictionaryEntryClass SystemCollectionsDictionaryEntryClass;

#define SYSTEM_COLLECTIONS_TYPE_HASHTABLE (system_collections_hashtable_get_type ())
#define SYSTEM_COLLECTIONS_HASHTABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtable))
#define SYSTEM_COLLECTIONS_HASHTABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtableClass))
#define SYSTEM_COLLECTIONS_IS_HASHTABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_HASHTABLE))
#define SYSTEM_COLLECTIONS_IS_HASHTABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_TYPE_HASHTABLE))
#define SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtableClass))

typedef struct _SystemCollectionsHashtable SystemCollectionsHashtable;
typedef struct _SystemCollectionsHashtableClass SystemCollectionsHashtableClass;
typedef struct _SystemCollectionsHashtablePrivate SystemCollectionsHashtablePrivate;
typedef struct _SystemCollectionsKeyValuePairs SystemCollectionsKeyValuePairs;

#define SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER (system_collections_iequality_comparer_get_type ())
#define SYSTEM_COLLECTIONS_IEQUALITY_COMPARER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER, SystemCollectionsIEqualityComparer))
#define SYSTEM_COLLECTIONS_IS_IEQUALITY_COMPARER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER))
#define SYSTEM_COLLECTIONS_IEQUALITY_COMPARER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER, SystemCollectionsIEqualityComparerIface))

typedef struct _SystemCollectionsIEqualityComparer SystemCollectionsIEqualityComparer;
typedef struct _SystemCollectionsIEqualityComparerIface SystemCollectionsIEqualityComparerIface;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _system_collections_key_value_pairs_free0(var) ((var == NULL) ? NULL : (var = (system_collections_key_value_pairs_free (var), NULL)))

#define SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR (system_collections_hashtable_hashtable_enumerator_get_type ())
#define SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumerator))
#define SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumeratorClass))
#define SYSTEM_COLLECTIONS_HASHTABLE_IS_HASHTABLE_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR))
#define SYSTEM_COLLECTIONS_HASHTABLE_IS_HASHTABLE_ENUMERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR))
#define SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumeratorClass))

typedef struct _SystemCollectionsHashtableHashtableEnumerator SystemCollectionsHashtableHashtableEnumerator;
typedef struct _SystemCollectionsHashtableHashtableEnumeratorClass SystemCollectionsHashtableHashtableEnumeratorClass;

#define SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION (system_collections_hashtable_key_collection_get_type ())
#define SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, SystemCollectionsHashtableKeyCollection))
#define SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, SystemCollectionsHashtableKeyCollectionClass))
#define SYSTEM_COLLECTIONS_HASHTABLE_IS_KEY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION))
#define SYSTEM_COLLECTIONS_HASHTABLE_IS_KEY_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION))
#define SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, SystemCollectionsHashtableKeyCollectionClass))

typedef struct _SystemCollectionsHashtableKeyCollection SystemCollectionsHashtableKeyCollection;
typedef struct _SystemCollectionsHashtableKeyCollectionClass SystemCollectionsHashtableKeyCollectionClass;

#define SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION (system_collections_hashtable_value_collection_get_type ())
#define SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, SystemCollectionsHashtableValueCollection))
#define SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, SystemCollectionsHashtableValueCollectionClass))
#define SYSTEM_COLLECTIONS_HASHTABLE_IS_VALUE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION))
#define SYSTEM_COLLECTIONS_HASHTABLE_IS_VALUE_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION))
#define SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, SystemCollectionsHashtableValueCollectionClass))

typedef struct _SystemCollectionsHashtableValueCollection SystemCollectionsHashtableValueCollection;
typedef struct _SystemCollectionsHashtableValueCollectionClass SystemCollectionsHashtableValueCollectionClass;
typedef struct _SystemCollectionsHashtableKeyCollectionPrivate SystemCollectionsHashtableKeyCollectionPrivate;
typedef struct _SystemCollectionsHashtableValueCollectionPrivate SystemCollectionsHashtableValueCollectionPrivate;
typedef struct _SystemCollectionsHashtableHashtableEnumeratorPrivate SystemCollectionsHashtableHashtableEnumeratorPrivate;

struct _SystemCollectionsIEnumeratorIface {
	GTypeInterface parent_iface;
	gboolean (*MoveNext) (SystemCollectionsIEnumerator* self);
	gboolean (*next) (SystemCollectionsIEnumerator* self);
	GObject* (*get) (SystemCollectionsIEnumerator* self);
	void (*Reset) (SystemCollectionsIEnumerator* self);
	GObject* (*get__currentElement) (SystemCollectionsIEnumerator* self);
	void (*set__currentElement) (SystemCollectionsIEnumerator* self, GObject* value);
	GeeIterator* (*get__iterator) (SystemCollectionsIEnumerator* self);
	void (*set__iterator) (SystemCollectionsIEnumerator* self, GeeIterator* value);
	GObject* (*get_Current) (SystemCollectionsIEnumerator* self);
};

struct _SystemCollectionsIEnumerableIface {
	GTypeInterface parent_iface;
	SystemCollectionsIEnumerator* (*GetEnumerator) (SystemCollectionsIEnumerable* self);
};

struct _SystemCollectionsICollectionIface {
	GTypeInterface parent_iface;
	void (*CopyTo) (SystemCollectionsICollection* self, GArray* array, gint arrayIndex);
	SystemCollectionsIEnumerator* (*iterator) (SystemCollectionsICollection* self);
	gint (*get_Count) (SystemCollectionsICollection* self);
	GObject* (*get_SyncRoot) (SystemCollectionsICollection* self);
	gboolean (*get_IsSynchronized) (SystemCollectionsICollection* self);
};

struct _SystemCollectionsIDictionaryEnumeratorIface {
	GTypeInterface parent_iface;
	GeeMapIterator* (*get__iterator) (SystemCollectionsIDictionaryEnumerator* self);
	void (*set__iterator) (SystemCollectionsIDictionaryEnumerator* self, GeeMapIterator* value);
	GObject* (*get_Key) (SystemCollectionsIDictionaryEnumerator* self);
	GObject* (*get_Value) (SystemCollectionsIDictionaryEnumerator* self);
	SystemCollectionsDictionaryEntry* (*get_Entry) (SystemCollectionsIDictionaryEnumerator* self);
};

struct _SystemCollectionsIDictionaryIface {
	GTypeInterface parent_iface;
	gboolean (*Contains) (SystemCollectionsIDictionary* self, GObject* key);
	void (*Add) (SystemCollectionsIDictionary* self, GObject* key, GObject* value);
	void (*Clear) (SystemCollectionsIDictionary* self);
	SystemCollectionsIDictionaryEnumerator* (*GetEnumerator) (SystemCollectionsIDictionary* self);
	void (*Remove) (SystemCollectionsIDictionary* self, GObject* key);
	SystemCollectionsICollection* (*get_Keys) (SystemCollectionsIDictionary* self);
	SystemCollectionsICollection* (*get_Values) (SystemCollectionsIDictionary* self);
	gboolean (*get_IsReadOnly) (SystemCollectionsIDictionary* self);
	gboolean (*get_IsFixedSize) (SystemCollectionsIDictionary* self);
};

struct _SystemCollectionsHashtable {
	GeeHashMap parent_instance;
	SystemCollectionsHashtablePrivate * priv;
	GObject* _syncRoot;
};

struct _SystemCollectionsHashtableClass {
	GeeHashMapClass parent_class;
	GObject* (*Clone) (SystemCollectionsHashtable* self);
	gboolean (*ContainsKey) (SystemCollectionsHashtable* self, GObject* key);
	gboolean (*ContainsValue) (SystemCollectionsHashtable* self, GObject* value);
	SystemCollectionsKeyValuePairs** (*ToKeyValuePairsArray) (SystemCollectionsHashtable* self, int* result_length1);
	gint (*GetHash) (SystemCollectionsHashtable* self, GObject* key);
	gboolean (*get_IsReadOnly) (SystemCollectionsHashtable* self);
	gboolean (*get_IsFixedSize) (SystemCollectionsHashtable* self);
	gboolean (*get_IsSynchronized) (SystemCollectionsHashtable* self);
	SystemCollectionsICollection* (*get_Keys) (SystemCollectionsHashtable* self);
	SystemCollectionsICollection* (*get_Values) (SystemCollectionsHashtable* self);
	GObject* (*get_SyncRoot) (SystemCollectionsHashtable* self);
	gint (*get_Count) (SystemCollectionsHashtable* self);
};

struct _SystemCollectionsIEqualityComparerIface {
	GTypeInterface parent_iface;
	gboolean (*Equals) (SystemCollectionsIEqualityComparer* self, GObject* x, GObject* y);
	gint (*GetHashCode) (SystemCollectionsIEqualityComparer* self, GObject* obj);
};

struct _SystemCollectionsHashtablePrivate {
	SystemCollectionsICollection* _keys;
	SystemCollectionsICollection* _values;
	SystemCollectionsIEqualityComparer* _keycomparer;
};

struct _SystemCollectionsHashtableKeyCollection {
	GObject parent_instance;
	SystemCollectionsHashtableKeyCollectionPrivate * priv;
};

struct _SystemCollectionsHashtableKeyCollectionClass {
	GObjectClass parent_class;
	SystemCollectionsIEnumerator* (*GetEnumerator) (SystemCollectionsHashtableKeyCollection* self);
	gboolean (*get_IsSynchronized) (SystemCollectionsHashtableKeyCollection* self);
	GObject* (*get_SyncRoot) (SystemCollectionsHashtableKeyCollection* self);
	gint (*get_Count) (SystemCollectionsHashtableKeyCollection* self);
};

struct _SystemCollectionsHashtableKeyCollectionPrivate {
	SystemCollectionsHashtable* _hashtable;
};

struct _SystemCollectionsHashtableValueCollection {
	GObject parent_instance;
	SystemCollectionsHashtableValueCollectionPrivate * priv;
};

struct _SystemCollectionsHashtableValueCollectionClass {
	GObjectClass parent_class;
	void (*CopyTo) (SystemCollectionsHashtableValueCollection* self, GArray* array, gint arrayIndex);
	SystemCollectionsIEnumerator* (*GetEnumerator) (SystemCollectionsHashtableValueCollection* self);
	gboolean (*get_IsSynchronized) (SystemCollectionsHashtableValueCollection* self);
	GObject* (*get_SyncRoot) (SystemCollectionsHashtableValueCollection* self);
	gint (*get_Count) (SystemCollectionsHashtableValueCollection* self);
};

struct _SystemCollectionsHashtableValueCollectionPrivate {
	SystemCollectionsHashtable* _hashtable;
};

struct _SystemCollectionsHashtableHashtableEnumerator {
	GObject parent_instance;
	SystemCollectionsHashtableHashtableEnumeratorPrivate * priv;
};

struct _SystemCollectionsHashtableHashtableEnumeratorClass {
	GObjectClass parent_class;
	void (*Reset) (SystemCollectionsHashtableHashtableEnumerator* self);
	GObject* (*get_Key) (SystemCollectionsHashtableHashtableEnumerator* self);
	SystemCollectionsDictionaryEntry* (*get_Entry) (SystemCollectionsHashtableHashtableEnumerator* self);
	GObject* (*get_Current) (SystemCollectionsHashtableHashtableEnumerator* self);
	GObject* (*get_Value) (SystemCollectionsHashtableHashtableEnumerator* self);
};

struct _SystemCollectionsHashtableHashtableEnumeratorPrivate {
	SystemCollectionsHashtable* _hashtable;
	GObject* __currentElement;
	GeeMapIterator* __iterator;
};


static gpointer system_collections_hashtable_parent_class = NULL;
static gpointer system_collections_hashtable_key_collection_parent_class = NULL;
static SystemCollectionsICollectionIface* system_collections_hashtable_key_collection_system_collections_icollection_parent_iface = NULL;
static SystemCollectionsIEnumerableIface* system_collections_hashtable_key_collection_system_collections_ienumerable_parent_iface = NULL;
static gpointer system_collections_hashtable_value_collection_parent_class = NULL;
static SystemCollectionsICollectionIface* system_collections_hashtable_value_collection_system_collections_icollection_parent_iface = NULL;
static SystemCollectionsIEnumerableIface* system_collections_hashtable_value_collection_system_collections_ienumerable_parent_iface = NULL;
static gpointer system_collections_hashtable_hashtable_enumerator_parent_class = NULL;
static SystemCollectionsIDictionaryEnumeratorIface* system_collections_hashtable_hashtable_enumerator_system_collections_idictionary_enumerator_parent_iface = NULL;
static SystemCollectionsIEnumeratorIface* system_collections_hashtable_hashtable_enumerator_system_collections_ienumerator_parent_iface = NULL;
static SystemCollectionsIDictionaryIface* system_collections_hashtable_system_collections_idictionary_parent_iface = NULL;
static SystemCollectionsIEnumerableIface* system_collections_hashtable_system_collections_ienumerable_parent_iface = NULL;
static SystemCollectionsICollectionIface* system_collections_hashtable_system_collections_icollection_parent_iface = NULL;

GType system_collections_ienumerator_get_type (void) G_GNUC_CONST;
GType system_collections_ienumerable_get_type (void) G_GNUC_CONST;
GType system_collections_icollection_get_type (void) G_GNUC_CONST;
gpointer system_collections_dictionary_entry_ref (gpointer instance);
void system_collections_dictionary_entry_unref (gpointer instance);
GParamSpec* system_collections_param_spec_dictionary_entry (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_collections_value_set_dictionary_entry (GValue* value, gpointer v_object);
void system_collections_value_take_dictionary_entry (GValue* value, gpointer v_object);
gpointer system_collections_value_get_dictionary_entry (const GValue* value);
GType system_collections_dictionary_entry_get_type (void) G_GNUC_CONST;
GType system_collections_idictionary_enumerator_get_type (void) G_GNUC_CONST;
GType system_collections_idictionary_get_type (void) G_GNUC_CONST;
GType system_collections_hashtable_get_type (void) G_GNUC_CONST;
void system_collections_key_value_pairs_free (SystemCollectionsKeyValuePairs* self);
GType system_collections_iequality_comparer_get_type (void) G_GNUC_CONST;
#define SYSTEM_COLLECTIONS_HASHTABLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtablePrivate))
enum  {
	SYSTEM_COLLECTIONS_HASHTABLE_DUMMY_PROPERTY,
	SYSTEM_COLLECTIONS_HASHTABLE_EQUALITY_COMPARER,
	SYSTEM_COLLECTIONS_HASHTABLE_IS_SYNCHRONIZED,
	SYSTEM_COLLECTIONS_HASHTABLE_KEYS,
	SYSTEM_COLLECTIONS_HASHTABLE_VALUES,
	SYSTEM_COLLECTIONS_HASHTABLE_SYNC_ROOT,
	SYSTEM_COLLECTIONS_HASHTABLE_COUNT
};
SystemCollectionsHashtable* system_collections_hashtable_new (SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsHashtable* system_collections_hashtable_construct (GType object_type, SystemCollectionsIEqualityComparer* equalityComparer);
gboolean system_collections_iequality_comparer_Equals (SystemCollectionsIEqualityComparer* self, GObject* x, GObject* y);
SystemCollectionsHashtable* system_collections_hashtable_new_WithCapacity (gint capacity, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsHashtable* system_collections_hashtable_construct_WithCapacity (GType object_type, gint capacity, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsHashtable* system_collections_hashtable_new_WithDictionary (SystemCollectionsIDictionary* d, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsHashtable* system_collections_hashtable_construct_WithDictionary (GType object_type, SystemCollectionsIDictionary* d, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer);
SystemCollectionsIDictionaryEnumerator* system_collections_idictionary_GetEnumerator (SystemCollectionsIDictionary* self);
gboolean system_collections_ienumerator_MoveNext (SystemCollectionsIEnumerator* self);
void system_collections_idictionary_Add (SystemCollectionsIDictionary* self, GObject* key, GObject* value);
GObject* system_collections_idictionary_enumerator_get_Key (SystemCollectionsIDictionaryEnumerator* self);
GObject* system_collections_idictionary_enumerator_get_Value (SystemCollectionsIDictionaryEnumerator* self);
GObject* system_collections_hashtable_Clone (SystemCollectionsHashtable* self);
static GObject* system_collections_hashtable_real_Clone (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_ContainsKey (SystemCollectionsHashtable* self, GObject* key);
static gboolean system_collections_hashtable_real_ContainsKey (SystemCollectionsHashtable* self, GObject* key);
gboolean system_collections_hashtable_ContainsValue (SystemCollectionsHashtable* self, GObject* value);
static gboolean system_collections_hashtable_real_ContainsValue (SystemCollectionsHashtable* self, GObject* value);
void system_collections_hashtable_CopyKeys (SystemCollectionsHashtable* self, GArray* array, gint arrayIndex);
SystemCollectionsKeyValuePairs** system_collections_hashtable_ToKeyValuePairsArray (SystemCollectionsHashtable* self, int* result_length1);
static SystemCollectionsKeyValuePairs** system_collections_hashtable_real_ToKeyValuePairsArray (SystemCollectionsHashtable* self, int* result_length1);
SystemCollectionsKeyValuePairs* system_collections_key_value_pairs_new (GObject* key, GObject* value);
SystemCollectionsKeyValuePairs* system_collections_key_value_pairs_new (GObject* key, GObject* value);
static void system_collections_hashtable_CopyValues (SystemCollectionsHashtable* self, GArray* array, gint arrayIndex);
static void system_collections_hashtable_rehash (SystemCollectionsHashtable* self, gint newsize, gboolean forceNewHashCode);
static SystemCollectionsIDictionaryEnumerator* system_collections_hashtable_real_GetEnumerator (SystemCollectionsIDictionary* base);
SystemCollectionsHashtableHashtableEnumerator* system_collections_hashtable_hashtable_enumerator_new (SystemCollectionsHashtable* hashtable);
SystemCollectionsHashtableHashtableEnumerator* system_collections_hashtable_hashtable_enumerator_construct (GType object_type, SystemCollectionsHashtable* hashtable);
GType system_collections_hashtable_hashtable_enumerator_get_type (void) G_GNUC_CONST;
gint system_collections_hashtable_GetHash (SystemCollectionsHashtable* self, GObject* key);
static gint system_collections_hashtable_real_GetHash (SystemCollectionsHashtable* self, GObject* key);
gint system_collections_iequality_comparer_GetHashCode (SystemCollectionsIEqualityComparer* self, GObject* obj);
static void system_collections_hashtable_Insert (SystemCollectionsHashtable* self, GObject* key, GObject* nvalue, gboolean add);
SystemCollectionsIEqualityComparer* system_collections_hashtable_get_EqualityComparer (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_get_IsReadOnly (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_get_IsFixedSize (SystemCollectionsHashtable* self);
gboolean system_collections_hashtable_get_IsSynchronized (SystemCollectionsHashtable* self);
SystemCollectionsICollection* system_collections_hashtable_get_Keys (SystemCollectionsHashtable* self);
SystemCollectionsHashtableKeyCollection* system_collections_hashtable_key_collection_new (SystemCollectionsHashtable* hashtable);
SystemCollectionsHashtableKeyCollection* system_collections_hashtable_key_collection_construct (GType object_type, SystemCollectionsHashtable* hashtable);
GType system_collections_hashtable_key_collection_get_type (void) G_GNUC_CONST;
SystemCollectionsICollection* system_collections_hashtable_get_Values (SystemCollectionsHashtable* self);
SystemCollectionsHashtableValueCollection* system_collections_hashtable_value_collection_new (SystemCollectionsHashtable* hashtable);
SystemCollectionsHashtableValueCollection* system_collections_hashtable_value_collection_construct (GType object_type, SystemCollectionsHashtable* hashtable);
GType system_collections_hashtable_value_collection_get_type (void) G_GNUC_CONST;
GObject* system_collections_hashtable_get_SyncRoot (SystemCollectionsHashtable* self);
gint system_collections_hashtable_get_Count (SystemCollectionsHashtable* self);
#define SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, SystemCollectionsHashtableKeyCollectionPrivate))
enum  {
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_DUMMY_PROPERTY,
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_IS_SYNCHRONIZED,
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_SYNC_ROOT,
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_COUNT
};
static void system_collections_hashtable_key_collection_real_CopyTo (SystemCollectionsICollection* base, GArray* array, gint arrayIndex);
SystemCollectionsIEnumerator* system_collections_hashtable_key_collection_GetEnumerator (SystemCollectionsHashtableKeyCollection* self);
static SystemCollectionsIEnumerator* system_collections_hashtable_key_collection_real_GetEnumerator (SystemCollectionsHashtableKeyCollection* self);
gboolean system_collections_hashtable_key_collection_get_IsSynchronized (SystemCollectionsHashtableKeyCollection* self);
GObject* system_collections_hashtable_key_collection_get_SyncRoot (SystemCollectionsHashtableKeyCollection* self);
gint system_collections_hashtable_key_collection_get_Count (SystemCollectionsHashtableKeyCollection* self);
static void system_collections_hashtable_key_collection_finalize (GObject* obj);
static void _vala_system_collections_hashtable_key_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
#define SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, SystemCollectionsHashtableValueCollectionPrivate))
enum  {
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_DUMMY_PROPERTY,
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_IS_SYNCHRONIZED,
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_SYNC_ROOT,
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_COUNT
};
void system_collections_hashtable_value_collection_CopyTo (SystemCollectionsHashtableValueCollection* self, GArray* array, gint arrayIndex);
static void system_collections_hashtable_value_collection_real_CopyTo (SystemCollectionsHashtableValueCollection* self, GArray* array, gint arrayIndex);
SystemCollectionsIEnumerator* system_collections_hashtable_value_collection_GetEnumerator (SystemCollectionsHashtableValueCollection* self);
static SystemCollectionsIEnumerator* system_collections_hashtable_value_collection_real_GetEnumerator (SystemCollectionsHashtableValueCollection* self);
gboolean system_collections_hashtable_value_collection_get_IsSynchronized (SystemCollectionsHashtableValueCollection* self);
GObject* system_collections_hashtable_value_collection_get_SyncRoot (SystemCollectionsHashtableValueCollection* self);
gint system_collections_hashtable_value_collection_get_Count (SystemCollectionsHashtableValueCollection* self);
static void system_collections_hashtable_value_collection_finalize (GObject* obj);
static void _vala_system_collections_hashtable_value_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
#define SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumeratorPrivate))
enum  {
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_DUMMY_PROPERTY,
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_KEY,
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_ENTRY,
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CURRENT,
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_VALUE
};
void system_collections_idictionary_enumerator_set__iterator (SystemCollectionsIDictionaryEnumerator* self, GeeMapIterator* value);
void system_collections_hashtable_hashtable_enumerator_Reset (SystemCollectionsHashtableHashtableEnumerator* self);
static void system_collections_hashtable_hashtable_enumerator_real_Reset (SystemCollectionsHashtableHashtableEnumerator* self);
GObject* system_collections_hashtable_hashtable_enumerator_get_Key (SystemCollectionsHashtableHashtableEnumerator* self);
GeeMapIterator* system_collections_idictionary_enumerator_get__iterator (SystemCollectionsIDictionaryEnumerator* self);
SystemCollectionsDictionaryEntry* system_collections_hashtable_hashtable_enumerator_get_Entry (SystemCollectionsHashtableHashtableEnumerator* self);
SystemCollectionsDictionaryEntry* system_collections_dictionary_entry_new (GObject* key, GObject* value);
SystemCollectionsDictionaryEntry* system_collections_dictionary_entry_construct (GType object_type, GObject* key, GObject* value);
GObject* system_collections_hashtable_hashtable_enumerator_get_Current (SystemCollectionsHashtableHashtableEnumerator* self);
GObject* system_collections_ienumerator_get__currentElement (SystemCollectionsIEnumerator* self);
GObject* system_collections_hashtable_hashtable_enumerator_get_Value (SystemCollectionsHashtableHashtableEnumerator* self);
static void system_collections_hashtable_hashtable_enumerator_finalize (GObject* obj);
static void _vala_system_collections_hashtable_hashtable_enumerator_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_system_collections_hashtable_hashtable_enumerator_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void system_collections_hashtable_finalize (GObject* obj);
static void _vala_system_collections_hashtable_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SystemCollectionsHashtable* system_collections_hashtable_construct (GType object_type, SystemCollectionsIEqualityComparer* equalityComparer) {
	SystemCollectionsHashtable * self = NULL;
	SystemCollectionsIEqualityComparer* _tmp0_ = NULL;
	SystemCollectionsIEqualityComparer* _tmp1_ = NULL;
	SystemCollectionsIEqualityComparer* _tmp2_ = NULL;
	_tmp0_ = equalityComparer;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_keycomparer);
	self->priv->_keycomparer = _tmp1_;
	_tmp2_ = equalityComparer;
	self = (SystemCollectionsHashtable*) gee_hash_map_construct (object_type, G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, (GeeEqualDataFunc) system_collections_iequality_comparer_Equals, g_object_ref (_tmp2_), NULL, NULL, NULL, NULL);
	return self;
}


SystemCollectionsHashtable* system_collections_hashtable_new (SystemCollectionsIEqualityComparer* equalityComparer) {
	return system_collections_hashtable_construct (SYSTEM_COLLECTIONS_TYPE_HASHTABLE, equalityComparer);
}


SystemCollectionsHashtable* system_collections_hashtable_construct_WithCapacity (GType object_type, gint capacity, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer) {
	SystemCollectionsHashtable * self = NULL;
	SystemCollectionsIEqualityComparer* _tmp0_ = NULL;
	_tmp0_ = equalityComparer;
	self = (SystemCollectionsHashtable*) system_collections_hashtable_construct (object_type, _tmp0_);
	return self;
}


SystemCollectionsHashtable* system_collections_hashtable_new_WithCapacity (gint capacity, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer) {
	return system_collections_hashtable_construct_WithCapacity (SYSTEM_COLLECTIONS_TYPE_HASHTABLE, capacity, loadFactor, equalityComparer);
}


SystemCollectionsHashtable* system_collections_hashtable_construct_WithDictionary (GType object_type, SystemCollectionsIDictionary* d, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer) {
	SystemCollectionsHashtable * self = NULL;
	SystemCollectionsIEqualityComparer* _tmp0_ = NULL;
	SystemCollectionsIDictionaryEnumerator* e = NULL;
	SystemCollectionsIDictionary* _tmp1_ = NULL;
	SystemCollectionsIDictionaryEnumerator* _tmp2_ = NULL;
	g_return_val_if_fail (d != NULL, NULL);
	_tmp0_ = equalityComparer;
	self = (SystemCollectionsHashtable*) system_collections_hashtable_construct (object_type, _tmp0_);
	_tmp1_ = d;
	_tmp2_ = system_collections_idictionary_GetEnumerator (_tmp1_);
	e = _tmp2_;
	while (TRUE) {
		SystemCollectionsIDictionaryEnumerator* _tmp3_ = NULL;
		gboolean _tmp4_ = FALSE;
		SystemCollectionsIDictionaryEnumerator* _tmp5_ = NULL;
		GObject* _tmp6_ = NULL;
		GObject* _tmp7_ = NULL;
		GObject* _tmp8_ = NULL;
		SystemCollectionsIDictionaryEnumerator* _tmp9_ = NULL;
		GObject* _tmp10_ = NULL;
		GObject* _tmp11_ = NULL;
		GObject* _tmp12_ = NULL;
		_tmp3_ = e;
		_tmp4_ = system_collections_ienumerator_MoveNext ((SystemCollectionsIEnumerator*) _tmp3_);
		if (!_tmp4_) {
			break;
		}
		_tmp5_ = e;
		_tmp6_ = system_collections_idictionary_enumerator_get_Key (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = _tmp7_;
		_tmp9_ = e;
		_tmp10_ = system_collections_idictionary_enumerator_get_Value (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp12_ = _tmp11_;
		system_collections_idictionary_Add ((SystemCollectionsIDictionary*) self, _tmp8_, _tmp12_);
		_g_object_unref0 (_tmp12_);
		_g_object_unref0 (_tmp8_);
	}
	_g_object_unref0 (e);
	return self;
}


SystemCollectionsHashtable* system_collections_hashtable_new_WithDictionary (SystemCollectionsIDictionary* d, gfloat loadFactor, SystemCollectionsIEqualityComparer* equalityComparer) {
	return system_collections_hashtable_construct_WithDictionary (SYSTEM_COLLECTIONS_TYPE_HASHTABLE, d, loadFactor, equalityComparer);
}


static GObject* system_collections_hashtable_real_Clone (SystemCollectionsHashtable* self) {
	GObject* result = NULL;
	GObject* _tmp0_ = NULL;
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (self, G_TYPE_OBJECT) ? ((GObject*) self) : NULL);
	result = _tmp0_;
	return result;
}


GObject* system_collections_hashtable_Clone (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->Clone (self);
}


static gboolean system_collections_hashtable_real_ContainsKey (SystemCollectionsHashtable* self, GObject* key) {
	gboolean result = FALSE;
	GObject* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (key != NULL, FALSE);
	_tmp0_ = key;
	_tmp1_ = gee_abstract_map_has_key ((GeeAbstractMap*) self, _tmp0_);
	result = _tmp1_;
	return result;
}


gboolean system_collections_hashtable_ContainsKey (SystemCollectionsHashtable* self, GObject* key) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->ContainsKey (self, key);
}


static gboolean system_collections_hashtable_real_ContainsValue (SystemCollectionsHashtable* self, GObject* value) {
	gboolean result = FALSE;
	GeeCollection* _tmp0_ = NULL;
	GeeCollection* _tmp1_ = NULL;
	GeeCollection* _tmp2_ = NULL;
	GObject* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	g_return_val_if_fail (value != NULL, FALSE);
	_tmp0_ = gee_abstract_map_get_values ((GeeMap*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_;
	_tmp3_ = value;
	_tmp4_ = gee_collection_contains (_tmp2_, _tmp3_);
	_tmp5_ = _tmp4_;
	_g_object_unref0 (_tmp2_);
	result = _tmp5_;
	return result;
}


gboolean system_collections_hashtable_ContainsValue (SystemCollectionsHashtable* self, GObject* value) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->ContainsValue (self, value);
}


void system_collections_hashtable_CopyKeys (SystemCollectionsHashtable* self, GArray* array, gint arrayIndex) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (array != NULL);
	{
		GeeIterator* _key_it = NULL;
		GeeSet* _tmp0_ = NULL;
		GeeSet* _tmp1_ = NULL;
		GeeSet* _tmp2_ = NULL;
		GeeIterator* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		_tmp0_ = gee_abstract_map_get_keys ((GeeMap*) self);
		_tmp1_ = _tmp0_;
		_tmp2_ = _tmp1_;
		_tmp3_ = gee_iterable_iterator ((GeeIterable*) _tmp2_);
		_tmp4_ = _tmp3_;
		_g_object_unref0 (_tmp2_);
		_key_it = _tmp4_;
		while (TRUE) {
			GeeIterator* _tmp5_ = NULL;
			gboolean _tmp6_ = FALSE;
			GObject* key = NULL;
			GeeIterator* _tmp7_ = NULL;
			gpointer _tmp8_ = NULL;
			GArray* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			GObject* _tmp11_ = NULL;
			GObject* _tmp12_ = NULL;
			_tmp5_ = _key_it;
			_tmp6_ = gee_iterator_next (_tmp5_);
			if (!_tmp6_) {
				break;
			}
			_tmp7_ = _key_it;
			_tmp8_ = gee_iterator_get (_tmp7_);
			key = (GObject*) _tmp8_;
			_tmp9_ = array;
			_tmp10_ = arrayIndex;
			arrayIndex = _tmp10_ + 1;
			_tmp11_ = key;
			_tmp12_ = _g_object_ref0 (_tmp11_);
			g_array_insert_val (_tmp9_, (guint) _tmp10_, _tmp12_);
			_g_object_unref0 (key);
		}
		_g_object_unref0 (_key_it);
	}
}


static SystemCollectionsKeyValuePairs** system_collections_hashtable_real_ToKeyValuePairsArray (SystemCollectionsHashtable* self, int* result_length1) {
	SystemCollectionsKeyValuePairs** result = NULL;
	SystemCollectionsKeyValuePairs** array = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	SystemCollectionsKeyValuePairs** _tmp2_ = NULL;
	gint array_length1 = 0;
	gint _array_size_ = 0;
	gint index = 0;
	SystemCollectionsKeyValuePairs** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	_tmp0_ = gee_abstract_map_get_size ((GeeMap*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_new0 (SystemCollectionsKeyValuePairs*, _tmp1_ + 1);
	array = _tmp2_;
	array_length1 = _tmp1_;
	_array_size_ = array_length1;
	index = 0;
	{
		GeeIterator* _ent_it = NULL;
		GeeSet* _tmp3_ = NULL;
		GeeSet* _tmp4_ = NULL;
		GeeSet* _tmp5_ = NULL;
		GeeIterator* _tmp6_ = NULL;
		GeeIterator* _tmp7_ = NULL;
		_tmp3_ = gee_abstract_map_get_entries ((GeeMap*) self);
		_tmp4_ = _tmp3_;
		_tmp5_ = _tmp4_;
		_tmp6_ = gee_iterable_iterator ((GeeIterable*) _tmp5_);
		_tmp7_ = _tmp6_;
		_g_object_unref0 (_tmp5_);
		_ent_it = _tmp7_;
		while (TRUE) {
			GeeIterator* _tmp8_ = NULL;
			gboolean _tmp9_ = FALSE;
			GeeMapEntry* ent = NULL;
			GeeIterator* _tmp10_ = NULL;
			gpointer _tmp11_ = NULL;
			SystemCollectionsKeyValuePairs** _tmp12_ = NULL;
			gint _tmp12__length1 = 0;
			gint _tmp13_ = 0;
			GeeMapEntry* _tmp14_ = NULL;
			gconstpointer _tmp15_ = NULL;
			GObject* _tmp16_ = NULL;
			GeeMapEntry* _tmp17_ = NULL;
			gconstpointer _tmp18_ = NULL;
			GObject* _tmp19_ = NULL;
			SystemCollectionsKeyValuePairs* _tmp20_ = NULL;
			SystemCollectionsKeyValuePairs* _tmp21_ = NULL;
			_tmp8_ = _ent_it;
			_tmp9_ = gee_iterator_next (_tmp8_);
			if (!_tmp9_) {
				break;
			}
			_tmp10_ = _ent_it;
			_tmp11_ = gee_iterator_get (_tmp10_);
			ent = (GeeMapEntry*) _tmp11_;
			_tmp12_ = array;
			_tmp12__length1 = array_length1;
			_tmp13_ = index;
			index = _tmp13_ + 1;
			_tmp14_ = ent;
			_tmp15_ = gee_map_entry_get_key (_tmp14_);
			_tmp16_ = _tmp15_;
			_tmp17_ = ent;
			_tmp18_ = gee_map_entry_get_value (_tmp17_);
			_tmp19_ = _tmp18_;
			_tmp20_ = system_collections_key_value_pairs_new ((GObject*) _tmp16_, (GObject*) _tmp19_);
			_system_collections_key_value_pairs_free0 (_tmp12_[_tmp13_]);
			_tmp12_[_tmp13_] = _tmp20_;
			_tmp21_ = _tmp12_[_tmp13_];
			_g_object_unref0 (ent);
		}
		_g_object_unref0 (_ent_it);
	}
	_tmp22_ = array;
	_tmp22__length1 = array_length1;
	if (result_length1) {
		*result_length1 = _tmp22__length1;
	}
	result = _tmp22_;
	return result;
}


SystemCollectionsKeyValuePairs** system_collections_hashtable_ToKeyValuePairsArray (SystemCollectionsHashtable* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->ToKeyValuePairsArray (self, result_length1);
}


static void system_collections_hashtable_CopyValues (SystemCollectionsHashtable* self, GArray* array, gint arrayIndex) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (array != NULL);
	{
		GeeIterator* _value_it = NULL;
		GeeCollection* _tmp0_ = NULL;
		GeeCollection* _tmp1_ = NULL;
		GeeCollection* _tmp2_ = NULL;
		GeeIterator* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		_tmp0_ = gee_abstract_map_get_values ((GeeMap*) self);
		_tmp1_ = _tmp0_;
		_tmp2_ = _tmp1_;
		_tmp3_ = gee_iterable_iterator ((GeeIterable*) _tmp2_);
		_tmp4_ = _tmp3_;
		_g_object_unref0 (_tmp2_);
		_value_it = _tmp4_;
		while (TRUE) {
			GeeIterator* _tmp5_ = NULL;
			gboolean _tmp6_ = FALSE;
			GObject* value = NULL;
			GeeIterator* _tmp7_ = NULL;
			gpointer _tmp8_ = NULL;
			GArray* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			GObject* _tmp11_ = NULL;
			GObject* _tmp12_ = NULL;
			_tmp5_ = _value_it;
			_tmp6_ = gee_iterator_next (_tmp5_);
			if (!_tmp6_) {
				break;
			}
			_tmp7_ = _value_it;
			_tmp8_ = gee_iterator_get (_tmp7_);
			value = (GObject*) _tmp8_;
			_tmp9_ = array;
			_tmp10_ = arrayIndex;
			arrayIndex = _tmp10_ + 1;
			_tmp11_ = value;
			_tmp12_ = _g_object_ref0 (_tmp11_);
			g_array_insert_val (_tmp9_, (guint) _tmp10_, _tmp12_);
			_g_object_unref0 (value);
		}
		_g_object_unref0 (_value_it);
	}
}


static void system_collections_hashtable_rehash (SystemCollectionsHashtable* self, gint newsize, gboolean forceNewHashCode) {
	g_return_if_fail (self != NULL);
}


static SystemCollectionsIDictionaryEnumerator* system_collections_hashtable_real_GetEnumerator (SystemCollectionsIDictionary* base) {
	SystemCollectionsHashtable * self;
	SystemCollectionsIDictionaryEnumerator* result = NULL;
	SystemCollectionsHashtableHashtableEnumerator* _tmp0_ = NULL;
	self = (SystemCollectionsHashtable*) base;
	_tmp0_ = system_collections_hashtable_hashtable_enumerator_new (self);
	result = (SystemCollectionsIDictionaryEnumerator*) _tmp0_;
	return result;
}


static gint system_collections_hashtable_real_GetHash (SystemCollectionsHashtable* self, GObject* key) {
	gint result = 0;
	SystemCollectionsIEqualityComparer* _tmp0_ = NULL;
	g_return_val_if_fail (key != NULL, 0);
	_tmp0_ = self->priv->_keycomparer;
	if (_tmp0_ != NULL) {
		SystemCollectionsIEqualityComparer* _tmp1_ = NULL;
		GObject* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		_tmp1_ = self->priv->_keycomparer;
		_tmp2_ = key;
		_tmp3_ = system_collections_iequality_comparer_GetHashCode (_tmp1_, _tmp2_);
		result = _tmp3_;
		return result;
	}
	result = -1;
	return result;
}


gint system_collections_hashtable_GetHash (SystemCollectionsHashtable* self, GObject* key) {
	g_return_val_if_fail (self != NULL, 0);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->GetHash (self, key);
}


static void system_collections_hashtable_Insert (SystemCollectionsHashtable* self, GObject* key, GObject* nvalue, gboolean add) {
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (key != NULL);
	g_return_if_fail (nvalue != NULL);
	_tmp0_ = key;
	_tmp1_ = nvalue;
	gee_abstract_map_set ((GeeAbstractMap*) self, _tmp0_, _tmp1_);
}


SystemCollectionsIEqualityComparer* system_collections_hashtable_get_EqualityComparer (SystemCollectionsHashtable* self) {
	SystemCollectionsIEqualityComparer* result;
	SystemCollectionsIEqualityComparer* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_keycomparer;
	result = _tmp0_;
	return result;
}


gboolean system_collections_hashtable_get_IsReadOnly (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_IsReadOnly (self);
}


static gboolean system_collections_hashtable_real_get_IsReadOnly (SystemCollectionsHashtable* base) {
	gboolean result;
	SystemCollectionsHashtable* self;
	self = base;
	result = FALSE;
	return result;
}


gboolean system_collections_hashtable_get_IsFixedSize (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_IsFixedSize (self);
}


static gboolean system_collections_hashtable_real_get_IsFixedSize (SystemCollectionsHashtable* base) {
	gboolean result;
	SystemCollectionsHashtable* self;
	self = base;
	result = FALSE;
	return result;
}


gboolean system_collections_hashtable_get_IsSynchronized (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_IsSynchronized (self);
}


static gboolean system_collections_hashtable_real_get_IsSynchronized (SystemCollectionsHashtable* base) {
	gboolean result;
	SystemCollectionsHashtable* self;
	self = base;
	result = FALSE;
	return result;
}


SystemCollectionsICollection* system_collections_hashtable_get_Keys (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_Keys (self);
}


static SystemCollectionsICollection* system_collections_hashtable_real_get_Keys (SystemCollectionsHashtable* base) {
	SystemCollectionsICollection* result;
	SystemCollectionsHashtable* self;
	SystemCollectionsICollection* _tmp0_ = NULL;
	SystemCollectionsICollection* _tmp2_ = NULL;
	SystemCollectionsICollection* _tmp3_ = NULL;
	self = base;
	_tmp0_ = self->priv->_keys;
	if (_tmp0_ == NULL) {
		SystemCollectionsHashtableKeyCollection* _tmp1_ = NULL;
		_tmp1_ = system_collections_hashtable_key_collection_new (self);
		_g_object_unref0 (self->priv->_keys);
		self->priv->_keys = (SystemCollectionsICollection*) _tmp1_;
	}
	_tmp2_ = self->priv->_keys;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


SystemCollectionsICollection* system_collections_hashtable_get_Values (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_Values (self);
}


static SystemCollectionsICollection* system_collections_hashtable_real_get_Values (SystemCollectionsHashtable* base) {
	SystemCollectionsICollection* result;
	SystemCollectionsHashtable* self;
	SystemCollectionsICollection* _tmp0_ = NULL;
	SystemCollectionsICollection* _tmp2_ = NULL;
	SystemCollectionsICollection* _tmp3_ = NULL;
	self = base;
	_tmp0_ = self->priv->_values;
	if (_tmp0_ == NULL) {
		SystemCollectionsHashtableValueCollection* _tmp1_ = NULL;
		_tmp1_ = system_collections_hashtable_value_collection_new (self);
		_g_object_unref0 (self->priv->_values);
		self->priv->_values = (SystemCollectionsICollection*) _tmp1_;
	}
	_tmp2_ = self->priv->_values;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GObject* system_collections_hashtable_get_SyncRoot (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_SyncRoot (self);
}


static GObject* system_collections_hashtable_real_get_SyncRoot (SystemCollectionsHashtable* base) {
	GObject* result;
	SystemCollectionsHashtable* self;
	GObject* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->_syncRoot;
	result = _tmp0_;
	return result;
}


gint system_collections_hashtable_get_Count (SystemCollectionsHashtable* self) {
	g_return_val_if_fail (self != NULL, 0);
	return SYSTEM_COLLECTIONS_HASHTABLE_GET_CLASS (self)->get_Count (self);
}


static gint system_collections_hashtable_real_get_Count (SystemCollectionsHashtable* base) {
	gint result;
	SystemCollectionsHashtable* self;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	self = base;
	_tmp0_ = gee_abstract_map_get_size ((GeeMap*) self);
	_tmp1_ = _tmp0_;
	result = _tmp1_;
	return result;
}


SystemCollectionsHashtableKeyCollection* system_collections_hashtable_key_collection_construct (GType object_type, SystemCollectionsHashtable* hashtable) {
	SystemCollectionsHashtableKeyCollection * self = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	g_return_val_if_fail (hashtable != NULL, NULL);
	self = (SystemCollectionsHashtableKeyCollection*) g_object_new (object_type, NULL);
	_tmp0_ = hashtable;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_hashtable);
	self->priv->_hashtable = _tmp1_;
	return self;
}


SystemCollectionsHashtableKeyCollection* system_collections_hashtable_key_collection_new (SystemCollectionsHashtable* hashtable) {
	return system_collections_hashtable_key_collection_construct (SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, hashtable);
}


static void system_collections_hashtable_key_collection_real_CopyTo (SystemCollectionsICollection* base, GArray* array, gint arrayIndex) {
	SystemCollectionsHashtableKeyCollection * self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	GArray* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (SystemCollectionsHashtableKeyCollection*) base;
	g_return_if_fail (array != NULL);
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = array;
	_tmp2_ = arrayIndex;
	system_collections_hashtable_CopyKeys (_tmp0_, _tmp1_, _tmp2_);
}


static SystemCollectionsIEnumerator* system_collections_hashtable_key_collection_real_GetEnumerator (SystemCollectionsHashtableKeyCollection* self) {
	SystemCollectionsIEnumerator* result = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtableHashtableEnumerator* _tmp1_ = NULL;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = system_collections_hashtable_hashtable_enumerator_new (_tmp0_);
	result = (SystemCollectionsIEnumerator*) _tmp1_;
	return result;
}


SystemCollectionsIEnumerator* system_collections_hashtable_key_collection_GetEnumerator (SystemCollectionsHashtableKeyCollection* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_CLASS (self)->GetEnumerator (self);
}


gboolean system_collections_hashtable_key_collection_get_IsSynchronized (SystemCollectionsHashtableKeyCollection* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_CLASS (self)->get_IsSynchronized (self);
}


static gboolean system_collections_hashtable_key_collection_real_get_IsSynchronized (SystemCollectionsHashtableKeyCollection* base) {
	gboolean result;
	SystemCollectionsHashtableKeyCollection* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	self = base;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = system_collections_hashtable_get_IsSynchronized (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


GObject* system_collections_hashtable_key_collection_get_SyncRoot (SystemCollectionsHashtableKeyCollection* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_CLASS (self)->get_SyncRoot (self);
}


static GObject* system_collections_hashtable_key_collection_real_get_SyncRoot (SystemCollectionsHashtableKeyCollection* base) {
	GObject* result;
	SystemCollectionsHashtableKeyCollection* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	self = base;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = system_collections_hashtable_get_SyncRoot (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


gint system_collections_hashtable_key_collection_get_Count (SystemCollectionsHashtableKeyCollection* self) {
	g_return_val_if_fail (self != NULL, 0);
	return SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_CLASS (self)->get_Count (self);
}


static gint system_collections_hashtable_key_collection_real_get_Count (SystemCollectionsHashtableKeyCollection* base) {
	gint result;
	SystemCollectionsHashtableKeyCollection* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	self = base;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = gee_abstract_map_get_size ((GeeMap*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


static void system_collections_hashtable_key_collection_class_init (SystemCollectionsHashtableKeyCollectionClass * klass) {
	system_collections_hashtable_key_collection_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemCollectionsHashtableKeyCollectionPrivate));
	((SystemCollectionsHashtableKeyCollectionClass *) klass)->GetEnumerator = system_collections_hashtable_key_collection_real_GetEnumerator;
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_CLASS (klass)->get_IsSynchronized = system_collections_hashtable_key_collection_real_get_IsSynchronized;
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_CLASS (klass)->get_SyncRoot = system_collections_hashtable_key_collection_real_get_SyncRoot;
	SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_CLASS (klass)->get_Count = system_collections_hashtable_key_collection_real_get_Count;
	G_OBJECT_CLASS (klass)->get_property = _vala_system_collections_hashtable_key_collection_get_property;
	G_OBJECT_CLASS (klass)->finalize = system_collections_hashtable_key_collection_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_IS_SYNCHRONIZED, g_param_spec_boolean ("IsSynchronized", "IsSynchronized", "IsSynchronized", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_SYNC_ROOT, g_param_spec_object ("SyncRoot", "SyncRoot", "SyncRoot", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_COUNT, g_param_spec_int ("Count", "Count", "Count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void system_collections_hashtable_key_collection_system_collections_icollection_interface_init (SystemCollectionsICollectionIface * iface) {
	system_collections_hashtable_key_collection_system_collections_icollection_parent_iface = g_type_interface_peek_parent (iface);
	iface->CopyTo = (void (*)(SystemCollectionsICollection*, GArray*, gint)) system_collections_hashtable_key_collection_real_CopyTo;
	iface->get_IsSynchronized = (gboolean (*) (SystemCollectionsICollection *)) system_collections_hashtable_key_collection_get_IsSynchronized;
	iface->get_SyncRoot = (GObject* (*) (SystemCollectionsICollection *)) system_collections_hashtable_key_collection_get_SyncRoot;
	iface->get_Count = (gint (*) (SystemCollectionsICollection *)) system_collections_hashtable_key_collection_get_Count;
}


static void system_collections_hashtable_key_collection_system_collections_ienumerable_interface_init (SystemCollectionsIEnumerableIface * iface) {
	system_collections_hashtable_key_collection_system_collections_ienumerable_parent_iface = g_type_interface_peek_parent (iface);
	iface->GetEnumerator = (SystemCollectionsIEnumerator* (*)(SystemCollectionsIEnumerable*)) system_collections_hashtable_key_collection_GetEnumerator;
}


static void system_collections_hashtable_key_collection_instance_init (SystemCollectionsHashtableKeyCollection * self) {
	self->priv = SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_GET_PRIVATE (self);
}


static void system_collections_hashtable_key_collection_finalize (GObject* obj) {
	SystemCollectionsHashtableKeyCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, SystemCollectionsHashtableKeyCollection);
	_g_object_unref0 (self->priv->_hashtable);
	G_OBJECT_CLASS (system_collections_hashtable_key_collection_parent_class)->finalize (obj);
}


GType system_collections_hashtable_key_collection_get_type (void) {
	static volatile gsize system_collections_hashtable_key_collection_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_hashtable_key_collection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsHashtableKeyCollectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_collections_hashtable_key_collection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemCollectionsHashtableKeyCollection), 0, (GInstanceInitFunc) system_collections_hashtable_key_collection_instance_init, NULL };
		static const GInterfaceInfo system_collections_icollection_info = { (GInterfaceInitFunc) system_collections_hashtable_key_collection_system_collections_icollection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_ienumerable_info = { (GInterfaceInitFunc) system_collections_hashtable_key_collection_system_collections_ienumerable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_collections_hashtable_key_collection_type_id;
		system_collections_hashtable_key_collection_type_id = g_type_register_static (G_TYPE_OBJECT, "SystemCollectionsHashtableKeyCollection", &g_define_type_info, 0);
		g_type_add_interface_static (system_collections_hashtable_key_collection_type_id, SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, &system_collections_icollection_info);
		g_type_add_interface_static (system_collections_hashtable_key_collection_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, &system_collections_ienumerable_info);
		g_once_init_leave (&system_collections_hashtable_key_collection_type_id__volatile, system_collections_hashtable_key_collection_type_id);
	}
	return system_collections_hashtable_key_collection_type_id__volatile;
}


static void _vala_system_collections_hashtable_key_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemCollectionsHashtableKeyCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_KEY_COLLECTION, SystemCollectionsHashtableKeyCollection);
	switch (property_id) {
		case SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_IS_SYNCHRONIZED:
		g_value_set_boolean (value, system_collections_hashtable_key_collection_get_IsSynchronized (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_SYNC_ROOT:
		g_value_set_object (value, system_collections_hashtable_key_collection_get_SyncRoot (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_KEY_COLLECTION_COUNT:
		g_value_set_int (value, system_collections_hashtable_key_collection_get_Count (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


SystemCollectionsHashtableValueCollection* system_collections_hashtable_value_collection_construct (GType object_type, SystemCollectionsHashtable* hashtable) {
	SystemCollectionsHashtableValueCollection * self = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	g_return_val_if_fail (hashtable != NULL, NULL);
	self = (SystemCollectionsHashtableValueCollection*) g_object_new (object_type, NULL);
	_tmp0_ = hashtable;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_hashtable);
	self->priv->_hashtable = _tmp1_;
	return self;
}


SystemCollectionsHashtableValueCollection* system_collections_hashtable_value_collection_new (SystemCollectionsHashtable* hashtable) {
	return system_collections_hashtable_value_collection_construct (SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, hashtable);
}


static void system_collections_hashtable_value_collection_real_CopyTo (SystemCollectionsHashtableValueCollection* self, GArray* array, gint arrayIndex) {
	SystemCollectionsHashtable* _tmp0_ = NULL;
	GArray* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	g_return_if_fail (array != NULL);
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = array;
	_tmp2_ = arrayIndex;
	system_collections_hashtable_CopyValues (_tmp0_, _tmp1_, _tmp2_);
}


void system_collections_hashtable_value_collection_CopyTo (SystemCollectionsHashtableValueCollection* self, GArray* array, gint arrayIndex) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_CLASS (self)->CopyTo (self, array, arrayIndex);
}


static SystemCollectionsIEnumerator* system_collections_hashtable_value_collection_real_GetEnumerator (SystemCollectionsHashtableValueCollection* self) {
	SystemCollectionsIEnumerator* result = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtableHashtableEnumerator* _tmp1_ = NULL;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = system_collections_hashtable_hashtable_enumerator_new (_tmp0_);
	result = (SystemCollectionsIEnumerator*) _tmp1_;
	return result;
}


SystemCollectionsIEnumerator* system_collections_hashtable_value_collection_GetEnumerator (SystemCollectionsHashtableValueCollection* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_CLASS (self)->GetEnumerator (self);
}


gboolean system_collections_hashtable_value_collection_get_IsSynchronized (SystemCollectionsHashtableValueCollection* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_CLASS (self)->get_IsSynchronized (self);
}


static gboolean system_collections_hashtable_value_collection_real_get_IsSynchronized (SystemCollectionsHashtableValueCollection* base) {
	gboolean result;
	SystemCollectionsHashtableValueCollection* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	self = base;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = system_collections_hashtable_get_IsSynchronized (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


GObject* system_collections_hashtable_value_collection_get_SyncRoot (SystemCollectionsHashtableValueCollection* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_CLASS (self)->get_SyncRoot (self);
}


static GObject* system_collections_hashtable_value_collection_real_get_SyncRoot (SystemCollectionsHashtableValueCollection* base) {
	GObject* result;
	SystemCollectionsHashtableValueCollection* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	self = base;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = system_collections_hashtable_get_SyncRoot (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


gint system_collections_hashtable_value_collection_get_Count (SystemCollectionsHashtableValueCollection* self) {
	g_return_val_if_fail (self != NULL, 0);
	return SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_CLASS (self)->get_Count (self);
}


static gint system_collections_hashtable_value_collection_real_get_Count (SystemCollectionsHashtableValueCollection* base) {
	gint result;
	SystemCollectionsHashtableValueCollection* self;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	self = base;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = gee_abstract_map_get_size ((GeeMap*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


static void system_collections_hashtable_value_collection_class_init (SystemCollectionsHashtableValueCollectionClass * klass) {
	system_collections_hashtable_value_collection_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemCollectionsHashtableValueCollectionPrivate));
	((SystemCollectionsHashtableValueCollectionClass *) klass)->CopyTo = system_collections_hashtable_value_collection_real_CopyTo;
	((SystemCollectionsHashtableValueCollectionClass *) klass)->GetEnumerator = system_collections_hashtable_value_collection_real_GetEnumerator;
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_CLASS (klass)->get_IsSynchronized = system_collections_hashtable_value_collection_real_get_IsSynchronized;
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_CLASS (klass)->get_SyncRoot = system_collections_hashtable_value_collection_real_get_SyncRoot;
	SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_CLASS (klass)->get_Count = system_collections_hashtable_value_collection_real_get_Count;
	G_OBJECT_CLASS (klass)->get_property = _vala_system_collections_hashtable_value_collection_get_property;
	G_OBJECT_CLASS (klass)->finalize = system_collections_hashtable_value_collection_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_IS_SYNCHRONIZED, g_param_spec_boolean ("IsSynchronized", "IsSynchronized", "IsSynchronized", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_SYNC_ROOT, g_param_spec_object ("SyncRoot", "SyncRoot", "SyncRoot", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_COUNT, g_param_spec_int ("Count", "Count", "Count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void system_collections_hashtable_value_collection_system_collections_icollection_interface_init (SystemCollectionsICollectionIface * iface) {
	system_collections_hashtable_value_collection_system_collections_icollection_parent_iface = g_type_interface_peek_parent (iface);
	iface->CopyTo = (void (*)(SystemCollectionsICollection*, GArray*, gint)) system_collections_hashtable_value_collection_CopyTo;
	iface->get_IsSynchronized = (gboolean (*) (SystemCollectionsICollection *)) system_collections_hashtable_value_collection_get_IsSynchronized;
	iface->get_SyncRoot = (GObject* (*) (SystemCollectionsICollection *)) system_collections_hashtable_value_collection_get_SyncRoot;
	iface->get_Count = (gint (*) (SystemCollectionsICollection *)) system_collections_hashtable_value_collection_get_Count;
}


static void system_collections_hashtable_value_collection_system_collections_ienumerable_interface_init (SystemCollectionsIEnumerableIface * iface) {
	system_collections_hashtable_value_collection_system_collections_ienumerable_parent_iface = g_type_interface_peek_parent (iface);
	iface->GetEnumerator = (SystemCollectionsIEnumerator* (*)(SystemCollectionsIEnumerable*)) system_collections_hashtable_value_collection_GetEnumerator;
}


static void system_collections_hashtable_value_collection_instance_init (SystemCollectionsHashtableValueCollection * self) {
	self->priv = SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_GET_PRIVATE (self);
}


static void system_collections_hashtable_value_collection_finalize (GObject* obj) {
	SystemCollectionsHashtableValueCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, SystemCollectionsHashtableValueCollection);
	_g_object_unref0 (self->priv->_hashtable);
	G_OBJECT_CLASS (system_collections_hashtable_value_collection_parent_class)->finalize (obj);
}


GType system_collections_hashtable_value_collection_get_type (void) {
	static volatile gsize system_collections_hashtable_value_collection_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_hashtable_value_collection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsHashtableValueCollectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_collections_hashtable_value_collection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemCollectionsHashtableValueCollection), 0, (GInstanceInitFunc) system_collections_hashtable_value_collection_instance_init, NULL };
		static const GInterfaceInfo system_collections_icollection_info = { (GInterfaceInitFunc) system_collections_hashtable_value_collection_system_collections_icollection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_ienumerable_info = { (GInterfaceInitFunc) system_collections_hashtable_value_collection_system_collections_ienumerable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_collections_hashtable_value_collection_type_id;
		system_collections_hashtable_value_collection_type_id = g_type_register_static (G_TYPE_OBJECT, "SystemCollectionsHashtableValueCollection", &g_define_type_info, 0);
		g_type_add_interface_static (system_collections_hashtable_value_collection_type_id, SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, &system_collections_icollection_info);
		g_type_add_interface_static (system_collections_hashtable_value_collection_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, &system_collections_ienumerable_info);
		g_once_init_leave (&system_collections_hashtable_value_collection_type_id__volatile, system_collections_hashtable_value_collection_type_id);
	}
	return system_collections_hashtable_value_collection_type_id__volatile;
}


static void _vala_system_collections_hashtable_value_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemCollectionsHashtableValueCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_VALUE_COLLECTION, SystemCollectionsHashtableValueCollection);
	switch (property_id) {
		case SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_IS_SYNCHRONIZED:
		g_value_set_boolean (value, system_collections_hashtable_value_collection_get_IsSynchronized (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_SYNC_ROOT:
		g_value_set_object (value, system_collections_hashtable_value_collection_get_SyncRoot (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_VALUE_COLLECTION_COUNT:
		g_value_set_int (value, system_collections_hashtable_value_collection_get_Count (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


SystemCollectionsHashtableHashtableEnumerator* system_collections_hashtable_hashtable_enumerator_construct (GType object_type, SystemCollectionsHashtable* hashtable) {
	SystemCollectionsHashtableHashtableEnumerator * self = NULL;
	SystemCollectionsHashtable* _tmp0_ = NULL;
	SystemCollectionsHashtable* _tmp1_ = NULL;
	SystemCollectionsHashtable* _tmp2_ = NULL;
	GeeMapIterator* _tmp3_ = NULL;
	GeeMapIterator* _tmp4_ = NULL;
	g_return_val_if_fail (hashtable != NULL, NULL);
	self = (SystemCollectionsHashtableHashtableEnumerator*) g_object_new (object_type, NULL);
	_tmp0_ = hashtable;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_hashtable);
	self->priv->_hashtable = _tmp1_;
	_tmp2_ = hashtable;
	_tmp3_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp2_);
	_tmp4_ = _tmp3_;
	system_collections_idictionary_enumerator_set__iterator ((SystemCollectionsIDictionaryEnumerator*) self, _tmp4_);
	_g_object_unref0 (_tmp4_);
	return self;
}


SystemCollectionsHashtableHashtableEnumerator* system_collections_hashtable_hashtable_enumerator_new (SystemCollectionsHashtable* hashtable) {
	return system_collections_hashtable_hashtable_enumerator_construct (SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, hashtable);
}


static void system_collections_hashtable_hashtable_enumerator_real_Reset (SystemCollectionsHashtableHashtableEnumerator* self) {
	SystemCollectionsHashtable* _tmp0_ = NULL;
	GeeMapIterator* _tmp1_ = NULL;
	GeeMapIterator* _tmp2_ = NULL;
	_tmp0_ = self->priv->_hashtable;
	_tmp1_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp0_);
	_tmp2_ = _tmp1_;
	system_collections_idictionary_enumerator_set__iterator ((SystemCollectionsIDictionaryEnumerator*) self, _tmp2_);
	_g_object_unref0 (_tmp2_);
}


void system_collections_hashtable_hashtable_enumerator_Reset (SystemCollectionsHashtableHashtableEnumerator* self) {
	g_return_if_fail (self != NULL);
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_CLASS (self)->Reset (self);
}


static GObject* system_collections_hashtable_hashtable_enumerator_real_get__currentElement (SystemCollectionsIEnumerator* base) {
	GObject* result;
	SystemCollectionsHashtableHashtableEnumerator* self;
	GObject* _tmp0_ = NULL;
	self = (SystemCollectionsHashtableHashtableEnumerator*) base;
	_tmp0_ = self->priv->__currentElement;
	result = _tmp0_;
	return result;
}


static void system_collections_hashtable_hashtable_enumerator_real_set__currentElement (SystemCollectionsIEnumerator* base, GObject* value) {
	SystemCollectionsHashtableHashtableEnumerator* self;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	self = (SystemCollectionsHashtableHashtableEnumerator*) base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->__currentElement);
	self->priv->__currentElement = _tmp1_;
}


static GeeMapIterator* system_collections_hashtable_hashtable_enumerator_real_get__iterator (SystemCollectionsIDictionaryEnumerator* base) {
	GeeMapIterator* result;
	SystemCollectionsHashtableHashtableEnumerator* self;
	GeeMapIterator* _tmp0_ = NULL;
	self = (SystemCollectionsHashtableHashtableEnumerator*) base;
	_tmp0_ = self->priv->__iterator;
	result = _tmp0_;
	return result;
}


static void system_collections_hashtable_hashtable_enumerator_real_set__iterator (SystemCollectionsIDictionaryEnumerator* base, GeeMapIterator* value) {
	SystemCollectionsHashtableHashtableEnumerator* self;
	GeeMapIterator* _tmp0_ = NULL;
	GeeMapIterator* _tmp1_ = NULL;
	self = (SystemCollectionsHashtableHashtableEnumerator*) base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->__iterator);
	self->priv->__iterator = _tmp1_;
}


GObject* system_collections_hashtable_hashtable_enumerator_get_Key (SystemCollectionsHashtableHashtableEnumerator* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_CLASS (self)->get_Key (self);
}


static GObject* system_collections_hashtable_hashtable_enumerator_real_get_Key (SystemCollectionsHashtableHashtableEnumerator* base) {
	GObject* result;
	SystemCollectionsHashtableHashtableEnumerator* self;
	GeeMapIterator* _tmp0_ = NULL;
	GeeMapIterator* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	self = base;
	_tmp0_ = system_collections_idictionary_enumerator_get__iterator ((SystemCollectionsIDictionaryEnumerator*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = gee_map_iterator_get_key (_tmp1_);
	result = (GObject*) _tmp2_;
	return result;
}


SystemCollectionsDictionaryEntry* system_collections_hashtable_hashtable_enumerator_get_Entry (SystemCollectionsHashtableHashtableEnumerator* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_CLASS (self)->get_Entry (self);
}


static SystemCollectionsDictionaryEntry* system_collections_hashtable_hashtable_enumerator_real_get_Entry (SystemCollectionsHashtableHashtableEnumerator* base) {
	SystemCollectionsDictionaryEntry* result;
	SystemCollectionsHashtableHashtableEnumerator* self;
	GeeMapIterator* _tmp0_ = NULL;
	GeeMapIterator* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	GObject* _tmp3_ = NULL;
	GeeMapIterator* _tmp4_ = NULL;
	GeeMapIterator* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	GObject* _tmp7_ = NULL;
	SystemCollectionsDictionaryEntry* _tmp8_ = NULL;
	SystemCollectionsDictionaryEntry* _tmp9_ = NULL;
	self = base;
	_tmp0_ = system_collections_idictionary_enumerator_get__iterator ((SystemCollectionsIDictionaryEnumerator*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = gee_map_iterator_get_key (_tmp1_);
	_tmp3_ = (GObject*) _tmp2_;
	_tmp4_ = system_collections_idictionary_enumerator_get__iterator ((SystemCollectionsIDictionaryEnumerator*) self);
	_tmp5_ = _tmp4_;
	_tmp6_ = gee_map_iterator_get_value (_tmp5_);
	_tmp7_ = (GObject*) _tmp6_;
	_tmp8_ = system_collections_dictionary_entry_new (_tmp3_, _tmp7_);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp7_);
	_g_object_unref0 (_tmp3_);
	result = _tmp9_;
	return result;
}


GObject* system_collections_hashtable_hashtable_enumerator_get_Current (SystemCollectionsHashtableHashtableEnumerator* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_CLASS (self)->get_Current (self);
}


static GObject* system_collections_hashtable_hashtable_enumerator_real_get_Current (SystemCollectionsHashtableHashtableEnumerator* base) {
	GObject* result;
	SystemCollectionsHashtableHashtableEnumerator* self;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	self = base;
	_tmp0_ = system_collections_ienumerator_get__currentElement ((SystemCollectionsIEnumerator*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}


GObject* system_collections_hashtable_hashtable_enumerator_get_Value (SystemCollectionsHashtableHashtableEnumerator* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_CLASS (self)->get_Value (self);
}


static GObject* system_collections_hashtable_hashtable_enumerator_real_get_Value (SystemCollectionsHashtableHashtableEnumerator* base) {
	GObject* result;
	SystemCollectionsHashtableHashtableEnumerator* self;
	GeeMapIterator* _tmp0_ = NULL;
	GeeMapIterator* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	self = base;
	_tmp0_ = system_collections_idictionary_enumerator_get__iterator ((SystemCollectionsIDictionaryEnumerator*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = gee_map_iterator_get_value (_tmp1_);
	result = (GObject*) _tmp2_;
	return result;
}


static void system_collections_hashtable_hashtable_enumerator_class_init (SystemCollectionsHashtableHashtableEnumeratorClass * klass) {
	system_collections_hashtable_hashtable_enumerator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemCollectionsHashtableHashtableEnumeratorPrivate));
	((SystemCollectionsHashtableHashtableEnumeratorClass *) klass)->Reset = system_collections_hashtable_hashtable_enumerator_real_Reset;
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CLASS (klass)->get_Key = system_collections_hashtable_hashtable_enumerator_real_get_Key;
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CLASS (klass)->get_Entry = system_collections_hashtable_hashtable_enumerator_real_get_Entry;
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CLASS (klass)->get_Current = system_collections_hashtable_hashtable_enumerator_real_get_Current;
	SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CLASS (klass)->get_Value = system_collections_hashtable_hashtable_enumerator_real_get_Value;
	G_OBJECT_CLASS (klass)->get_property = _vala_system_collections_hashtable_hashtable_enumerator_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_system_collections_hashtable_hashtable_enumerator_set_property;
	G_OBJECT_CLASS (klass)->finalize = system_collections_hashtable_hashtable_enumerator_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_KEY, g_param_spec_object ("Key", "Key", "Key", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_ENTRY, system_collections_param_spec_dictionary_entry ("Entry", "Entry", "Entry", SYSTEM_COLLECTIONS_TYPE_DICTIONARY_ENTRY, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CURRENT, g_param_spec_object ("Current", "Current", "Current", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_VALUE, g_param_spec_object ("Value", "Value", "Value", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void system_collections_hashtable_hashtable_enumerator_system_collections_idictionary_enumerator_interface_init (SystemCollectionsIDictionaryEnumeratorIface * iface) {
	system_collections_hashtable_hashtable_enumerator_system_collections_idictionary_enumerator_parent_iface = g_type_interface_peek_parent (iface);
	iface->get__iterator = system_collections_hashtable_hashtable_enumerator_real_get__iterator;
	iface->set__iterator = system_collections_hashtable_hashtable_enumerator_real_set__iterator;
	iface->get_Key = (GObject* (*) (SystemCollectionsIDictionaryEnumerator *)) system_collections_hashtable_hashtable_enumerator_get_Key;
	iface->get_Entry = (SystemCollectionsDictionaryEntry* (*) (SystemCollectionsIDictionaryEnumerator *)) system_collections_hashtable_hashtable_enumerator_get_Entry;
	iface->get_Value = (GObject* (*) (SystemCollectionsIDictionaryEnumerator *)) system_collections_hashtable_hashtable_enumerator_get_Value;
}


static void system_collections_hashtable_hashtable_enumerator_system_collections_ienumerator_interface_init (SystemCollectionsIEnumeratorIface * iface) {
	system_collections_hashtable_hashtable_enumerator_system_collections_ienumerator_parent_iface = g_type_interface_peek_parent (iface);
	iface->Reset = (void (*)(SystemCollectionsIEnumerator*)) system_collections_hashtable_hashtable_enumerator_Reset;
	iface->get__currentElement = system_collections_hashtable_hashtable_enumerator_real_get__currentElement;
	iface->set__currentElement = system_collections_hashtable_hashtable_enumerator_real_set__currentElement;
	iface->get_Current = (GObject* (*) (SystemCollectionsIEnumerator *)) system_collections_hashtable_hashtable_enumerator_get_Current;
}


static void system_collections_hashtable_hashtable_enumerator_instance_init (SystemCollectionsHashtableHashtableEnumerator * self) {
	self->priv = SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_GET_PRIVATE (self);
}


static void system_collections_hashtable_hashtable_enumerator_finalize (GObject* obj) {
	SystemCollectionsHashtableHashtableEnumerator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumerator);
	_g_object_unref0 (self->priv->_hashtable);
	_g_object_unref0 (self->priv->__currentElement);
	_g_object_unref0 (self->priv->__iterator);
	G_OBJECT_CLASS (system_collections_hashtable_hashtable_enumerator_parent_class)->finalize (obj);
}


GType system_collections_hashtable_hashtable_enumerator_get_type (void) {
	static volatile gsize system_collections_hashtable_hashtable_enumerator_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_hashtable_hashtable_enumerator_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsHashtableHashtableEnumeratorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_collections_hashtable_hashtable_enumerator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemCollectionsHashtableHashtableEnumerator), 0, (GInstanceInitFunc) system_collections_hashtable_hashtable_enumerator_instance_init, NULL };
		static const GInterfaceInfo system_collections_idictionary_enumerator_info = { (GInterfaceInitFunc) system_collections_hashtable_hashtable_enumerator_system_collections_idictionary_enumerator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_ienumerator_info = { (GInterfaceInitFunc) system_collections_hashtable_hashtable_enumerator_system_collections_ienumerator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_collections_hashtable_hashtable_enumerator_type_id;
		system_collections_hashtable_hashtable_enumerator_type_id = g_type_register_static (G_TYPE_OBJECT, "SystemCollectionsHashtableHashtableEnumerator", &g_define_type_info, 0);
		g_type_add_interface_static (system_collections_hashtable_hashtable_enumerator_type_id, SYSTEM_COLLECTIONS_TYPE_IDICTIONARY_ENUMERATOR, &system_collections_idictionary_enumerator_info);
		g_type_add_interface_static (system_collections_hashtable_hashtable_enumerator_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, &system_collections_ienumerator_info);
		g_once_init_leave (&system_collections_hashtable_hashtable_enumerator_type_id__volatile, system_collections_hashtable_hashtable_enumerator_type_id);
	}
	return system_collections_hashtable_hashtable_enumerator_type_id__volatile;
}


static void _vala_system_collections_hashtable_hashtable_enumerator_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemCollectionsHashtableHashtableEnumerator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumerator);
	switch (property_id) {
		case SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_KEY:
		g_value_take_object (value, system_collections_hashtable_hashtable_enumerator_get_Key (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_ENTRY:
		system_collections_value_take_dictionary_entry (value, system_collections_hashtable_hashtable_enumerator_get_Entry (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_CURRENT:
		g_value_take_object (value, system_collections_hashtable_hashtable_enumerator_get_Current (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_HASHTABLE_ENUMERATOR_VALUE:
		g_value_take_object (value, system_collections_hashtable_hashtable_enumerator_get_Value (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_system_collections_hashtable_hashtable_enumerator_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SystemCollectionsHashtableHashtableEnumerator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_HASHTABLE_TYPE_HASHTABLE_ENUMERATOR, SystemCollectionsHashtableHashtableEnumerator);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void system_collections_hashtable_class_init (SystemCollectionsHashtableClass * klass) {
	system_collections_hashtable_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemCollectionsHashtablePrivate));
	((SystemCollectionsHashtableClass *) klass)->Clone = system_collections_hashtable_real_Clone;
	((SystemCollectionsHashtableClass *) klass)->ContainsKey = system_collections_hashtable_real_ContainsKey;
	((SystemCollectionsHashtableClass *) klass)->ContainsValue = system_collections_hashtable_real_ContainsValue;
	((SystemCollectionsHashtableClass *) klass)->ToKeyValuePairsArray = system_collections_hashtable_real_ToKeyValuePairsArray;
	((SystemCollectionsHashtableClass *) klass)->GetHash = system_collections_hashtable_real_GetHash;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_IsReadOnly = system_collections_hashtable_real_get_IsReadOnly;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_IsFixedSize = system_collections_hashtable_real_get_IsFixedSize;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_IsSynchronized = system_collections_hashtable_real_get_IsSynchronized;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_Keys = system_collections_hashtable_real_get_Keys;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_Values = system_collections_hashtable_real_get_Values;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_SyncRoot = system_collections_hashtable_real_get_SyncRoot;
	SYSTEM_COLLECTIONS_HASHTABLE_CLASS (klass)->get_Count = system_collections_hashtable_real_get_Count;
	G_OBJECT_CLASS (klass)->get_property = _vala_system_collections_hashtable_get_property;
	G_OBJECT_CLASS (klass)->finalize = system_collections_hashtable_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_EQUALITY_COMPARER, g_param_spec_object ("EqualityComparer", "EqualityComparer", "EqualityComparer", SYSTEM_COLLECTIONS_TYPE_IEQUALITY_COMPARER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_IS_SYNCHRONIZED, g_param_spec_boolean ("IsSynchronized", "IsSynchronized", "IsSynchronized", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_KEYS, g_param_spec_object ("Keys", "Keys", "Keys", SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_VALUES, g_param_spec_object ("Values", "Values", "Values", SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_SYNC_ROOT, g_param_spec_object ("SyncRoot", "SyncRoot", "SyncRoot", G_TYPE_OBJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_HASHTABLE_COUNT, g_param_spec_int ("Count", "Count", "Count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void system_collections_hashtable_system_collections_idictionary_interface_init (SystemCollectionsIDictionaryIface * iface) {
	system_collections_hashtable_system_collections_idictionary_parent_iface = g_type_interface_peek_parent (iface);
	iface->GetEnumerator = (SystemCollectionsIDictionaryEnumerator* (*)(SystemCollectionsIDictionary*)) system_collections_hashtable_real_GetEnumerator;
	iface->get_IsReadOnly = (gboolean (*) (SystemCollectionsIDictionary *)) system_collections_hashtable_get_IsReadOnly;
	iface->get_IsFixedSize = (gboolean (*) (SystemCollectionsIDictionary *)) system_collections_hashtable_get_IsFixedSize;
	iface->get_Keys = (SystemCollectionsICollection* (*) (SystemCollectionsIDictionary *)) system_collections_hashtable_get_Keys;
	iface->get_Values = (SystemCollectionsICollection* (*) (SystemCollectionsIDictionary *)) system_collections_hashtable_get_Values;
}


static void system_collections_hashtable_system_collections_ienumerable_interface_init (SystemCollectionsIEnumerableIface * iface) {
	system_collections_hashtable_system_collections_ienumerable_parent_iface = g_type_interface_peek_parent (iface);
}


static void system_collections_hashtable_system_collections_icollection_interface_init (SystemCollectionsICollectionIface * iface) {
	system_collections_hashtable_system_collections_icollection_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_IsSynchronized = (gboolean (*) (SystemCollectionsICollection *)) system_collections_hashtable_get_IsSynchronized;
	iface->get_SyncRoot = (GObject* (*) (SystemCollectionsICollection *)) system_collections_hashtable_get_SyncRoot;
	iface->get_Count = (gint (*) (SystemCollectionsICollection *)) system_collections_hashtable_get_Count;
}


static void system_collections_hashtable_instance_init (SystemCollectionsHashtable * self) {
	self->priv = SYSTEM_COLLECTIONS_HASHTABLE_GET_PRIVATE (self);
}


static void system_collections_hashtable_finalize (GObject* obj) {
	SystemCollectionsHashtable * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtable);
	_g_object_unref0 (self->priv->_keys);
	_g_object_unref0 (self->priv->_values);
	_g_object_unref0 (self->priv->_keycomparer);
	_g_object_unref0 (self->_syncRoot);
	G_OBJECT_CLASS (system_collections_hashtable_parent_class)->finalize (obj);
}


GType system_collections_hashtable_get_type (void) {
	static volatile gsize system_collections_hashtable_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_hashtable_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsHashtableClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_collections_hashtable_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemCollectionsHashtable), 0, (GInstanceInitFunc) system_collections_hashtable_instance_init, NULL };
		static const GInterfaceInfo system_collections_idictionary_info = { (GInterfaceInitFunc) system_collections_hashtable_system_collections_idictionary_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_ienumerable_info = { (GInterfaceInitFunc) system_collections_hashtable_system_collections_ienumerable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_icollection_info = { (GInterfaceInitFunc) system_collections_hashtable_system_collections_icollection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_collections_hashtable_type_id;
		system_collections_hashtable_type_id = g_type_register_static (GEE_TYPE_HASH_MAP, "SystemCollectionsHashtable", &g_define_type_info, 0);
		g_type_add_interface_static (system_collections_hashtable_type_id, SYSTEM_COLLECTIONS_TYPE_IDICTIONARY, &system_collections_idictionary_info);
		g_type_add_interface_static (system_collections_hashtable_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, &system_collections_ienumerable_info);
		g_type_add_interface_static (system_collections_hashtable_type_id, SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, &system_collections_icollection_info);
		g_once_init_leave (&system_collections_hashtable_type_id__volatile, system_collections_hashtable_type_id);
	}
	return system_collections_hashtable_type_id__volatile;
}


static void _vala_system_collections_hashtable_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemCollectionsHashtable * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_TYPE_HASHTABLE, SystemCollectionsHashtable);
	switch (property_id) {
		case SYSTEM_COLLECTIONS_HASHTABLE_EQUALITY_COMPARER:
		g_value_set_object (value, system_collections_hashtable_get_EqualityComparer (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_IS_SYNCHRONIZED:
		g_value_set_boolean (value, system_collections_hashtable_get_IsSynchronized (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_KEYS:
		g_value_take_object (value, system_collections_hashtable_get_Keys (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_VALUES:
		g_value_take_object (value, system_collections_hashtable_get_Values (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_SYNC_ROOT:
		g_value_set_object (value, system_collections_hashtable_get_SyncRoot (self));
		break;
		case SYSTEM_COLLECTIONS_HASHTABLE_COUNT:
		g_value_set_int (value, system_collections_hashtable_get_Count (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



