/* icomparer.c generated by valac 0.29.2.5-8632-dirty, the Vala compiler
 * generated from icomparer.vala, do not modify */

/* ==++==*/
/* */
/*   Copyright (c) Microsoft Corporation.  All rights reserved.*/
/* */
/* ==--==*/
/*============================================================
**
** Interface:  IComparer
** 
** <OWNER>[....]</OWNER>
**
**
** Purpose: Interface for comparing two GLib.Objects.
**
** 
===========================================================*/

#include <glib.h>
#include <glib-object.h>


#define SYSTEM_COLLECTIONS_TYPE_ICOMPARER (system_collections_icomparer_get_type ())
#define SYSTEM_COLLECTIONS_ICOMPARER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_ICOMPARER, SystemCollectionsIComparer))
#define SYSTEM_COLLECTIONS_IS_ICOMPARER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOMPARER))
#define SYSTEM_COLLECTIONS_ICOMPARER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOMPARER, SystemCollectionsIComparerIface))

typedef struct _SystemCollectionsIComparer SystemCollectionsIComparer;
typedef struct _SystemCollectionsIComparerIface SystemCollectionsIComparerIface;

struct _SystemCollectionsIComparerIface {
	GTypeInterface parent_iface;
	gint (*Compare) (SystemCollectionsIComparer* self, GObject* x, GObject* y);
};



GType system_collections_icomparer_get_type (void) G_GNUC_CONST;
gint system_collections_icomparer_Compare (SystemCollectionsIComparer* self, GObject* x, GObject* y);


gint system_collections_icomparer_Compare (SystemCollectionsIComparer* self, GObject* x, GObject* y) {
#line 31 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/icomparer.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 31 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/icomparer.vala"
	return SYSTEM_COLLECTIONS_ICOMPARER_GET_INTERFACE (self)->Compare (self, x, y);
#line 50 "icomparer.c"
}


static void system_collections_icomparer_base_init (SystemCollectionsIComparerIface * iface) {
#line 26 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/icomparer.vala"
	static gboolean initialized = FALSE;
#line 26 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/icomparer.vala"
	if (!initialized) {
#line 26 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/icomparer.vala"
		initialized = TRUE;
#line 61 "icomparer.c"
	}
}


GType system_collections_icomparer_get_type (void) {
	static volatile gsize system_collections_icomparer_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_icomparer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsIComparerIface), (GBaseInitFunc) system_collections_icomparer_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType system_collections_icomparer_type_id;
		system_collections_icomparer_type_id = g_type_register_static (G_TYPE_INTERFACE, "SystemCollectionsIComparer", &g_define_type_info, 0);
		g_once_init_leave (&system_collections_icomparer_type_id__volatile, system_collections_icomparer_type_id);
	}
	return system_collections_icomparer_type_id__volatile;
}



