/* Exceptions.c generated by valac 0.29.2.5-8632-dirty, the Vala compiler
 * generated from Exceptions.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


typedef enum  {
	SYSTEM_ARRAY_TYPE_MISMATCH_EXCEPTION_ARRAY_TYPE_MISMATCH
} SystemArrayTypeMismatchException;
#define SYSTEM_ARRAY_TYPE_MISMATCH_EXCEPTION system_array_type_mismatch_exception_quark ()
typedef enum  {
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_INDEX,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_VALUE,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_NEED_NON_NEG_NUM,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_BEGIN_INDEX_NOT_NEGATIVE,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_LENGTH_NOT_NEGATIVE,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_NEGATIVE_CAPACITY,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_NEGATIVE_LENGTH,
	SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION_SMALL_CAPACITY
} SystemArgumentOutOfRangeException;
#define SYSTEM_ARGUMENT_OUT_OF_RANGE_EXCEPTION system_argument_out_of_range_exception_quark ()
typedef enum  {
	SYSTEM_ERROR_NOELEMENTS
} SystemError;
#define SYSTEM_ERROR system_error_quark ()
typedef enum  {
	SYSTEM_ARGUMENT_EXCEPTION_NULL,
	SYSTEM_ARGUMENT_EXCEPTION_INVALID_OFFSET_LENGTH,
	SYSTEM_ARGUMENT_EXCEPTION_NOT_FOUND,
	SYSTEM_ARGUMENT_EXCEPTION_IMPLEMENT_ICOMPARABLE,
	SYSTEM_ARGUMENT_EXCEPTION_INVALID_ARRAY_TYPE,
	SYSTEM_ARGUMENT_EXCEPTION_ADDING_DUPLICATE
} SystemArgumentException;
#define SYSTEM_ARGUMENT_EXCEPTION system_argument_exception_quark ()
typedef enum  {
	SYSTEM_ARGUMENT_NULL_EXCEPTION_POINTER,
	SYSTEM_ARGUMENT_NULL_EXCEPTION_VALUE,
	SYSTEM_ARGUMENT_NULL_EXCEPTION_STRING
} SystemArgumentNullException;
#define SYSTEM_ARGUMENT_NULL_EXCEPTION system_argument_null_exception_quark ()
typedef enum  {
	SYSTEM_INVALID_OPERATION_EXCEPTION_ENUM_NOT_STARTED,
	SYSTEM_INVALID_OPERATION_EXCEPTION_ENUM_ENDED,
	SYSTEM_INVALID_OPERATION_EXCEPTION_NOT_IMPLEMENTED,
	SYSTEM_INVALID_OPERATION_EXCEPTION_COMPARE_FAILED
} SystemInvalidOperationException;
#define SYSTEM_INVALID_OPERATION_EXCEPTION system_invalid_operation_exception_quark ()
typedef enum  {
	SYSTEM_NOT_SUPPORTED_EXCEPTION_RANGE_COLLECTION,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_FIXED_SIZE_COLLECTION,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_SORTED_LIST_NESTED_WRITE,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_KEY_COLLECTION_SET
} SystemNotSupportedException;
#define SYSTEM_NOT_SUPPORTED_EXCEPTION system_not_supported_exception_quark ()
typedef enum  {
	SYSTEM_SERIALIZATION_EXCEPTION_SERIALIZATION
} SystemSerializationException;
#define SYSTEM_SERIALIZATION_EXCEPTION system_serialization_exception_quark ()


GQuark system_array_type_mismatch_exception_quark (void);
GQuark system_argument_out_of_range_exception_quark (void);
GQuark system_error_quark (void);
GQuark system_argument_exception_quark (void);
GQuark system_argument_null_exception_quark (void);
GQuark system_invalid_operation_exception_quark (void);
GQuark system_not_supported_exception_quark (void);
GQuark system_serialization_exception_quark (void);


GQuark system_array_type_mismatch_exception_quark (void) {
	return g_quark_from_static_string ("system_array_type_mismatch_exception-quark");
}


GQuark system_argument_out_of_range_exception_quark (void) {
	return g_quark_from_static_string ("system_argument_out_of_range_exception-quark");
}


GQuark system_error_quark (void) {
	return g_quark_from_static_string ("system_error-quark");
}


GQuark system_argument_exception_quark (void) {
	return g_quark_from_static_string ("system_argument_exception-quark");
}


GQuark system_argument_null_exception_quark (void) {
	return g_quark_from_static_string ("system_argument_null_exception-quark");
}


GQuark system_invalid_operation_exception_quark (void) {
	return g_quark_from_static_string ("system_invalid_operation_exception-quark");
}


GQuark system_not_supported_exception_quark (void) {
	return g_quark_from_static_string ("system_not_supported_exception-quark");
}


GQuark system_serialization_exception_quark (void) {
	return g_quark_from_static_string ("system_serialization_exception-quark");
}



