/* icustomformatter.c generated by valac 0.29.2.5-8632-dirty, the Vala compiler
 * generated from icustomformatter.vala, do not modify */

/* ==++==*/
/* */
/*   Copyright (c) Microsoft Corporation.  All rights reserved.*/
/* */
/* ==--==*/
/*============================================================
**
** Interface:  ICustomFormatter
**
**
** Purpose: Marks a class as providing special formatting
**
**
===========================================================*/

#include <glib.h>
#include <glib-object.h>


#define SYSTEM_TYPE_ICUSTOM_FORMATTER (system_icustom_formatter_get_type ())
#define SYSTEM_ICUSTOM_FORMATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TYPE_ICUSTOM_FORMATTER, SystemICustomFormatter))
#define SYSTEM_IS_ICUSTOM_FORMATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TYPE_ICUSTOM_FORMATTER))
#define SYSTEM_ICUSTOM_FORMATTER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_TYPE_ICUSTOM_FORMATTER, SystemICustomFormatterIface))

typedef struct _SystemICustomFormatter SystemICustomFormatter;
typedef struct _SystemICustomFormatterIface SystemICustomFormatterIface;

struct _SystemICustomFormatterIface {
	GTypeInterface parent_iface;
};



GType system_icustom_formatter_get_type (void) G_GNUC_CONST;


static void system_icustom_formatter_base_init (SystemICustomFormatterIface * iface) {
#line 21 "/home/developer/projects/Backup/LibDotNet/src/System/icustomformatter.vala"
	static gboolean initialized = FALSE;
#line 21 "/home/developer/projects/Backup/LibDotNet/src/System/icustomformatter.vala"
	if (!initialized) {
#line 21 "/home/developer/projects/Backup/LibDotNet/src/System/icustomformatter.vala"
		initialized = TRUE;
#line 48 "icustomformatter.c"
	}
}


GType system_icustom_formatter_get_type (void) {
	static volatile gsize system_icustom_formatter_type_id__volatile = 0;
	if (g_once_init_enter (&system_icustom_formatter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemICustomFormatterIface), (GBaseInitFunc) system_icustom_formatter_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType system_icustom_formatter_type_id;
		system_icustom_formatter_type_id = g_type_register_static (G_TYPE_INTERFACE, "SystemICustomFormatter", &g_define_type_info, 0);
		g_once_init_leave (&system_icustom_formatter_type_id__volatile, system_icustom_formatter_type_id);
	}
	return system_icustom_formatter_type_id__volatile;
}



