/* ReadOnlyCollection.c generated by valac 0.29.2.5-8632-dirty, the Vala compiler
 * generated from ReadOnlyCollection.vala, do not modify */

/* ==++==*/
/* */
/*   Copyright (c) Microsoft Corporation.  All rights reserved.*/
/* */
/* ==--==*/
/* */

#include <glib.h>
#include <glib-object.h>


#define SYSTEM_LINQ_TYPE_ENUMERABLE (system_linq_enumerable_get_type ())
#define SYSTEM_LINQ_ENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_LINQ_TYPE_ENUMERABLE, SystemLinqEnumerable))
#define SYSTEM_LINQ_ENUMERABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_LINQ_TYPE_ENUMERABLE, SystemLinqEnumerableClass))
#define SYSTEM_LINQ_IS_ENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_LINQ_TYPE_ENUMERABLE))
#define SYSTEM_LINQ_IS_ENUMERABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_LINQ_TYPE_ENUMERABLE))
#define SYSTEM_LINQ_ENUMERABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_LINQ_TYPE_ENUMERABLE, SystemLinqEnumerableClass))

typedef struct _SystemLinqEnumerable SystemLinqEnumerable;
typedef struct _SystemLinqEnumerableClass SystemLinqEnumerableClass;
typedef struct _SystemLinqEnumerablePrivate SystemLinqEnumerablePrivate;

#define SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE (system_collections_generic_ienumerable_get_type ())
#define SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE, SystemCollectionsGenericIEnumerable))
#define SYSTEM_COLLECTIONS_GENERIC_IS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE))
#define SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE, SystemCollectionsGenericIEnumerableIface))

typedef struct _SystemCollectionsGenericIEnumerable SystemCollectionsGenericIEnumerable;
typedef struct _SystemCollectionsGenericIEnumerableIface SystemCollectionsGenericIEnumerableIface;

#define SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERATOR (system_collections_generic_ienumerator_get_type ())
#define SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERATOR, SystemCollectionsGenericIEnumerator))
#define SYSTEM_COLLECTIONS_GENERIC_IS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERATOR))
#define SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERATOR, SystemCollectionsGenericIEnumeratorIface))

typedef struct _SystemCollectionsGenericIEnumerator SystemCollectionsGenericIEnumerator;
typedef struct _SystemCollectionsGenericIEnumeratorIface SystemCollectionsGenericIEnumeratorIface;

#define SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION (system_collections_generic_icollection_get_type ())
#define SYSTEM_COLLECTIONS_GENERIC_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollection))
#define SYSTEM_COLLECTIONS_GENERIC_IS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION))
#define SYSTEM_COLLECTIONS_GENERIC_ICOLLECTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollectionIface))

typedef struct _SystemCollectionsGenericICollection SystemCollectionsGenericICollection;
typedef struct _SystemCollectionsGenericICollectionIface SystemCollectionsGenericICollectionIface;

#define SYSTEM_COLLECTIONS_GENERIC_TYPE_IREAD_ONLY_COLLECTION (system_collections_generic_iread_only_collection_get_type ())
#define SYSTEM_COLLECTIONS_GENERIC_IREAD_ONLY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IREAD_ONLY_COLLECTION, SystemCollectionsGenericIReadOnlyCollection))
#define SYSTEM_COLLECTIONS_GENERIC_IS_IREAD_ONLY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IREAD_ONLY_COLLECTION))
#define SYSTEM_COLLECTIONS_GENERIC_IREAD_ONLY_COLLECTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_IREAD_ONLY_COLLECTION, SystemCollectionsGenericIReadOnlyCollectionIface))

typedef struct _SystemCollectionsGenericIReadOnlyCollection SystemCollectionsGenericIReadOnlyCollection;
typedef struct _SystemCollectionsGenericIReadOnlyCollectionIface SystemCollectionsGenericIReadOnlyCollectionIface;

#define SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION (system_collections_object_model_read_only_collection_get_type ())
#define SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollection))
#define SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollectionClass))
#define SYSTEM_COLLECTIONS_OBJECT_MODEL_IS_READ_ONLY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION))
#define SYSTEM_COLLECTIONS_OBJECT_MODEL_IS_READ_ONLY_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION))
#define SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollectionClass))

typedef struct _SystemCollectionsObjectModelReadOnlyCollection SystemCollectionsObjectModelReadOnlyCollection;
typedef struct _SystemCollectionsObjectModelReadOnlyCollectionClass SystemCollectionsObjectModelReadOnlyCollectionClass;
typedef struct _SystemCollectionsObjectModelReadOnlyCollectionPrivate SystemCollectionsObjectModelReadOnlyCollectionPrivate;

#define SYSTEM_COLLECTIONS_GENERIC_TYPE_ILIST (system_collections_generic_ilist_get_type ())
#define SYSTEM_COLLECTIONS_GENERIC_ILIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_ILIST, SystemCollectionsGenericIList))
#define SYSTEM_COLLECTIONS_GENERIC_IS_ILIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_ILIST))
#define SYSTEM_COLLECTIONS_GENERIC_ILIST_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_GENERIC_TYPE_ILIST, SystemCollectionsGenericIListIface))

typedef struct _SystemCollectionsGenericIList SystemCollectionsGenericIList;
typedef struct _SystemCollectionsGenericIListIface SystemCollectionsGenericIListIface;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef gpointer (*SystemFunc) (gconstpointer arg, void* user_data);
struct _SystemCollectionsGenericIEnumeratorIface {
	GTypeInterface parent_iface;
	GType (*get_t_type) (SystemCollectionsGenericIEnumerator* self);
	GBoxedCopyFunc (*get_t_dup_func) (SystemCollectionsGenericIEnumerator* self);
	GDestroyNotify (*get_t_destroy_func) (SystemCollectionsGenericIEnumerator* self);
	gpointer (*get) (SystemCollectionsGenericIEnumerator* self);
	gboolean (*MoveNext) (SystemCollectionsGenericIEnumerator* self);
	gboolean (*next) (SystemCollectionsGenericIEnumerator* self);
	void (*Reset) (SystemCollectionsGenericIEnumerator* self);
	gpointer (*get_Current) (SystemCollectionsGenericIEnumerator* self);
};

struct _SystemCollectionsGenericIEnumerableIface {
	GTypeInterface parent_iface;
	GType (*get_t_type) (SystemCollectionsGenericIEnumerable* self);
	GBoxedCopyFunc (*get_t_dup_func) (SystemCollectionsGenericIEnumerable* self);
	GDestroyNotify (*get_t_destroy_func) (SystemCollectionsGenericIEnumerable* self);
	GType (*get_element_type) (SystemCollectionsGenericIEnumerable* self);
	SystemCollectionsGenericIEnumerator* (*iterator) (SystemCollectionsGenericIEnumerable* self);
	SystemCollectionsGenericIEnumerator* (*GetEnumerator) (SystemCollectionsGenericIEnumerable* self);
};

struct _SystemLinqEnumerable {
	GObject parent_instance;
	SystemLinqEnumerablePrivate * priv;
};

struct _SystemLinqEnumerableClass {
	GObjectClass parent_class;
	SystemCollectionsGenericIEnumerable* (*Where) (SystemLinqEnumerable* self, SystemFunc predicate, void* predicate_target);
};

struct _SystemCollectionsGenericICollectionIface {
	GTypeInterface parent_iface;
	void (*Add) (SystemCollectionsGenericICollection* self, gconstpointer item);
	void (*Clear) (SystemCollectionsGenericICollection* self);
	gboolean (*contains) (SystemCollectionsGenericICollection* self, gconstpointer item);
	gboolean (*Contains) (SystemCollectionsGenericICollection* self, gconstpointer item);
	void (*CopyTo) (SystemCollectionsGenericICollection* self, gpointer* array, int array_length1, gint arrayIndex);
	gboolean (*Remove) (SystemCollectionsGenericICollection* self, gconstpointer item);
	gint (*get_size) (SystemCollectionsGenericICollection* self);
	gint (*get_Count) (SystemCollectionsGenericICollection* self);
	gboolean (*get_IsReadOnly) (SystemCollectionsGenericICollection* self);
};

struct _SystemCollectionsGenericIReadOnlyCollectionIface {
	GTypeInterface parent_iface;
	gint (*get_size) (SystemCollectionsGenericIReadOnlyCollection* self);
	gint (*get_Count) (SystemCollectionsGenericIReadOnlyCollection* self);
};

struct _SystemCollectionsObjectModelReadOnlyCollection {
	SystemLinqEnumerable parent_instance;
	SystemCollectionsObjectModelReadOnlyCollectionPrivate * priv;
};

struct _SystemCollectionsObjectModelReadOnlyCollectionClass {
	SystemLinqEnumerableClass parent_class;
	gint (*get_size) (SystemCollectionsObjectModelReadOnlyCollection* self);
	gboolean (*get_IsReadOnly) (SystemCollectionsObjectModelReadOnlyCollection* self);
};

struct _SystemCollectionsGenericIListIface {
	GTypeInterface parent_iface;
	gpointer (*get) (SystemCollectionsGenericIList* self, gint index);
	void (*set) (SystemCollectionsGenericIList* self, gint index, gconstpointer item);
	gint (*IndexOf) (SystemCollectionsGenericIList* self, gconstpointer item, gint index);
	void (*Insert) (SystemCollectionsGenericIList* self, gint index, gconstpointer item);
	void (*RemoveAt) (SystemCollectionsGenericIList* self, gint index);
};

struct _SystemCollectionsObjectModelReadOnlyCollectionPrivate {
	GType t_type;
	GBoxedCopyFunc t_dup_func;
	GDestroyNotify t_destroy_func;
	SystemCollectionsGenericIList* list;
	GObject* _syncRoot;
};

typedef enum  {
	SYSTEM_NOT_SUPPORTED_EXCEPTION_RANGE_COLLECTION,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_FIXED_SIZE_COLLECTION,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_SORTED_LIST_NESTED_WRITE,
	SYSTEM_NOT_SUPPORTED_EXCEPTION_KEY_COLLECTION_SET
} SystemNotSupportedException;
#define SYSTEM_NOT_SUPPORTED_EXCEPTION system_not_supported_exception_quark ()

static gpointer system_collections_object_model_read_only_collection_parent_class = NULL;
static SystemCollectionsGenericIEnumerableIface* system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_parent_iface = NULL;
static SystemCollectionsGenericICollectionIface* system_collections_object_model_read_only_collection_system_collections_generic_icollection_parent_iface = NULL;
static SystemCollectionsGenericIReadOnlyCollectionIface* system_collections_object_model_read_only_collection_system_collections_generic_iread_only_collection_parent_iface = NULL;

GType system_linq_enumerable_get_type (void) G_GNUC_CONST;
GType system_collections_generic_ienumerator_get_type (void) G_GNUC_CONST;
GType system_collections_generic_ienumerable_get_type (void) G_GNUC_CONST;
GType system_collections_generic_icollection_get_type (void) G_GNUC_CONST;
GType system_collections_generic_iread_only_collection_get_type (void) G_GNUC_CONST;
GType system_collections_object_model_read_only_collection_get_type (void) G_GNUC_CONST;
GType system_collections_generic_ilist_get_type (void) G_GNUC_CONST;
#define SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollectionPrivate))
enum  {
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_DUMMY_PROPERTY,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_TYPE,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_DUP_FUNC,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_DESTROY_FUNC,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_COUNT,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_SIZE,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_ITEMS,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_READ_ONLY,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_SYNCHRONIZED,
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_FIXED_SIZE
};
SystemCollectionsObjectModelReadOnlyCollection* system_collections_object_model_read_only_collection_new (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, SystemCollectionsGenericIList* list);
SystemCollectionsObjectModelReadOnlyCollection* system_collections_object_model_read_only_collection_construct (GType object_type, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, SystemCollectionsGenericIList* list);
SystemLinqEnumerable* system_linq_enumerable_construct (GType object_type, GType tsource_type, GBoxedCopyFunc tsource_dup_func, GDestroyNotify tsource_destroy_func);
gpointer system_collections_object_model_read_only_collection_get (SystemCollectionsObjectModelReadOnlyCollection* self, gint index);
gpointer system_collections_generic_ilist_get (SystemCollectionsGenericIList* self, gint index);
void system_collections_object_model_read_only_collection_set (SystemCollectionsObjectModelReadOnlyCollection* self, gint index, gconstpointer value);
GQuark system_not_supported_exception_quark (void);
static gboolean system_collections_object_model_read_only_collection_real_contains (SystemCollectionsGenericICollection* base, gconstpointer value);
gboolean system_collections_generic_icollection_Contains (SystemCollectionsGenericICollection* self, gconstpointer item);
static gboolean system_collections_object_model_read_only_collection_real_Contains (SystemCollectionsGenericICollection* base, gconstpointer value);
static void system_collections_object_model_read_only_collection_real_CopyTo (SystemCollectionsGenericICollection* base, gpointer* array, int array_length1, gint index);
void system_collections_generic_icollection_CopyTo (SystemCollectionsGenericICollection* self, gpointer* array, int array_length1, gint arrayIndex);
static SystemCollectionsGenericIEnumerator* system_collections_object_model_read_only_collection_real_GetEnumerator (SystemCollectionsGenericIEnumerable* base);
SystemCollectionsGenericIEnumerator* system_collections_generic_ienumerable_GetEnumerator (SystemCollectionsGenericIEnumerable* self);
static SystemCollectionsGenericIEnumerator* system_collections_object_model_read_only_collection_real_iterator (SystemCollectionsGenericIEnumerable* base);
gint system_collections_object_model_read_only_collection_IndexOf (SystemCollectionsObjectModelReadOnlyCollection* self, gconstpointer value, gint index);
gint system_collections_generic_ilist_IndexOf (SystemCollectionsGenericIList* self, gconstpointer item, gint index);
static GType system_collections_object_model_read_only_collection_real_get_element_type (SystemCollectionsGenericIEnumerable* base);
static void system_collections_object_model_read_only_collection_real_Add (SystemCollectionsGenericICollection* base, gconstpointer value);
static void system_collections_object_model_read_only_collection_real_Clear (SystemCollectionsGenericICollection* base);
void system_collections_object_model_read_only_collection_Insert (SystemCollectionsObjectModelReadOnlyCollection* self, gint index, gconstpointer value);
static gboolean system_collections_object_model_read_only_collection_real_Remove (SystemCollectionsGenericICollection* base, gconstpointer value);
void system_collections_object_model_read_only_collection_RemoveAt (SystemCollectionsObjectModelReadOnlyCollection* self, gint index);
gint system_collections_generic_icollection_get_Count (SystemCollectionsGenericICollection* self);
gint system_collections_object_model_read_only_collection_get_size (SystemCollectionsObjectModelReadOnlyCollection* self);
gint system_collections_generic_icollection_get_size (SystemCollectionsGenericICollection* self);
SystemCollectionsGenericIList* system_collections_object_model_read_only_collection_get_Items (SystemCollectionsObjectModelReadOnlyCollection* self);
gboolean system_collections_object_model_read_only_collection_get_IsReadOnly (SystemCollectionsObjectModelReadOnlyCollection* self);
gboolean system_collections_object_model_read_only_collection_get_IsSynchronized (SystemCollectionsObjectModelReadOnlyCollection* self);
gboolean system_collections_object_model_read_only_collection_get_IsFixedSize (SystemCollectionsObjectModelReadOnlyCollection* self);
static void system_collections_object_model_read_only_collection_finalize (GObject* obj);
static void _vala_system_collections_object_model_read_only_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_system_collections_object_model_read_only_collection_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
#line 24 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return self ? g_object_ref (self) : NULL;
#line 231 "ReadOnlyCollection.c"
}


SystemCollectionsObjectModelReadOnlyCollection* system_collections_object_model_read_only_collection_construct (GType object_type, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, SystemCollectionsGenericIList* list) {
	SystemCollectionsObjectModelReadOnlyCollection * self = NULL;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	SystemCollectionsGenericIList* _tmp1_ = NULL;
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (list != NULL, NULL);
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) system_linq_enumerable_construct (object_type, t_type, (GBoxedCopyFunc) t_dup_func, t_destroy_func);
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self->priv->t_type = t_type;
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self->priv->t_dup_func = t_dup_func;
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self->priv->t_destroy_func = t_destroy_func;
#line 24 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = list;
#line 24 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 24 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_g_object_unref0 (self->priv->list);
#line 24 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self->priv->list = _tmp1_;
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return self;
#line 259 "ReadOnlyCollection.c"
}


SystemCollectionsObjectModelReadOnlyCollection* system_collections_object_model_read_only_collection_new (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, SystemCollectionsGenericIList* list) {
#line 23 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return system_collections_object_model_read_only_collection_construct (SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, t_type, t_dup_func, t_destroy_func, list);
#line 266 "ReadOnlyCollection.c"
}


gpointer system_collections_object_model_read_only_collection_get (SystemCollectionsObjectModelReadOnlyCollection* self, gint index) {
	gpointer result = NULL;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gpointer _tmp2_ = NULL;
#line 35 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = index;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = system_collections_generic_ilist_get (_tmp0_, _tmp1_);
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp2_;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 287 "ReadOnlyCollection.c"
}


void system_collections_object_model_read_only_collection_set (SystemCollectionsObjectModelReadOnlyCollection* self, gint index, gconstpointer value) {
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 39 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_if_fail (self != NULL);
#line 40 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = g_error_new_literal (SYSTEM_NOT_SUPPORTED_EXCEPTION, SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION, "ExceptionResource.NotSupported_ReadOnlyCollection");
#line 40 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_inner_error_ = _tmp0_;
#line 40 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 40 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_clear_error (&_inner_error_);
#line 40 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return;
#line 306 "ReadOnlyCollection.c"
}


static gboolean system_collections_object_model_read_only_collection_real_contains (SystemCollectionsGenericICollection* base, gconstpointer value) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	gboolean result = FALSE;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 43 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = value;
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = system_collections_generic_icollection_Contains (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollection), _tmp1_);
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp2_;
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 328 "ReadOnlyCollection.c"
}


static gboolean system_collections_object_model_read_only_collection_real_Contains (SystemCollectionsGenericICollection* base, gconstpointer value) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	gboolean result = FALSE;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 47 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 48 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 48 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = value;
#line 48 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = system_collections_generic_icollection_Contains (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollection), _tmp1_);
#line 48 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp2_;
#line 48 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 350 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_real_CopyTo (SystemCollectionsGenericICollection* base, gpointer* array, int array_length1, gint index) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gpointer* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
#line 51 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = array;
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1__length1 = array_length1;
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = index;
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	system_collections_generic_icollection_CopyTo (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollection), _tmp1_, _tmp1__length1, _tmp2_);
#line 372 "ReadOnlyCollection.c"
}


static SystemCollectionsGenericIEnumerator* system_collections_object_model_read_only_collection_real_GetEnumerator (SystemCollectionsGenericIEnumerable* base) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	SystemCollectionsGenericIEnumerator* result = NULL;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	SystemCollectionsGenericIEnumerator* _tmp1_ = NULL;
#line 55 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 56 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 56 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = system_collections_generic_ienumerable_GetEnumerator (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE, SystemCollectionsGenericIEnumerable));
#line 56 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp1_;
#line 56 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 391 "ReadOnlyCollection.c"
}


static SystemCollectionsGenericIEnumerator* system_collections_object_model_read_only_collection_real_iterator (SystemCollectionsGenericIEnumerable* base) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	SystemCollectionsGenericIEnumerator* result = NULL;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	SystemCollectionsGenericIEnumerator* _tmp1_ = NULL;
#line 59 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 60 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 60 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = system_collections_generic_ienumerable_GetEnumerator (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE, SystemCollectionsGenericIEnumerable));
#line 60 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp1_;
#line 60 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 410 "ReadOnlyCollection.c"
}


gint system_collections_object_model_read_only_collection_IndexOf (SystemCollectionsObjectModelReadOnlyCollection* self, gconstpointer value, gint index) {
	gint result = 0;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	gint _tmp2_ = 0;
#line 63 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 64 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 64 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = value;
#line 64 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = system_collections_generic_ilist_IndexOf (_tmp0_, _tmp1_, 0);
#line 64 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp2_;
#line 64 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 431 "ReadOnlyCollection.c"
}


static GType system_collections_object_model_read_only_collection_real_get_element_type (SystemCollectionsGenericIEnumerable* base) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	GType result = 0UL;
#line 77 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 78 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = self->priv->t_type;
#line 78 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 444 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_real_Add (SystemCollectionsGenericICollection* base, gconstpointer value) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 81 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = g_error_new_literal (SYSTEM_NOT_SUPPORTED_EXCEPTION, SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION, "ExceptionResource.NotSupported_ReadOnlyCollection");
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_inner_error_ = _tmp0_;
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_clear_error (&_inner_error_);
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return;
#line 464 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_real_Clear (SystemCollectionsGenericICollection* base) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 85 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 86 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = g_error_new_literal (SYSTEM_NOT_SUPPORTED_EXCEPTION, SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION, "ExceptionResource.NotSupported_ReadOnlyCollection");
#line 86 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_inner_error_ = _tmp0_;
#line 86 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 86 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_clear_error (&_inner_error_);
#line 86 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return;
#line 484 "ReadOnlyCollection.c"
}


void system_collections_object_model_read_only_collection_Insert (SystemCollectionsObjectModelReadOnlyCollection* self, gint index, gconstpointer value) {
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 89 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_if_fail (self != NULL);
#line 90 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = g_error_new_literal (SYSTEM_NOT_SUPPORTED_EXCEPTION, SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION, "ExceptionResource.NotSupported_ReadOnlyCollection");
#line 90 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_inner_error_ = _tmp0_;
#line 90 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 90 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_clear_error (&_inner_error_);
#line 90 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return;
#line 503 "ReadOnlyCollection.c"
}


static gboolean system_collections_object_model_read_only_collection_real_Remove (SystemCollectionsGenericICollection* base, gconstpointer value) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	gboolean result = FALSE;
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 93 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 94 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = g_error_new_literal (SYSTEM_NOT_SUPPORTED_EXCEPTION, SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION, "ExceptionResource.NotSupported_ReadOnlyCollection");
#line 94 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_inner_error_ = _tmp0_;
#line 94 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 94 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_clear_error (&_inner_error_);
#line 94 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return FALSE;
#line 95 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = FALSE;
#line 95 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 93 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 530 "ReadOnlyCollection.c"
}


void system_collections_object_model_read_only_collection_RemoveAt (SystemCollectionsObjectModelReadOnlyCollection* self, gint index) {
	GError* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 98 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_if_fail (self != NULL);
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = g_error_new_literal (SYSTEM_NOT_SUPPORTED_EXCEPTION, SYSTEM_NOT_SUPPORTED_EXCEPTION_READ_ONLY_COLLECTION, "ExceptionResource.NotSupported_ReadOnlyCollection");
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_inner_error_ = _tmp0_;
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_clear_error (&_inner_error_);
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return;
#line 549 "ReadOnlyCollection.c"
}


static gint system_collections_object_model_read_only_collection_real_get_Count (SystemCollectionsGenericICollection* base) {
	gint result;
	SystemCollectionsObjectModelReadOnlyCollection* self;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 28 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = (SystemCollectionsObjectModelReadOnlyCollection*) base;
#line 28 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 28 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = system_collections_generic_icollection_get_Count (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollection));
#line 28 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = _tmp1_;
#line 28 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp2_;
#line 28 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 571 "ReadOnlyCollection.c"
}


gint system_collections_object_model_read_only_collection_get_size (SystemCollectionsObjectModelReadOnlyCollection* self) {
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_GET_CLASS (self)->get_size (self);
#line 580 "ReadOnlyCollection.c"
}


static gint system_collections_object_model_read_only_collection_real_get_size (SystemCollectionsObjectModelReadOnlyCollection* base) {
	gint result;
	SystemCollectionsObjectModelReadOnlyCollection* self;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = base;
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp1_ = system_collections_generic_icollection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, SystemCollectionsGenericICollection));
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp2_ = _tmp1_;
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp2_;
#line 32 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 602 "ReadOnlyCollection.c"
}


SystemCollectionsGenericIList* system_collections_object_model_read_only_collection_get_Items (SystemCollectionsObjectModelReadOnlyCollection* self) {
	SystemCollectionsGenericIList* result;
	SystemCollectionsGenericIList* _tmp0_ = NULL;
#line 68 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 69 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_tmp0_ = self->priv->list;
#line 69 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = _tmp0_;
#line 69 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 617 "ReadOnlyCollection.c"
}


gboolean system_collections_object_model_read_only_collection_get_IsReadOnly (SystemCollectionsObjectModelReadOnlyCollection* self) {
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_GET_CLASS (self)->get_IsReadOnly (self);
#line 626 "ReadOnlyCollection.c"
}


static gboolean system_collections_object_model_read_only_collection_real_get_IsReadOnly (SystemCollectionsObjectModelReadOnlyCollection* base) {
	gboolean result;
	SystemCollectionsObjectModelReadOnlyCollection* self;
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = base;
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = TRUE;
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 639 "ReadOnlyCollection.c"
}


gboolean system_collections_object_model_read_only_collection_get_IsSynchronized (SystemCollectionsObjectModelReadOnlyCollection* self) {
	gboolean result;
#line 103 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 103 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = FALSE;
#line 103 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 651 "ReadOnlyCollection.c"
}


gboolean system_collections_object_model_read_only_collection_get_IsFixedSize (SystemCollectionsObjectModelReadOnlyCollection* self) {
	gboolean result;
#line 121 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 121 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	result = TRUE;
#line 121 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return result;
#line 663 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_class_init (SystemCollectionsObjectModelReadOnlyCollectionClass * klass) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	system_collections_object_model_read_only_collection_parent_class = g_type_class_peek_parent (klass);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_type_class_add_private (klass, sizeof (SystemCollectionsObjectModelReadOnlyCollectionPrivate));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_CLASS (klass)->get_size = system_collections_object_model_read_only_collection_real_get_size;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_CLASS (klass)->get_IsReadOnly = system_collections_object_model_read_only_collection_real_get_IsReadOnly;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_system_collections_object_model_read_only_collection_get_property;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_system_collections_object_model_read_only_collection_set_property;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	G_OBJECT_CLASS (klass)->finalize = system_collections_object_model_read_only_collection_finalize;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_TYPE, g_param_spec_gtype ("t-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_DUP_FUNC, g_param_spec_pointer ("t-dup-func", "dup func", "dup func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_DESTROY_FUNC, g_param_spec_pointer ("t-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_COUNT, g_param_spec_int ("Count", "Count", "Count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_SIZE, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_ITEMS, g_param_spec_object ("Items", "Items", "Items", SYSTEM_COLLECTIONS_GENERIC_TYPE_ILIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_READ_ONLY, g_param_spec_boolean ("IsReadOnly", "IsReadOnly", "IsReadOnly", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_SYNCHRONIZED, g_param_spec_boolean ("IsSynchronized", "IsSynchronized", "IsSynchronized", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_FIXED_SIZE, g_param_spec_boolean ("IsFixedSize", "IsFixedSize", "IsFixedSize", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 700 "ReadOnlyCollection.c"
}


static GType system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_get_t_type (SystemCollectionsObjectModelReadOnlyCollection* self) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return self->priv->t_type;
#line 707 "ReadOnlyCollection.c"
}


static GBoxedCopyFunc system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_get_t_dup_func (SystemCollectionsObjectModelReadOnlyCollection* self) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return self->priv->t_dup_func;
#line 714 "ReadOnlyCollection.c"
}


static GDestroyNotify system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_get_t_destroy_func (SystemCollectionsObjectModelReadOnlyCollection* self) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	return self->priv->t_destroy_func;
#line 721 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_interface_init (SystemCollectionsGenericIEnumerableIface * iface) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_parent_iface = g_type_interface_peek_parent (iface);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->GetEnumerator = (SystemCollectionsGenericIEnumerator* (*)(SystemCollectionsGenericIEnumerable*)) system_collections_object_model_read_only_collection_real_GetEnumerator;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->iterator = (SystemCollectionsGenericIEnumerator* (*)(SystemCollectionsGenericIEnumerable*)) system_collections_object_model_read_only_collection_real_iterator;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_element_type = (GType (*)(SystemCollectionsGenericIEnumerable*)) system_collections_object_model_read_only_collection_real_get_element_type;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_t_type = (GType(*)(SystemCollectionsGenericIEnumerable*)) system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_get_t_type;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_t_dup_func = (GBoxedCopyFunc(*)(SystemCollectionsGenericIEnumerable*)) system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_get_t_dup_func;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_t_destroy_func = (GDestroyNotify(*)(SystemCollectionsGenericIEnumerable*)) system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_get_t_destroy_func;
#line 740 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_system_collections_generic_icollection_interface_init (SystemCollectionsGenericICollectionIface * iface) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	system_collections_object_model_read_only_collection_system_collections_generic_icollection_parent_iface = g_type_interface_peek_parent (iface);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->contains = (gboolean (*)(SystemCollectionsGenericICollection*, gconstpointer)) system_collections_object_model_read_only_collection_real_contains;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->Contains = (gboolean (*)(SystemCollectionsGenericICollection*, gconstpointer)) system_collections_object_model_read_only_collection_real_Contains;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->CopyTo = (void (*)(SystemCollectionsGenericICollection*, gpointer*, int, gint)) system_collections_object_model_read_only_collection_real_CopyTo;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->Add = (void (*)(SystemCollectionsGenericICollection*, gconstpointer)) system_collections_object_model_read_only_collection_real_Add;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->Clear = (void (*)(SystemCollectionsGenericICollection*)) system_collections_object_model_read_only_collection_real_Clear;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->Remove = (gboolean (*)(SystemCollectionsGenericICollection*, gconstpointer)) system_collections_object_model_read_only_collection_real_Remove;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_Count = system_collections_object_model_read_only_collection_real_get_Count;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_size = (gint (*) (SystemCollectionsGenericICollection *)) system_collections_object_model_read_only_collection_get_size;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	iface->get_IsReadOnly = (gboolean (*) (SystemCollectionsGenericICollection *)) system_collections_object_model_read_only_collection_get_IsReadOnly;
#line 765 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_system_collections_generic_iread_only_collection_interface_init (SystemCollectionsGenericIReadOnlyCollectionIface * iface) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	system_collections_object_model_read_only_collection_system_collections_generic_iread_only_collection_parent_iface = g_type_interface_peek_parent (iface);
#line 772 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_instance_init (SystemCollectionsObjectModelReadOnlyCollection * self) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self->priv = SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_GET_PRIVATE (self);
#line 779 "ReadOnlyCollection.c"
}


static void system_collections_object_model_read_only_collection_finalize (GObject* obj) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollection);
#line 20 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_g_object_unref0 (self->priv->list);
#line 21 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	_g_object_unref0 (self->priv->_syncRoot);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	G_OBJECT_CLASS (system_collections_object_model_read_only_collection_parent_class)->finalize (obj);
#line 793 "ReadOnlyCollection.c"
}


GType system_collections_object_model_read_only_collection_get_type (void) {
	static volatile gsize system_collections_object_model_read_only_collection_type_id__volatile = 0;
	if (g_once_init_enter (&system_collections_object_model_read_only_collection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemCollectionsObjectModelReadOnlyCollectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_collections_object_model_read_only_collection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemCollectionsObjectModelReadOnlyCollection), 0, (GInstanceInitFunc) system_collections_object_model_read_only_collection_instance_init, NULL };
		static const GInterfaceInfo system_collections_generic_ienumerable_info = { (GInterfaceInitFunc) system_collections_object_model_read_only_collection_system_collections_generic_ienumerable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_generic_icollection_info = { (GInterfaceInitFunc) system_collections_object_model_read_only_collection_system_collections_generic_icollection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_generic_iread_only_collection_info = { (GInterfaceInitFunc) system_collections_object_model_read_only_collection_system_collections_generic_iread_only_collection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_collections_object_model_read_only_collection_type_id;
		system_collections_object_model_read_only_collection_type_id = g_type_register_static (SYSTEM_LINQ_TYPE_ENUMERABLE, "SystemCollectionsObjectModelReadOnlyCollection", &g_define_type_info, 0);
		g_type_add_interface_static (system_collections_object_model_read_only_collection_type_id, SYSTEM_COLLECTIONS_GENERIC_TYPE_IENUMERABLE, &system_collections_generic_ienumerable_info);
		g_type_add_interface_static (system_collections_object_model_read_only_collection_type_id, SYSTEM_COLLECTIONS_GENERIC_TYPE_ICOLLECTION, &system_collections_generic_icollection_info);
		g_type_add_interface_static (system_collections_object_model_read_only_collection_type_id, SYSTEM_COLLECTIONS_GENERIC_TYPE_IREAD_ONLY_COLLECTION, &system_collections_generic_iread_only_collection_info);
		g_once_init_leave (&system_collections_object_model_read_only_collection_type_id__volatile, system_collections_object_model_read_only_collection_type_id);
	}
	return system_collections_object_model_read_only_collection_type_id__volatile;
}


static void _vala_system_collections_object_model_read_only_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollection);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	switch (property_id) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_COUNT:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		g_value_set_int (value, system_collections_generic_icollection_get_Count ((SystemCollectionsGenericICollection*) self));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_SIZE:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		g_value_set_int (value, system_collections_object_model_read_only_collection_get_size (self));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_ITEMS:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		g_value_set_object (value, system_collections_object_model_read_only_collection_get_Items (self));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_READ_ONLY:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		g_value_set_boolean (value, system_collections_object_model_read_only_collection_get_IsReadOnly (self));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_SYNCHRONIZED:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		g_value_set_boolean (value, system_collections_object_model_read_only_collection_get_IsSynchronized (self));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_IS_FIXED_SIZE:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		g_value_set_boolean (value, system_collections_object_model_read_only_collection_get_IsFixedSize (self));
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 856 "ReadOnlyCollection.c"
		default:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 862 "ReadOnlyCollection.c"
	}
}


static void _vala_system_collections_object_model_read_only_collection_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SystemCollectionsObjectModelReadOnlyCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_COLLECTIONS_OBJECT_MODEL_TYPE_READ_ONLY_COLLECTION, SystemCollectionsObjectModelReadOnlyCollection);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
	switch (property_id) {
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_TYPE:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		self->priv->t_type = g_value_get_gtype (value);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_DUP_FUNC:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		self->priv->t_dup_func = g_value_get_pointer (value);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		case SYSTEM_COLLECTIONS_OBJECT_MODEL_READ_ONLY_COLLECTION_T_DESTROY_FUNC:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		self->priv->t_destroy_func = g_value_get_pointer (value);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 890 "ReadOnlyCollection.c"
		default:
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "/home/developer/projects/Backup/LibDotNet/src/System/Collections/ObjectModel/ReadOnlyCollection.vala"
		break;
#line 896 "ReadOnlyCollection.c"
	}
}



