/* RegexGroupCollection.c generated by valac 0.26.2, the Vala compiler
 * generated from RegexGroupCollection.vala, do not modify */

/* Copyright (c) Microsoft. All rights reserved.*/
/* Licensed under the MIT license. See LICENSE file in the project root for full license information.*/
/* The GroupCollection lists the captured Capture numbers*/
/* contained in a compiled Regex.*/

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define SYSTEM_COLLECTIONS_TYPE_IENUMERABLE (system_collections_ienumerable_get_type ())
#define SYSTEM_COLLECTIONS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, SystemCollectionsIEnumerable))
#define SYSTEM_COLLECTIONS_IS_IENUMERABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE))
#define SYSTEM_COLLECTIONS_IENUMERABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, SystemCollectionsIEnumerableIface))

typedef struct _SystemCollectionsIEnumerable SystemCollectionsIEnumerable;
typedef struct _SystemCollectionsIEnumerableIface SystemCollectionsIEnumerableIface;

#define SYSTEM_COLLECTIONS_TYPE_IENUMERATOR (system_collections_ienumerator_get_type ())
#define SYSTEM_COLLECTIONS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, SystemCollectionsIEnumerator))
#define SYSTEM_COLLECTIONS_IS_IENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR))
#define SYSTEM_COLLECTIONS_IENUMERATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, SystemCollectionsIEnumeratorIface))

typedef struct _SystemCollectionsIEnumerator SystemCollectionsIEnumerator;
typedef struct _SystemCollectionsIEnumeratorIface SystemCollectionsIEnumeratorIface;

#define SYSTEM_COLLECTIONS_TYPE_ICOLLECTION (system_collections_icollection_get_type ())
#define SYSTEM_COLLECTIONS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, SystemCollectionsICollection))
#define SYSTEM_COLLECTIONS_IS_ICOLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION))
#define SYSTEM_COLLECTIONS_ICOLLECTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, SystemCollectionsICollectionIface))

typedef struct _SystemCollectionsICollection SystemCollectionsICollection;
typedef struct _SystemCollectionsICollectionIface SystemCollectionsICollectionIface;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION (system_text_regular_expressions_group_collection_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollection))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollectionClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollectionClass))

typedef struct _SystemTextRegularExpressionsGroupCollection SystemTextRegularExpressionsGroupCollection;
typedef struct _SystemTextRegularExpressionsGroupCollectionClass SystemTextRegularExpressionsGroupCollectionClass;
typedef struct _SystemTextRegularExpressionsGroupCollectionPrivate SystemTextRegularExpressionsGroupCollectionPrivate;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE (system_text_regular_expressions_capture_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE, SystemTextRegularExpressionsCapture))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE, SystemTextRegularExpressionsCaptureClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE, SystemTextRegularExpressionsCaptureClass))

typedef struct _SystemTextRegularExpressionsCapture SystemTextRegularExpressionsCapture;
typedef struct _SystemTextRegularExpressionsCaptureClass SystemTextRegularExpressionsCaptureClass;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP (system_text_regular_expressions_group_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, SystemTextRegularExpressionsGroup))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, SystemTextRegularExpressionsGroupClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, SystemTextRegularExpressionsGroupClass))

typedef struct _SystemTextRegularExpressionsGroup SystemTextRegularExpressionsGroup;
typedef struct _SystemTextRegularExpressionsGroupClass SystemTextRegularExpressionsGroupClass;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH (system_text_regular_expressions_match_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatch))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatchClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatchClass))

typedef struct _SystemTextRegularExpressionsMatch SystemTextRegularExpressionsMatch;
typedef struct _SystemTextRegularExpressionsMatchClass SystemTextRegularExpressionsMatchClass;
#define _system_text_regular_expressions_capture_unref0(var) ((var == NULL) ? NULL : (var = (system_text_regular_expressions_capture_unref (var), NULL)))

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR (system_text_regular_expressions_group_collection_enumerator_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumerator))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_ENUMERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumeratorClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_IS_ENUMERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_IS_ENUMERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_ENUMERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumeratorClass))

typedef struct _SystemTextRegularExpressionsGroupCollectionEnumerator SystemTextRegularExpressionsGroupCollectionEnumerator;
typedef struct _SystemTextRegularExpressionsGroupCollectionEnumeratorClass SystemTextRegularExpressionsGroupCollectionEnumeratorClass;
typedef struct _SystemTextRegularExpressionsCapturePrivate SystemTextRegularExpressionsCapturePrivate;
typedef struct _SystemTextRegularExpressionsGroupPrivate SystemTextRegularExpressionsGroupPrivate;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION (system_text_regular_expressions_capture_collection_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION, SystemTextRegularExpressionsCaptureCollection))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION, SystemTextRegularExpressionsCaptureCollectionClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION, SystemTextRegularExpressionsCaptureCollectionClass))

typedef struct _SystemTextRegularExpressionsCaptureCollection SystemTextRegularExpressionsCaptureCollection;
typedef struct _SystemTextRegularExpressionsCaptureCollectionClass SystemTextRegularExpressionsCaptureCollectionClass;
typedef struct _SystemTextRegularExpressionsMatchPrivate SystemTextRegularExpressionsMatchPrivate;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX (system_text_regular_expressions_static_regex_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_STATIC_REGEX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX, SystemTextRegularExpressionsStaticRegex))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_STATIC_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX, SystemTextRegularExpressionsStaticRegexClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_STATIC_REGEX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_STATIC_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_STATIC_REGEX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX, SystemTextRegularExpressionsStaticRegexClass))

typedef struct _SystemTextRegularExpressionsStaticRegex SystemTextRegularExpressionsStaticRegex;
typedef struct _SystemTextRegularExpressionsStaticRegexClass SystemTextRegularExpressionsStaticRegexClass;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX (system_text_regular_expressions_regex_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX, SystemTextRegularExpressionsRegex))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX, SystemTextRegularExpressionsRegexClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_REGEX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX, SystemTextRegularExpressionsRegexClass))

typedef struct _SystemTextRegularExpressionsRegex SystemTextRegularExpressionsRegex;
typedef struct _SystemTextRegularExpressionsRegexClass SystemTextRegularExpressionsRegexClass;
typedef struct _SystemTextRegularExpressionsGroupCollectionEnumeratorPrivate SystemTextRegularExpressionsGroupCollectionEnumeratorPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _SystemCollectionsIEnumeratorIface {
	GTypeInterface parent_iface;
	gboolean (*MoveNext) (SystemCollectionsIEnumerator* self);
	gboolean (*next) (SystemCollectionsIEnumerator* self);
	GObject* (*get) (SystemCollectionsIEnumerator* self);
	void (*Reset) (SystemCollectionsIEnumerator* self);
	GObject* (*get__currentElement) (SystemCollectionsIEnumerator* self);
	void (*set__currentElement) (SystemCollectionsIEnumerator* self, GObject* value);
	GeeIterator* (*get__iterator) (SystemCollectionsIEnumerator* self);
	void (*set__iterator) (SystemCollectionsIEnumerator* self, GeeIterator* value);
	GObject* (*get_Current) (SystemCollectionsIEnumerator* self);
};

struct _SystemCollectionsIEnumerableIface {
	GTypeInterface parent_iface;
	SystemCollectionsIEnumerator* (*GetEnumerator) (SystemCollectionsIEnumerable* self);
};

struct _SystemCollectionsICollectionIface {
	GTypeInterface parent_iface;
	void (*CopyTo) (SystemCollectionsICollection* self, GArray* array, gint arrayIndex);
	SystemCollectionsIEnumerator* (*iterator) (SystemCollectionsICollection* self);
	gint (*get_Count) (SystemCollectionsICollection* self);
	GObject* (*get_SyncRoot) (SystemCollectionsICollection* self);
	gboolean (*get_IsSynchronized) (SystemCollectionsICollection* self);
};

struct _SystemTextRegularExpressionsGroupCollection {
	GObject parent_instance;
	SystemTextRegularExpressionsGroupCollectionPrivate * priv;
};

struct _SystemTextRegularExpressionsGroupCollectionClass {
	GObjectClass parent_class;
};

struct _SystemTextRegularExpressionsGroupCollectionPrivate {
	SystemTextRegularExpressionsMatch* _match;
	SystemTextRegularExpressionsGroup** _groups;
	gint _groups_length1;
	gint __groups_size_;
};

struct _SystemTextRegularExpressionsCapture {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SystemTextRegularExpressionsCapturePrivate * priv;
	gchar* _text;
	gint _index;
	gint _length;
};

struct _SystemTextRegularExpressionsCaptureClass {
	GTypeClass parent_class;
	void (*finalize) (SystemTextRegularExpressionsCapture *self);
};

struct _SystemTextRegularExpressionsGroup {
	SystemTextRegularExpressionsCapture parent_instance;
	SystemTextRegularExpressionsGroupPrivate * priv;
	gint _capcount;
	SystemTextRegularExpressionsCaptureCollection* _capcoll;
};

struct _SystemTextRegularExpressionsGroupClass {
	SystemTextRegularExpressionsCaptureClass parent_class;
};

struct _SystemTextRegularExpressionsMatch {
	SystemTextRegularExpressionsGroup parent_instance;
	SystemTextRegularExpressionsMatchPrivate * priv;
	SystemTextRegularExpressionsGroupCollection* _groupcoll;
	GMatchInfo* _matchinfo;
};

struct _SystemTextRegularExpressionsMatchClass {
	SystemTextRegularExpressionsGroupClass parent_class;
	void (*Reset) (SystemTextRegularExpressionsMatch* self, SystemTextRegularExpressionsRegex* regex, const gchar* text, gint textbeg, gint textend, gint textstart);
	gchar* (*Result) (SystemTextRegularExpressionsMatch* self, const gchar* replacement);
	SystemTextRegularExpressionsGroupCollection* (*get_Groups) (SystemTextRegularExpressionsMatch* self);
};

struct _SystemTextRegularExpressionsGroupCollectionEnumerator {
	GObject parent_instance;
	SystemTextRegularExpressionsGroupCollectionEnumeratorPrivate * priv;
};

struct _SystemTextRegularExpressionsGroupCollectionEnumeratorClass {
	GObjectClass parent_class;
};

struct _SystemTextRegularExpressionsGroupCollectionEnumeratorPrivate {
	SystemTextRegularExpressionsGroupCollection* _collection;
	gint _index;
	GObject* __currentElement;
	GeeIterator* __iterator;
};


static gpointer system_text_regular_expressions_group_collection_parent_class = NULL;
static gpointer system_text_regular_expressions_group_collection_enumerator_parent_class = NULL;
static SystemCollectionsIEnumeratorIface* system_text_regular_expressions_group_collection_enumerator_system_collections_ienumerator_parent_iface = NULL;
static SystemCollectionsICollectionIface* system_text_regular_expressions_group_collection_system_collections_icollection_parent_iface = NULL;
static SystemCollectionsIEnumerableIface* system_text_regular_expressions_group_collection_system_collections_ienumerable_parent_iface = NULL;

GType system_collections_ienumerator_get_type (void) G_GNUC_CONST;
GType system_collections_ienumerable_get_type (void) G_GNUC_CONST;
GType system_collections_icollection_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_group_collection_get_type (void) G_GNUC_CONST;
gpointer system_text_regular_expressions_capture_ref (gpointer instance);
void system_text_regular_expressions_capture_unref (gpointer instance);
GParamSpec* system_text_regular_expressions_param_spec_capture (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_text_regular_expressions_value_set_capture (GValue* value, gpointer v_object);
void system_text_regular_expressions_value_take_capture (GValue* value, gpointer v_object);
gpointer system_text_regular_expressions_value_get_capture (const GValue* value);
GType system_text_regular_expressions_capture_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_group_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_match_get_type (void) G_GNUC_CONST;
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollectionPrivate))
enum  {
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_DUMMY_PROPERTY,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_COUNT
};
SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_group_collection_new (SystemTextRegularExpressionsMatch* match);
SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_group_collection_construct (GType object_type, SystemTextRegularExpressionsMatch* match);
SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_collection_get (SystemTextRegularExpressionsGroupCollection* self, gint groupnum);
static SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_collection_GetGroup (SystemTextRegularExpressionsGroupCollection* self, gint groupnum);
static SystemCollectionsIEnumerator* system_text_regular_expressions_group_collection_real_GetEnumerator (SystemCollectionsIEnumerable* base);
SystemTextRegularExpressionsGroupCollectionEnumerator* system_text_regular_expressions_group_collection_enumerator_new (SystemTextRegularExpressionsGroupCollection* collection);
SystemTextRegularExpressionsGroupCollectionEnumerator* system_text_regular_expressions_group_collection_enumerator_construct (GType object_type, SystemTextRegularExpressionsGroupCollection* collection);
GType system_text_regular_expressions_group_collection_enumerator_get_type (void) G_GNUC_CONST;
SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_new (void);
SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_construct (GType object_type);
static SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_collection_GetGroupImpl (SystemTextRegularExpressionsGroupCollection* self, gint groupnum);
GType system_text_regular_expressions_capture_collection_get_type (void) G_GNUC_CONST;
gpointer system_text_regular_expressions_static_regex_ref (gpointer instance);
void system_text_regular_expressions_static_regex_unref (gpointer instance);
GParamSpec* system_text_regular_expressions_param_spec_static_regex (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_text_regular_expressions_value_set_static_regex (GValue* value, gpointer v_object);
void system_text_regular_expressions_value_take_static_regex (GValue* value, gpointer v_object);
gpointer system_text_regular_expressions_value_get_static_regex (const GValue* value);
GType system_text_regular_expressions_static_regex_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_regex_get_type (void) G_GNUC_CONST;
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_ENUMERATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumeratorPrivate))
enum  {
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_ENUMERATOR_DUMMY_PROPERTY
};
static gboolean system_text_regular_expressions_group_collection_enumerator_real_MoveNext (SystemCollectionsIEnumerator* base);
gint system_collections_icollection_get_Count (SystemCollectionsICollection* self);
static void system_text_regular_expressions_group_collection_enumerator_real_Reset (SystemCollectionsIEnumerator* base);
GObject* system_collections_ienumerator_get__currentElement (SystemCollectionsIEnumerator* self);
static void system_text_regular_expressions_group_collection_enumerator_finalize (GObject* obj);
static void _vala_system_text_regular_expressions_group_collection_enumerator_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_system_text_regular_expressions_group_collection_enumerator_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void system_text_regular_expressions_group_collection_finalize (GObject* obj);
static void _vala_system_text_regular_expressions_group_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _system_text_regular_expressions_capture_ref0 (gpointer self) {
	return self ? system_text_regular_expressions_capture_ref (self) : NULL;
}


SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_group_collection_construct (GType object_type, SystemTextRegularExpressionsMatch* match) {
	SystemTextRegularExpressionsGroupCollection * self = NULL;
	SystemTextRegularExpressionsMatch* _tmp0_ = NULL;
	SystemTextRegularExpressionsMatch* _tmp1_ = NULL;
	g_return_val_if_fail (match != NULL, NULL);
	self = (SystemTextRegularExpressionsGroupCollection*) g_object_new (object_type, NULL);
	_tmp0_ = match;
	_tmp1_ = _system_text_regular_expressions_capture_ref0 (_tmp0_);
	_system_text_regular_expressions_capture_unref0 (self->priv->_match);
	self->priv->_match = _tmp1_;
	return self;
}


SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_group_collection_new (SystemTextRegularExpressionsMatch* match) {
	return system_text_regular_expressions_group_collection_construct (SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, match);
}


SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_collection_get (SystemTextRegularExpressionsGroupCollection* self, gint groupnum) {
	SystemTextRegularExpressionsGroup* result = NULL;
	gint _tmp0_ = 0;
	SystemTextRegularExpressionsGroup* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = groupnum;
	_tmp1_ = system_text_regular_expressions_group_collection_GetGroup (self, _tmp0_);
	result = _tmp1_;
	return result;
}


static SystemCollectionsIEnumerator* system_text_regular_expressions_group_collection_real_GetEnumerator (SystemCollectionsIEnumerable* base) {
	SystemTextRegularExpressionsGroupCollection * self;
	SystemCollectionsIEnumerator* result = NULL;
	SystemTextRegularExpressionsGroupCollectionEnumerator* _tmp0_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollection*) base;
	_tmp0_ = system_text_regular_expressions_group_collection_enumerator_new (self);
	result = (SystemCollectionsIEnumerator*) _tmp0_;
	return result;
}


static SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_collection_GetGroup (SystemTextRegularExpressionsGroupCollection* self, gint groupnum) {
	SystemTextRegularExpressionsGroup* result = NULL;
	SystemTextRegularExpressionsGroup* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = system_text_regular_expressions_group_new ();
	result = _tmp0_;
	return result;
}


static SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_collection_GetGroupImpl (SystemTextRegularExpressionsGroupCollection* self, gint groupnum) {
	SystemTextRegularExpressionsGroup* result = NULL;
	SystemTextRegularExpressionsGroup** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	SystemTextRegularExpressionsGroup* _tmp2_ = NULL;
	SystemTextRegularExpressionsGroup* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_groups;
	_tmp0__length1 = self->priv->_groups_length1;
	_tmp1_ = groupnum;
	_tmp2_ = _tmp0_[_tmp1_ - 1];
	_tmp3_ = _system_text_regular_expressions_capture_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


static gint system_text_regular_expressions_group_collection_real_get_Count (SystemCollectionsICollection* base) {
	gint result;
	SystemTextRegularExpressionsGroupCollection* self;
	SystemTextRegularExpressionsMatch* _tmp0_ = NULL;
	GMatchInfo* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (SystemTextRegularExpressionsGroupCollection*) base;
	_tmp0_ = self->priv->_match;
	_tmp1_ = _tmp0_->_matchinfo;
	_tmp2_ = g_match_info_get_match_count (_tmp1_);
	result = _tmp2_;
	return result;
}


static gboolean system_text_regular_expressions_group_collection_real_get_IsSynchronized (SystemCollectionsICollection* base) {
	gboolean result;
	SystemTextRegularExpressionsGroupCollection* self;
	self = (SystemTextRegularExpressionsGroupCollection*) base;
	result = FALSE;
	return result;
}


static GObject* system_text_regular_expressions_group_collection_real_get_SyncRoot (SystemCollectionsICollection* base) {
	GObject* result;
	SystemTextRegularExpressionsGroupCollection* self;
	SystemTextRegularExpressionsMatch* _tmp0_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollection*) base;
	_tmp0_ = self->priv->_match;
	result = G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, G_TYPE_OBJECT) ? ((GObject*) _tmp0_) : NULL;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SystemTextRegularExpressionsGroupCollectionEnumerator* system_text_regular_expressions_group_collection_enumerator_construct (GType object_type, SystemTextRegularExpressionsGroupCollection* collection) {
	SystemTextRegularExpressionsGroupCollectionEnumerator * self = NULL;
	SystemTextRegularExpressionsGroupCollection* _tmp0_ = NULL;
	SystemTextRegularExpressionsGroupCollection* _tmp1_ = NULL;
	g_return_val_if_fail (collection != NULL, NULL);
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) g_object_new (object_type, NULL);
	_tmp0_ = collection;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_collection);
	self->priv->_collection = _tmp1_;
	self->priv->_index = -1;
	return self;
}


SystemTextRegularExpressionsGroupCollectionEnumerator* system_text_regular_expressions_group_collection_enumerator_new (SystemTextRegularExpressionsGroupCollection* collection) {
	return system_text_regular_expressions_group_collection_enumerator_construct (SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, collection);
}


static gboolean system_text_regular_expressions_group_collection_enumerator_real_MoveNext (SystemCollectionsIEnumerator* base) {
	SystemTextRegularExpressionsGroupCollectionEnumerator * self;
	gboolean result = FALSE;
	gint size = 0;
	SystemTextRegularExpressionsGroupCollection* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	_tmp0_ = self->priv->_collection;
	_tmp1_ = system_collections_icollection_get_Count ((SystemCollectionsICollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	size = _tmp2_;
	_tmp3_ = self->priv->_index;
	_tmp4_ = size;
	if (_tmp3_ >= _tmp4_) {
		result = FALSE;
		return result;
	}
	_tmp5_ = self->priv->_index;
	self->priv->_index = _tmp5_ + 1;
	_tmp6_ = self->priv->_index;
	_tmp7_ = size;
	result = _tmp6_ < _tmp7_;
	return result;
}


static void system_text_regular_expressions_group_collection_enumerator_real_Reset (SystemCollectionsIEnumerator* base) {
	SystemTextRegularExpressionsGroupCollectionEnumerator * self;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	self->priv->_index = -1;
}


static GObject* system_text_regular_expressions_group_collection_enumerator_real_get__currentElement (SystemCollectionsIEnumerator* base) {
	GObject* result;
	SystemTextRegularExpressionsGroupCollectionEnumerator* self;
	GObject* _tmp0_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	_tmp0_ = self->priv->__currentElement;
	result = _tmp0_;
	return result;
}


static void system_text_regular_expressions_group_collection_enumerator_real_set__currentElement (SystemCollectionsIEnumerator* base, GObject* value) {
	SystemTextRegularExpressionsGroupCollectionEnumerator* self;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->__currentElement);
	self->priv->__currentElement = _tmp1_;
}


static GeeIterator* system_text_regular_expressions_group_collection_enumerator_real_get__iterator (SystemCollectionsIEnumerator* base) {
	GeeIterator* result;
	SystemTextRegularExpressionsGroupCollectionEnumerator* self;
	GeeIterator* _tmp0_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	_tmp0_ = self->priv->__iterator;
	result = _tmp0_;
	return result;
}


static void system_text_regular_expressions_group_collection_enumerator_real_set__iterator (SystemCollectionsIEnumerator* base, GeeIterator* value) {
	SystemTextRegularExpressionsGroupCollectionEnumerator* self;
	GeeIterator* _tmp0_ = NULL;
	GeeIterator* _tmp1_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->__iterator);
	self->priv->__iterator = _tmp1_;
}


static GObject* system_text_regular_expressions_group_collection_enumerator_real_get_Current (SystemCollectionsIEnumerator* base) {
	GObject* result;
	SystemTextRegularExpressionsGroupCollectionEnumerator* self;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	self = (SystemTextRegularExpressionsGroupCollectionEnumerator*) base;
	_tmp0_ = system_collections_ienumerator_get__currentElement ((SystemCollectionsIEnumerator*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	result = _tmp2_;
	return result;
}


static void system_text_regular_expressions_group_collection_enumerator_class_init (SystemTextRegularExpressionsGroupCollectionEnumeratorClass * klass) {
	system_text_regular_expressions_group_collection_enumerator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemTextRegularExpressionsGroupCollectionEnumeratorPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_system_text_regular_expressions_group_collection_enumerator_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_system_text_regular_expressions_group_collection_enumerator_set_property;
	G_OBJECT_CLASS (klass)->finalize = system_text_regular_expressions_group_collection_enumerator_finalize;
}


static void system_text_regular_expressions_group_collection_enumerator_system_collections_ienumerator_interface_init (SystemCollectionsIEnumeratorIface * iface) {
	system_text_regular_expressions_group_collection_enumerator_system_collections_ienumerator_parent_iface = g_type_interface_peek_parent (iface);
	iface->MoveNext = (gboolean (*)(SystemCollectionsIEnumerator*)) system_text_regular_expressions_group_collection_enumerator_real_MoveNext;
	iface->Reset = (void (*)(SystemCollectionsIEnumerator*)) system_text_regular_expressions_group_collection_enumerator_real_Reset;
	iface->get__currentElement = system_text_regular_expressions_group_collection_enumerator_real_get__currentElement;
	iface->set__currentElement = system_text_regular_expressions_group_collection_enumerator_real_set__currentElement;
	iface->get__iterator = system_text_regular_expressions_group_collection_enumerator_real_get__iterator;
	iface->set__iterator = system_text_regular_expressions_group_collection_enumerator_real_set__iterator;
	iface->get_Current = system_text_regular_expressions_group_collection_enumerator_real_get_Current;
}


static void system_text_regular_expressions_group_collection_enumerator_instance_init (SystemTextRegularExpressionsGroupCollectionEnumerator * self) {
	self->priv = SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_ENUMERATOR_GET_PRIVATE (self);
}


static void system_text_regular_expressions_group_collection_enumerator_finalize (GObject* obj) {
	SystemTextRegularExpressionsGroupCollectionEnumerator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumerator);
	_g_object_unref0 (self->priv->_collection);
	_g_object_unref0 (self->priv->__currentElement);
	_g_object_unref0 (self->priv->__iterator);
	G_OBJECT_CLASS (system_text_regular_expressions_group_collection_enumerator_parent_class)->finalize (obj);
}


GType system_text_regular_expressions_group_collection_enumerator_get_type (void) {
	static volatile gsize system_text_regular_expressions_group_collection_enumerator_type_id__volatile = 0;
	if (g_once_init_enter (&system_text_regular_expressions_group_collection_enumerator_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemTextRegularExpressionsGroupCollectionEnumeratorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_text_regular_expressions_group_collection_enumerator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemTextRegularExpressionsGroupCollectionEnumerator), 0, (GInstanceInitFunc) system_text_regular_expressions_group_collection_enumerator_instance_init, NULL };
		static const GInterfaceInfo system_collections_ienumerator_info = { (GInterfaceInitFunc) system_text_regular_expressions_group_collection_enumerator_system_collections_ienumerator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_text_regular_expressions_group_collection_enumerator_type_id;
		system_text_regular_expressions_group_collection_enumerator_type_id = g_type_register_static (G_TYPE_OBJECT, "SystemTextRegularExpressionsGroupCollectionEnumerator", &g_define_type_info, 0);
		g_type_add_interface_static (system_text_regular_expressions_group_collection_enumerator_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERATOR, &system_collections_ienumerator_info);
		g_once_init_leave (&system_text_regular_expressions_group_collection_enumerator_type_id__volatile, system_text_regular_expressions_group_collection_enumerator_type_id);
	}
	return system_text_regular_expressions_group_collection_enumerator_type_id__volatile;
}


static void _vala_system_text_regular_expressions_group_collection_enumerator_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemTextRegularExpressionsGroupCollectionEnumerator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumerator);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_system_text_regular_expressions_group_collection_enumerator_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SystemTextRegularExpressionsGroupCollectionEnumerator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_TYPE_ENUMERATOR, SystemTextRegularExpressionsGroupCollectionEnumerator);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void system_text_regular_expressions_group_collection_class_init (SystemTextRegularExpressionsGroupCollectionClass * klass) {
	system_text_regular_expressions_group_collection_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SystemTextRegularExpressionsGroupCollectionPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_system_text_regular_expressions_group_collection_get_property;
	G_OBJECT_CLASS (klass)->finalize = system_text_regular_expressions_group_collection_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_COUNT, g_param_spec_int ("Count", "Count", "Count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void system_text_regular_expressions_group_collection_system_collections_icollection_interface_init (SystemCollectionsICollectionIface * iface) {
	system_text_regular_expressions_group_collection_system_collections_icollection_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_Count = system_text_regular_expressions_group_collection_real_get_Count;
	iface->get_IsSynchronized = system_text_regular_expressions_group_collection_real_get_IsSynchronized;
	iface->get_SyncRoot = system_text_regular_expressions_group_collection_real_get_SyncRoot;
}


static void system_text_regular_expressions_group_collection_system_collections_ienumerable_interface_init (SystemCollectionsIEnumerableIface * iface) {
	system_text_regular_expressions_group_collection_system_collections_ienumerable_parent_iface = g_type_interface_peek_parent (iface);
	iface->GetEnumerator = (SystemCollectionsIEnumerator* (*)(SystemCollectionsIEnumerable*)) system_text_regular_expressions_group_collection_real_GetEnumerator;
}


static void system_text_regular_expressions_group_collection_instance_init (SystemTextRegularExpressionsGroupCollection * self) {
	self->priv = SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_GET_PRIVATE (self);
}


static void system_text_regular_expressions_group_collection_finalize (GObject* obj) {
	SystemTextRegularExpressionsGroupCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollection);
	_system_text_regular_expressions_capture_unref0 (self->priv->_match);
	self->priv->_groups = (_vala_array_free (self->priv->_groups, self->priv->_groups_length1, (GDestroyNotify) system_text_regular_expressions_capture_unref), NULL);
	G_OBJECT_CLASS (system_text_regular_expressions_group_collection_parent_class)->finalize (obj);
}


GType system_text_regular_expressions_group_collection_get_type (void) {
	static volatile gsize system_text_regular_expressions_group_collection_type_id__volatile = 0;
	if (g_once_init_enter (&system_text_regular_expressions_group_collection_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemTextRegularExpressionsGroupCollectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_text_regular_expressions_group_collection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemTextRegularExpressionsGroupCollection), 0, (GInstanceInitFunc) system_text_regular_expressions_group_collection_instance_init, NULL };
		static const GInterfaceInfo system_collections_icollection_info = { (GInterfaceInitFunc) system_text_regular_expressions_group_collection_system_collections_icollection_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo system_collections_ienumerable_info = { (GInterfaceInitFunc) system_text_regular_expressions_group_collection_system_collections_ienumerable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType system_text_regular_expressions_group_collection_type_id;
		system_text_regular_expressions_group_collection_type_id = g_type_register_static (G_TYPE_OBJECT, "SystemTextRegularExpressionsGroupCollection", &g_define_type_info, 0);
		g_type_add_interface_static (system_text_regular_expressions_group_collection_type_id, SYSTEM_COLLECTIONS_TYPE_ICOLLECTION, &system_collections_icollection_info);
		g_type_add_interface_static (system_text_regular_expressions_group_collection_type_id, SYSTEM_COLLECTIONS_TYPE_IENUMERABLE, &system_collections_ienumerable_info);
		g_once_init_leave (&system_text_regular_expressions_group_collection_type_id__volatile, system_text_regular_expressions_group_collection_type_id);
	}
	return system_text_regular_expressions_group_collection_type_id__volatile;
}


static void _vala_system_text_regular_expressions_group_collection_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SystemTextRegularExpressionsGroupCollection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollection);
	switch (property_id) {
		case SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_COUNT:
		g_value_set_int (value, system_collections_icollection_get_Count ((SystemCollectionsICollection*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



