/* RegexMatch.c generated by valac 0.29.2.5-8632-dirty, the Vala compiler
 * generated from RegexMatch.vala, do not modify */

/* Copyright (c) Microsoft. All rights reserved.*/
/* Licensed under the MIT license. See LICENSE file in the project root for full license information.*/
/* Match is the result class for a regex search.*/
/* It returns the location, length, and substring for*/
/* the entire match as well as every captured group.*/
/* Match is also used during the search to keep track of each capture for each group.  This is*/
/* done using the "_matches" array.  _matches[x] represents an array of the captures for group x.*/
/* This array consists of start and length pairs, and may have empty entries at the end.  _matchcount[x]*/
/* stores how many captures a group has.  Note that _matchcount[x]*2 is the length of all the valid*/
/* values in _matches.  _matchcount[x]*2-2 is the Start of the last capture, and _matchcount[x]*2-1 is the*/
/* Length of the last capture*/
/**/
/* For example, if group 2 has one capture starting at position 4 with length 6,*/
/* _matchcount[2] == 1*/
/* _matches[2][0] == 4*/
/* _matches[2][1] == 6*/
/**/
/* Values in the _matches array can also be negative.  This happens when using the balanced match*/
/* construct, "(?<start-end>...)".  When the "end" group matches, a capture is added for both the "start"*/
/* and "end" groups.  The capture added for "start" receives the negative values, and these values point to*/
/* the next capture to be balanced.  They do NOT point to the capture that "end" just balanced out.  The negative*/
/* values are indices into the _matches array transformed by the formula -3-x.  This formula also untransforms.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE (system_text_regular_expressions_capture_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE, SystemTextRegularExpressionsCapture))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE, SystemTextRegularExpressionsCaptureClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE, SystemTextRegularExpressionsCaptureClass))

typedef struct _SystemTextRegularExpressionsCapture SystemTextRegularExpressionsCapture;
typedef struct _SystemTextRegularExpressionsCaptureClass SystemTextRegularExpressionsCaptureClass;
typedef struct _SystemTextRegularExpressionsCapturePrivate SystemTextRegularExpressionsCapturePrivate;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP (system_text_regular_expressions_group_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, SystemTextRegularExpressionsGroup))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, SystemTextRegularExpressionsGroupClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, SystemTextRegularExpressionsGroupClass))

typedef struct _SystemTextRegularExpressionsGroup SystemTextRegularExpressionsGroup;
typedef struct _SystemTextRegularExpressionsGroupClass SystemTextRegularExpressionsGroupClass;
typedef struct _SystemTextRegularExpressionsGroupPrivate SystemTextRegularExpressionsGroupPrivate;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION (system_text_regular_expressions_capture_collection_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION, SystemTextRegularExpressionsCaptureCollection))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION, SystemTextRegularExpressionsCaptureCollectionClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_CAPTURE_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_CAPTURE_COLLECTION, SystemTextRegularExpressionsCaptureCollectionClass))

typedef struct _SystemTextRegularExpressionsCaptureCollection SystemTextRegularExpressionsCaptureCollection;
typedef struct _SystemTextRegularExpressionsCaptureCollectionClass SystemTextRegularExpressionsCaptureCollectionClass;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH (system_text_regular_expressions_match_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatch))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatchClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_MATCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatchClass))

typedef struct _SystemTextRegularExpressionsMatch SystemTextRegularExpressionsMatch;
typedef struct _SystemTextRegularExpressionsMatchClass SystemTextRegularExpressionsMatchClass;
typedef struct _SystemTextRegularExpressionsMatchPrivate SystemTextRegularExpressionsMatchPrivate;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX (system_text_regular_expressions_static_regex_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_STATIC_REGEX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX, SystemTextRegularExpressionsStaticRegex))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_STATIC_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX, SystemTextRegularExpressionsStaticRegexClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_STATIC_REGEX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_STATIC_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_STATIC_REGEX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_STATIC_REGEX, SystemTextRegularExpressionsStaticRegexClass))

typedef struct _SystemTextRegularExpressionsStaticRegex SystemTextRegularExpressionsStaticRegex;
typedef struct _SystemTextRegularExpressionsStaticRegexClass SystemTextRegularExpressionsStaticRegexClass;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX (system_text_regular_expressions_regex_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX, SystemTextRegularExpressionsRegex))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX, SystemTextRegularExpressionsRegexClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_REGEX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_REGEX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX, SystemTextRegularExpressionsRegexClass))

typedef struct _SystemTextRegularExpressionsRegex SystemTextRegularExpressionsRegex;
typedef struct _SystemTextRegularExpressionsRegexClass SystemTextRegularExpressionsRegexClass;

#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION (system_text_regular_expressions_group_collection_get_type ())
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollection))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollectionClass))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_IS_GROUP_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION))
#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_GROUP_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP_COLLECTION, SystemTextRegularExpressionsGroupCollectionClass))

typedef struct _SystemTextRegularExpressionsGroupCollection SystemTextRegularExpressionsGroupCollection;
typedef struct _SystemTextRegularExpressionsGroupCollectionClass SystemTextRegularExpressionsGroupCollectionClass;
#define _system_text_regular_expressions_group_collection_unref0(var) ((var == NULL) ? NULL : (var = (system_text_regular_expressions_group_collection_unref (var), NULL)))

struct _SystemTextRegularExpressionsCapture {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SystemTextRegularExpressionsCapturePrivate * priv;
	gchar* _text;
	gint _index;
	gint _length;
};

struct _SystemTextRegularExpressionsCaptureClass {
	GTypeClass parent_class;
	void (*finalize) (SystemTextRegularExpressionsCapture *self);
};

struct _SystemTextRegularExpressionsGroup {
	SystemTextRegularExpressionsCapture parent_instance;
	SystemTextRegularExpressionsGroupPrivate * priv;
	gint _capcount;
	SystemTextRegularExpressionsCaptureCollection* _capcoll;
};

struct _SystemTextRegularExpressionsGroupClass {
	SystemTextRegularExpressionsCaptureClass parent_class;
};

struct _SystemTextRegularExpressionsMatch {
	SystemTextRegularExpressionsGroup parent_instance;
	SystemTextRegularExpressionsMatchPrivate * priv;
	SystemTextRegularExpressionsGroupCollection* _groupcoll;
	GMatchInfo* _matchinfo;
};

struct _SystemTextRegularExpressionsMatchClass {
	SystemTextRegularExpressionsGroupClass parent_class;
	void (*Reset) (SystemTextRegularExpressionsMatch* self, SystemTextRegularExpressionsRegex* regex, const gchar* text, gint textbeg, gint textend, gint textstart);
	gchar* (*Result) (SystemTextRegularExpressionsMatch* self, const gchar* replacement);
	SystemTextRegularExpressionsGroupCollection* (*get_Groups) (SystemTextRegularExpressionsMatch* self);
};


static gpointer system_text_regular_expressions_match_parent_class = NULL;

gpointer system_text_regular_expressions_capture_ref (gpointer instance);
void system_text_regular_expressions_capture_unref (gpointer instance);
GParamSpec* system_text_regular_expressions_param_spec_capture (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_text_regular_expressions_value_set_capture (GValue* value, gpointer v_object);
void system_text_regular_expressions_value_take_capture (GValue* value, gpointer v_object);
gpointer system_text_regular_expressions_value_get_capture (const GValue* value);
GType system_text_regular_expressions_capture_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_group_get_type (void) G_GNUC_CONST;
gpointer system_text_regular_expressions_capture_collection_ref (gpointer instance);
void system_text_regular_expressions_capture_collection_unref (gpointer instance);
GParamSpec* system_text_regular_expressions_param_spec_capture_collection (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_text_regular_expressions_value_set_capture_collection (GValue* value, gpointer v_object);
void system_text_regular_expressions_value_take_capture_collection (GValue* value, gpointer v_object);
gpointer system_text_regular_expressions_value_get_capture_collection (const GValue* value);
GType system_text_regular_expressions_capture_collection_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_match_get_type (void) G_GNUC_CONST;
gpointer system_text_regular_expressions_static_regex_ref (gpointer instance);
void system_text_regular_expressions_static_regex_unref (gpointer instance);
GParamSpec* system_text_regular_expressions_param_spec_static_regex (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_text_regular_expressions_value_set_static_regex (GValue* value, gpointer v_object);
void system_text_regular_expressions_value_take_static_regex (GValue* value, gpointer v_object);
gpointer system_text_regular_expressions_value_get_static_regex (const GValue* value);
GType system_text_regular_expressions_static_regex_get_type (void) G_GNUC_CONST;
GType system_text_regular_expressions_regex_get_type (void) G_GNUC_CONST;
gpointer system_text_regular_expressions_group_collection_ref (gpointer instance);
void system_text_regular_expressions_group_collection_unref (gpointer instance);
GParamSpec* system_text_regular_expressions_param_spec_group_collection (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void system_text_regular_expressions_value_set_group_collection (GValue* value, gpointer v_object);
void system_text_regular_expressions_value_take_group_collection (GValue* value, gpointer v_object);
gpointer system_text_regular_expressions_value_get_group_collection (const GValue* value);
GType system_text_regular_expressions_group_collection_get_type (void) G_GNUC_CONST;
enum  {
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_DUMMY_PROPERTY
};
SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_new (GMatchInfo* matchinfo);
SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_construct (GType object_type, GMatchInfo* matchinfo);
SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_new (void);
SystemTextRegularExpressionsGroup* system_text_regular_expressions_group_construct (GType object_type);
void system_text_regular_expressions_match_Reset (SystemTextRegularExpressionsMatch* self, SystemTextRegularExpressionsRegex* regex, const gchar* text, gint textbeg, gint textend, gint textstart);
static void system_text_regular_expressions_match_real_Reset (SystemTextRegularExpressionsMatch* self, SystemTextRegularExpressionsRegex* regex, const gchar* text, gint textbeg, gint textend, gint textstart);
SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_NextMatch (SystemTextRegularExpressionsMatch* self);
gchar* system_text_regular_expressions_match_Result (SystemTextRegularExpressionsMatch* self, const gchar* replacement);
static gchar* system_text_regular_expressions_match_real_Result (SystemTextRegularExpressionsMatch* self, const gchar* replacement);
static SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_Synchronized (SystemTextRegularExpressionsMatch* inner);
SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_match_get_Groups (SystemTextRegularExpressionsMatch* self);
SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_group_collection_new (SystemTextRegularExpressionsMatch* match);
SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_group_collection_construct (GType object_type, SystemTextRegularExpressionsMatch* match);
static void system_text_regular_expressions_match_finalize (SystemTextRegularExpressionsCapture* obj);


SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_construct (GType object_type, GMatchInfo* matchinfo) {
	SystemTextRegularExpressionsMatch* self = NULL;
	GMatchInfo* _tmp0_ = NULL;
#line 43 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_val_if_fail (matchinfo != NULL, NULL);
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp0_ = matchinfo;
#line 44 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	self->_matchinfo = _tmp0_;
#line 45 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	self = (SystemTextRegularExpressionsMatch*) system_text_regular_expressions_group_construct (object_type);
#line 43 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return self;
#line 214 "RegexMatch.c"
}


SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_new (GMatchInfo* matchinfo) {
#line 43 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return system_text_regular_expressions_match_construct (SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, matchinfo);
#line 221 "RegexMatch.c"
}


static void system_text_regular_expressions_match_real_Reset (SystemTextRegularExpressionsMatch* self, SystemTextRegularExpressionsRegex* regex, const gchar* text, gint textbeg, gint textend, gint textstart) {
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_if_fail (regex != NULL);
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_if_fail (text != NULL);
#line 230 "RegexMatch.c"
}


void system_text_regular_expressions_match_Reset (SystemTextRegularExpressionsMatch* self, SystemTextRegularExpressionsRegex* regex, const gchar* text, gint textbeg, gint textend, gint textstart) {
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_if_fail (self != NULL);
#line 52 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_GET_CLASS (self)->Reset (self, regex, text, textbeg, textend, textstart);
#line 239 "RegexMatch.c"
}


static gpointer _system_text_regular_expressions_capture_ref0 (gpointer self) {
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return self ? system_text_regular_expressions_capture_ref (self) : NULL;
#line 246 "RegexMatch.c"
}


SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_NextMatch (SystemTextRegularExpressionsMatch* self) {
	SystemTextRegularExpressionsMatch* result = NULL;
	SystemTextRegularExpressionsMatch* _tmp0_ = NULL;
#line 72 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp0_ = _system_text_regular_expressions_capture_ref0 (self);
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	result = _tmp0_;
#line 74 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return result;
#line 261 "RegexMatch.c"
}


static gchar* system_text_regular_expressions_match_real_Result (SystemTextRegularExpressionsMatch* self, const gchar* replacement) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 85 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp0_ = replacement;
#line 85 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 85 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	result = _tmp1_;
#line 85 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return result;
#line 279 "RegexMatch.c"
}


gchar* system_text_regular_expressions_match_Result (SystemTextRegularExpressionsMatch* self, const gchar* replacement) {
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 82 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_GET_CLASS (self)->Result (self, replacement);
#line 288 "RegexMatch.c"
}


static SystemTextRegularExpressionsMatch* system_text_regular_expressions_match_Synchronized (SystemTextRegularExpressionsMatch* inner) {
	SystemTextRegularExpressionsMatch* result = NULL;
	SystemTextRegularExpressionsMatch* _tmp0_ = NULL;
	SystemTextRegularExpressionsMatch* _tmp1_ = NULL;
#line 97 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_val_if_fail (inner != NULL, NULL);
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp0_ = inner;
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp1_ = _system_text_regular_expressions_capture_ref0 (_tmp0_);
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	result = _tmp1_;
#line 99 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return result;
#line 306 "RegexMatch.c"
}


SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_match_get_Groups (SystemTextRegularExpressionsMatch* self) {
#line 58 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 58 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_GET_CLASS (self)->get_Groups (self);
#line 315 "RegexMatch.c"
}


static SystemTextRegularExpressionsGroupCollection* system_text_regular_expressions_match_real_get_Groups (SystemTextRegularExpressionsMatch* base) {
	SystemTextRegularExpressionsGroupCollection* result;
	SystemTextRegularExpressionsMatch* self;
	SystemTextRegularExpressionsGroupCollection* _tmp0_ = NULL;
	SystemTextRegularExpressionsGroupCollection* _tmp2_ = NULL;
#line 58 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	self = base;
#line 60 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp0_ = self->_groupcoll;
#line 60 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	if (_tmp0_ == NULL) {
#line 330 "RegexMatch.c"
		SystemTextRegularExpressionsGroupCollection* _tmp1_ = NULL;
#line 61 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
		_tmp1_ = system_text_regular_expressions_group_collection_new (self);
#line 61 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
		_system_text_regular_expressions_group_collection_unref0 (self->_groupcoll);
#line 61 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
		self->_groupcoll = _tmp1_;
#line 338 "RegexMatch.c"
	}
#line 63 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_tmp2_ = self->_groupcoll;
#line 63 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	result = _tmp2_;
#line 63 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	return result;
#line 346 "RegexMatch.c"
}


static void system_text_regular_expressions_match_class_init (SystemTextRegularExpressionsMatchClass * klass) {
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	system_text_regular_expressions_match_parent_class = g_type_class_peek_parent (klass);
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	((SystemTextRegularExpressionsCaptureClass *) klass)->finalize = system_text_regular_expressions_match_finalize;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	((SystemTextRegularExpressionsMatchClass *) klass)->Reset = system_text_regular_expressions_match_real_Reset;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	((SystemTextRegularExpressionsMatchClass *) klass)->Result = system_text_regular_expressions_match_real_Result;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_MATCH_CLASS (klass)->get_Groups = system_text_regular_expressions_match_real_get_Groups;
#line 361 "RegexMatch.c"
}


static void system_text_regular_expressions_match_instance_init (SystemTextRegularExpressionsMatch * self) {
}


static void system_text_regular_expressions_match_finalize (SystemTextRegularExpressionsCapture* obj) {
	SystemTextRegularExpressionsMatch * self;
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_MATCH, SystemTextRegularExpressionsMatch);
#line 39 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	_system_text_regular_expressions_group_collection_unref0 (self->_groupcoll);
#line 36 "/home/developer/projects/Backup/LibDotNet/src/System/Text/RegularExpressions/RegexMatch.vala"
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_CAPTURE_CLASS (system_text_regular_expressions_match_parent_class)->finalize (obj);
#line 377 "RegexMatch.c"
}


GType system_text_regular_expressions_match_get_type (void) {
	static volatile gsize system_text_regular_expressions_match_type_id__volatile = 0;
	if (g_once_init_enter (&system_text_regular_expressions_match_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SystemTextRegularExpressionsMatchClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) system_text_regular_expressions_match_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SystemTextRegularExpressionsMatch), 0, (GInstanceInitFunc) system_text_regular_expressions_match_instance_init, NULL };
		GType system_text_regular_expressions_match_type_id;
		system_text_regular_expressions_match_type_id = g_type_register_static (SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_GROUP, "SystemTextRegularExpressionsMatch", &g_define_type_info, 0);
		g_once_init_leave (&system_text_regular_expressions_match_type_id__volatile, system_text_regular_expressions_match_type_id);
	}
	return system_text_regular_expressions_match_type_id__volatile;
}



