/* RegexOptions.c generated by valac 0.26.2, the Vala compiler
 * generated from RegexOptions.vala, do not modify */

/* Copyright (c) Microsoft. All rights reserved.*/
/* Licensed under the MIT license. See LICENSE file in the project root for full license information.*/

#include <glib.h>
#include <glib-object.h>


#define SYSTEM_TEXT_REGULAR_EXPRESSIONS_TYPE_REGEX_OPTIONS (system_text_regular_expressions_regex_options_get_type ())

typedef enum  {
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_None = 0x0000,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_IgnoreCase = 0x0001,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Multiline = 0x0002,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_ExplicitCapture = 0x0004,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Compiled = 0x0008,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Singleline = 0x0010,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_IgnorePatternWhitespace = 0x0020,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_RightToLeft = 0x0040,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_ECMAScript = 0x0100,
	SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_CultureInvariant = 0x0200
} SystemTextRegularExpressionsRegexOptions;



GType system_text_regular_expressions_regex_options_get_type (void) G_GNUC_CONST;


GType system_text_regular_expressions_regex_options_get_type (void) {
	static volatile gsize system_text_regular_expressions_regex_options_type_id__volatile = 0;
	if (g_once_init_enter (&system_text_regular_expressions_regex_options_type_id__volatile)) {
		static const GEnumValue values[] = {{SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_None, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_None", "none"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_IgnoreCase, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_IgnoreCase", "ignorecase"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Multiline, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Multiline", "multiline"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_ExplicitCapture, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_ExplicitCapture", "explicitcapture"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Compiled, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Compiled", "compiled"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Singleline, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_Singleline", "singleline"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_IgnorePatternWhitespace, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_IgnorePatternWhitespace", "ignorepatternwhitespace"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_RightToLeft, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_RightToLeft", "righttoleft"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_ECMAScript, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_ECMAScript", "ecmascript"}, {SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_CultureInvariant, "SYSTEM_TEXT_REGULAR_EXPRESSIONS_REGEX_OPTIONS_CultureInvariant", "cultureinvariant"}, {0, NULL, NULL}};
		GType system_text_regular_expressions_regex_options_type_id;
		system_text_regular_expressions_regex_options_type_id = g_enum_register_static ("SystemTextRegularExpressionsRegexOptions", values);
		g_once_init_leave (&system_text_regular_expressions_regex_options_type_id__volatile, system_text_regular_expressions_regex_options_type_id);
	}
	return system_text_regular_expressions_regex_options_type_id__volatile;
}



